/********************************************************************
*
* C7X256V0_CLEC INTERRUPT MAP. header file
*
* Copyright (C) 2015-2020 Texas Instruments Incorporated.
*  Redistribution and use in source and binary forms, with or without
*  modification, are permitted provided that the following conditions
*  are met:
*
*    Redistributions of source code must retain the above copyright
*    notice, this list of conditions and the following disclaimer.
*
*    Redistributions in binary form must reproduce the above copyright
*    notice, this list of conditions and the following disclaimer in the
*    documentation and/or other materials provided with the
*    distribution.
*
*    Neither the name of Texas Instruments Incorporated nor the names of
*    its contributors may be used to endorse or promote products derived
*    from this software without specific prior written permission.
*
*  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
*  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
*  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
*  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
*  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
*  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
*  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
*  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
*  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
*  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
*  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*
*/
#ifndef CSLR_C7X256V0_CLEC_INTERRUPT_MAP_H_
#define CSLR_C7X256V0_CLEC_INTERRUPT_MAP_H_

#include <drivers/hw_include/cslr.h>
#include <drivers/hw_include/tistdtypes.h>
#ifdef __cplusplus
extern "C"
{
#endif

/*
* List of intr sources for receiver: C7X256V0_CLEC
*/

#define CSLR_C7X256V0_CLEC_ARM_0_EVENTO_IN_COMPUTE_CLUSTER0_CPU_EVNT_EVENTO_0                      (0U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_MAIN_GPIOMUX_INTROUTER0_OUTP_0                                  (0U)
#define CSLR_C7X256V0_CLEC_SOC_EVENTS_IN_MAILBOX0_MAILBOX_CLUSTER_0_MAILBOX_CLUSTER0_PEND_1        (0U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_MAIN_GPIOMUX_INTROUTER0_OUTP_1                                  (1U)
#define CSLR_C7X256V0_CLEC_SOC_EVENTS_IN_MAILBOX0_MAILBOX_CLUSTER_0_MAILBOX_CLUSTER1_PEND_1        (1U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_MAIN_GPIOMUX_INTROUTER0_OUTP_2                                  (2U)
#define CSLR_C7X256V0_CLEC_SOC_EVENTS_IN_MAILBOX0_MAILBOX_CLUSTER_0_MAILBOX_CLUSTER2_PEND_1        (2U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_MAIN_GPIOMUX_INTROUTER0_OUTP_3                                  (3U)
#define CSLR_C7X256V0_CLEC_SOC_EVENTS_IN_MAILBOX0_MAILBOX_CLUSTER_0_MAILBOX_CLUSTER3_PEND_1        (3U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_MAIN_GPIOMUX_INTROUTER0_OUTP_4                                  (4U)
#define CSLR_C7X256V0_CLEC_SOC_EVENTS_IN_RTI4_INTR_WWD_0                                           (4U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_MAIN_GPIOMUX_INTROUTER0_OUTP_5                                  (5U)
#define CSLR_C7X256V0_CLEC_SOC_EVENTS_IN_CTRL_MMR0_IPC_SET0_IPC_SET_IPCFG_0                        (5U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_MAIN_GPIOMUX_INTROUTER0_OUTP_6                                  (6U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_MAIN_GPIOMUX_INTROUTER0_OUTP_7                                  (7U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_MAIN_GPIOMUX_INTROUTER0_OUTP_8                                  (8U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_MAIN_GPIOMUX_INTROUTER0_OUTP_9                                  (9U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_MAIN_GPIOMUX_INTROUTER0_OUTP_10                                 (10U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_MAIN_GPIOMUX_INTROUTER0_OUTP_11                                 (11U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_MAIN_GPIOMUX_INTROUTER0_OUTP_12                                 (12U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_MAIN_GPIOMUX_INTROUTER0_OUTP_13                                 (13U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_MAIN_GPIOMUX_INTROUTER0_OUTP_14                                 (14U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_MAIN_GPIOMUX_INTROUTER0_OUTP_15                                 (15U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_CMP_EVENT_INTROUTER0_OUTP_0                                     (16U)
#define CSLR_C7X256V0_CLEC_SOC_EVENTS_IN_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_84                    (16U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_CMP_EVENT_INTROUTER0_OUTP_1                                     (17U)
#define CSLR_C7X256V0_CLEC_SOC_EVENTS_IN_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_85                    (17U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_CMP_EVENT_INTROUTER0_OUTP_2                                     (18U)
#define CSLR_C7X256V0_CLEC_SOC_EVENTS_IN_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_86                    (18U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_CMP_EVENT_INTROUTER0_OUTP_3                                     (19U)
#define CSLR_C7X256V0_CLEC_SOC_EVENTS_IN_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_87                    (19U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_CMP_EVENT_INTROUTER0_OUTP_4                                     (20U)
#define CSLR_C7X256V0_CLEC_SOC_EVENTS_IN_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_88                    (20U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_CMP_EVENT_INTROUTER0_OUTP_5                                     (21U)
#define CSLR_C7X256V0_CLEC_SOC_EVENTS_IN_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_89                    (21U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_CMP_EVENT_INTROUTER0_OUTP_6                                     (22U)
#define CSLR_C7X256V0_CLEC_SOC_EVENTS_IN_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_90                    (22U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_CMP_EVENT_INTROUTER0_OUTP_7                                     (23U)
#define CSLR_C7X256V0_CLEC_SOC_EVENTS_IN_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_91                    (23U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_CMP_EVENT_INTROUTER0_OUTP_8                                     (24U)
#define CSLR_C7X256V0_CLEC_SOC_EVENTS_IN_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_92                    (24U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_CMP_EVENT_INTROUTER0_OUTP_9                                     (25U)
#define CSLR_C7X256V0_CLEC_SOC_EVENTS_IN_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_93                    (25U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_CMP_EVENT_INTROUTER0_OUTP_10                                    (26U)
#define CSLR_C7X256V0_CLEC_SOC_EVENTS_IN_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_94                    (26U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_CMP_EVENT_INTROUTER0_OUTP_11                                    (27U)
#define CSLR_C7X256V0_CLEC_SOC_EVENTS_IN_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_95                    (27U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_CMP_EVENT_INTROUTER0_OUTP_12                                    (28U)
#define CSLR_C7X256V0_CLEC_SOC_EVENTS_IN_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_96                    (28U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_CMP_EVENT_INTROUTER0_OUTP_13                                    (29U)
#define CSLR_C7X256V0_CLEC_SOC_EVENTS_IN_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_97                    (29U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_CMP_EVENT_INTROUTER0_OUTP_14                                    (30U)
#define CSLR_C7X256V0_CLEC_SOC_EVENTS_IN_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_98                    (30U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_CMP_EVENT_INTROUTER0_OUTP_15                                    (31U)
#define CSLR_C7X256V0_CLEC_SOC_EVENTS_IN_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_99                    (31U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_0                           (32U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_1                           (33U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_2                           (34U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_3                           (35U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_4                           (36U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_5                           (37U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_6                           (38U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_7                           (39U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_8                           (40U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_9                           (41U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_10                          (42U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_11                          (43U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_12                          (44U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_13                          (45U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_14                          (46U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_15                          (47U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_16                          (48U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_17                          (49U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_18                          (50U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_19                          (51U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_20                          (52U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_21                          (53U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_22                          (54U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_23                          (55U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_24                          (56U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_25                          (57U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_26                          (58U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_27                          (59U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_28                          (60U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_29                          (61U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_30                          (62U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_31                          (63U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_32                          (64U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_33                          (65U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_34                          (66U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_35                          (67U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_36                          (68U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_37                          (69U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_38                          (70U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS0_INTAGGR_0_INTAGGR_VINTR_PEND_39                          (71U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_WKUP_MCU_GPIOMUX_INTROUTER0_OUTP_0                              (72U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_WKUP_MCU_GPIOMUX_INTROUTER0_OUTP_1                              (73U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_WKUP_MCU_GPIOMUX_INTROUTER0_OUTP_2                              (74U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_WKUP_MCU_GPIOMUX_INTROUTER0_OUTP_3                              (75U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_MAILBOX0_MAILBOX_CLUSTER_0_MAILBOX_CLUSTER0_PEND_0              (76U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_MAILBOX0_MAILBOX_CLUSTER_0_MAILBOX_CLUSTER1_PEND_0              (77U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_GLUELOGIC_MAINRESET_REQUEST_GLUE_MAIN_PORZ_SYNC_STRETCH_0       (78U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_GLUELOGIC_MAINRESET_REQUEST_GLUE_MAIN_RESETZ_SYNC_STRETCH_0     (79U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_SA3_SS0_INTAGGR_0_INTAGGR_VINTR_4                               (80U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_SA3_SS0_INTAGGR_0_INTAGGR_VINTR_5                               (81U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_MMCSD2_EMMCSDSS_INTR_0                                          (82U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_MMCSD1_EMMCSDSS_INTR_0                                          (83U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DSS0_DISPC_INTR_REQ_0_0                                         (84U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DSS0_DISPC_INTR_REQ_1_0                                         (85U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_GLUELOGIC_MAIN_DCC_DONE_GLUE_DCC_DONE_0                         (96U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_GLUELOGIC_SOC_ACCESS_ERR_INTR_GLUE_OUT_0                        (97U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_JPGENC0_IRQ_0                                                   (98U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_WKUP_RTCSS0_RTC_EVENT_PEND_0                                    (100U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_GLUELOGIC_SOC_CBASS_ERR_INTR_GLUE_MAIN_CBASS_AGG_ERR_INTR_0     (101U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_CPSW0_EVNT_PEND_0                                               (102U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_CPSW0_MDIO_PEND_0                                               (103U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_CPSW0_STAT_PEND_0                                               (104U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_GPMC0_GPMC_SINTERRUPT_0                                         (106U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_MCU_I2C0_POINTRPEND_0                                           (107U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_MAILBOX0_MAILBOX_CLUSTER_0_MAILBOX_CLUSTER2_PEND_0              (108U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_MAILBOX0_MAILBOX_CLUSTER_0_MAILBOX_CLUSTER3_PEND_0              (109U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_SMS0_TIFS_CBASS_0_FW_EXCEPTION_INTR_0                           (111U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_SMS0_COMMON_0_COMBINED_SEC_IN_0                                 (112U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_ECAP0_ECAP_INT_0                                                (113U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_ECAP1_ECAP_INT_0                                                (114U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_ECAP2_ECAP_INT_0                                                (115U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_EQEP0_EQEP_INT_0                                                (116U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_EQEP1_EQEP_INT_0                                                (117U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_EQEP2_EQEP_INT_0                                                (118U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DDR32SS0_DDRSS_CONTROLLER_0                                     (119U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_TIMER0_INTR_PEND_0                                              (120U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_TIMER1_INTR_PEND_0                                              (121U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_TIMER2_INTR_PEND_0                                              (122U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_TIMER3_INTR_PEND_0                                              (123U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_TIMER4_INTR_PEND_0                                              (124U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_TIMER5_INTR_PEND_0                                              (125U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_TIMER6_INTR_PEND_0                                              (126U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_TIMER7_INTR_PEND_0                                              (127U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_SA3_SS0_SA_UL_0_SA_UL_PKA_0                                     (128U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_SA3_SS0_SA_UL_0_SA_UL_TRNG_0                                    (129U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_ELM0_ELM_POROCPSINTERRUPT_LVL_0                                 (132U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_MMCSD0_EMMCSDSS_INTR_0                                          (133U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_MCRC64_0_INT_MCRC_0                                             (134U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_VPAC0_VPAC_LEVEL_0                                              (136U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_VPAC0_VPAC_LEVEL_1                                              (137U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_VPAC0_VPAC_LEVEL_2                                              (138U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DDR32SS0_DDRSS_PLL_FREQ_CHANGE_REQ_0                            (140U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_CSI_RX_IF0_CSI_IRQ_0                                            (141U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_CSI_RX_IF0_CSI_LEVEL_0                                          (142U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_CSI_RX_IF0_CSI_ERR_IRQ_0                                        (143U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_SMS0_AESEIP38T_0_AES_SINTREQUEST_P_0                            (144U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DDPA0_DDPA_INTR_0                                               (145U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_ESM0_ESM_INT_CFG_LVL_0                                          (148U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_ESM0_ESM_INT_HI_LVL_0                                           (149U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_ESM0_ESM_INT_LOW_LVL_0                                          (150U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_WKUP_VTM0_THERM_LVL_GT_TH1_INTR_0                               (151U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_WKUP_VTM0_THERM_LVL_GT_TH2_INTR_0                               (152U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_WKUP_VTM0_THERM_LVL_LT_TH0_INTR_0                               (153U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_MCAN0_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                          (154U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_MCAN0_MCANSS_MCAN_LVL_INT_0                                     (155U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_MCAN0_MCANSS_MCAN_LVL_INT_1                                     (156U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_VPAC0_VPAC_LEVEL_3                                              (157U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_VPAC0_VPAC_LEVEL_4                                              (158U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_VPAC0_VPAC_LEVEL_5                                              (159U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_MCU_MCRC64_0_INT_MCRC_0                                         (160U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_I2C0_POINTRPEND_0                                               (161U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_I2C1_POINTRPEND_0                                               (162U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_I2C2_POINTRPEND_0                                               (163U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_I2C3_POINTRPEND_0                                               (164U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_SMS0_AESEIP38T_0_AES_SINTREQUEST_S_0                            (166U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DEBUGSS0_AQCMPINTR_LEVEL_0                                      (169U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DEBUGSS0_CTM_LEVEL_0                                            (170U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_PSC0_PSC_ALLINT_0                                               (171U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_MCSPI0_INTR_SPI_0                                               (172U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_MCSPI1_INTR_SPI_0                                               (173U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_MCSPI2_INTR_SPI_0                                               (174U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_MCU_MCSPI0_INTR_SPI_0                                           (176U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_MCU_MCSPI1_INTR_SPI_0                                           (177U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_UART0_USART_IRQ_0                                               (178U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_UART1_USART_IRQ_0                                               (179U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_UART2_USART_IRQ_0                                               (180U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_UART3_USART_IRQ_0                                               (181U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_UART4_USART_IRQ_0                                               (182U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_UART5_USART_IRQ_0                                               (183U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_UART6_USART_IRQ_0                                               (184U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_MCU_UART0_USART_IRQ_0                                           (185U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_WKUP_UART0_USART_IRQ_0                                          (186U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_USB0_IRQ_0                                                      (188U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_USB0_IRQ_1                                                      (189U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_USB0_IRQ_2                                                      (190U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_USB0_IRQ_3                                                      (191U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_USB0_IRQ_4                                                      (192U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_USB0_IRQ_5                                                      (193U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_USB0_IRQ_6                                                      (194U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_USB0_IRQ_7                                                      (195U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_USB0_MISC_LEVEL_0                                               (196U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_EPWM0_EPWM_ETINT_0                                              (197U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_EPWM0_EPWM_TRIPZINT_0                                           (198U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_EPWM1_EPWM_ETINT_0                                              (199U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_EPWM1_EPWM_TRIPZINT_0                                           (201U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_EPWM2_EPWM_ETINT_0                                              (202U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_EPWM2_EPWM_TRIPZINT_0                                           (203U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_0                           (205U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_1                           (206U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_2                           (207U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_DMASS1_INTAGGR_0_INTAGGR_VINTR_PEND_3                           (208U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_RTI0_INTR_WWD_0                                                 (220U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_RTI1_INTR_WWD_0                                                 (221U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_RTI2_INTR_WWD_0                                                 (222U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_RTI3_INTR_WWD_0                                                 (223U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_GLUELOGIC_GLUE_EXT_INTN_OUT_0                                   (224U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_USB1_IRQ_0                                                      (226U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_USB1_IRQ_1                                                      (227U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_USB1_IRQ_2                                                      (228U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_USB1_IRQ_3                                                      (229U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_USB1_IRQ_4                                                      (230U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_USB1_IRQ_5                                                      (231U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_USB1_IRQ_6                                                      (232U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_USB1_IRQ_7                                                      (233U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_USB1_MISC_LEVEL_0                                               (234U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_MCASP0_REC_INTR_PEND_0                                          (235U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_MCASP0_XMIT_INTR_PEND_0                                         (236U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_MCASP1_REC_INTR_PEND_0                                          (237U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_MCASP1_XMIT_INTR_PEND_0                                         (238U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_MCASP2_REC_INTR_PEND_0                                          (239U)
#define CSLR_C7X256V0_CLEC_GIC_SPI_MCASP2_XMIT_INTR_PEND_0                                         (240U)

#ifdef __cplusplus
}
#endif
#endif /* CSLR_C7X256V0_CLEC_INTERRUPT_MAP_H_ */

