#
# Auto generated makefile
#

all:
	$(MAKE) -f makefile.am62ax libs
	$(MAKE) -f makefile.am62ax sbl
	$(MAKE) -f makefile.am62ax examples

clean: libs-clean sbl-clean examples-clean
scrub: libs-scrub sbl-scrub examples-scrub

help:
	@echo  Notes,
	@echo  - Use -j to invoke parallel builds
	@echo  - Use PROFILE=debug or PROFILE=release [default] to build in debug or release profile
	@echo  .
	@echo  Overall build targets,
	@echo  ======================
	@echo  $(MAKE) -s -f makefile.am62ax help
	@echo  .
	@echo  $(MAKE) -s -f makefile.am62ax all
	@echo  $(MAKE) -s -f makefile.am62ax clean  # delete's tmp files for current profile
	@echo  $(MAKE) -s -f makefile.am62ax scrub  # delete's all tmp files and folders for all profiles
	@echo  .
	@echo  $(MAKE) -s -f makefile.am62ax libs
	@echo  $(MAKE) -s -f makefile.am62ax libs-clean # delete's tmp files for current profile
	@echo  $(MAKE) -s -f makefile.am62ax libs-scrub # delete's all tmp files and folders for all profiles
	@echo  .
	@echo  $(MAKE) -s -f makefile.am62ax examples
	@echo  $(MAKE) -s -f makefile.am62ax examples-clean # delete's tmp files for current profile
	@echo  $(MAKE) -s -f makefile.am62ax examples-scrub # delete's all tmp files and folders for all profiles
	@echo  .
	@echo  Library build targets,
	@echo  ======================
	@echo  $(MAKE) -s -f makefile.am62ax unity_r5f.ti-arm-clang
	@echo  $(MAKE) -s -f makefile.am62ax doxy_samples_r5f.ti-arm-clang
	@echo  .
	@echo  Library clean targets,
	@echo  ======================
	@echo  $(MAKE) -s -f makefile.am62ax unity_r5f.ti-arm-clang_clean
	@echo  $(MAKE) -s -f makefile.am62ax doxy_samples_r5f.ti-arm-clang_clean
	@echo  .
	@echo  Example build targets,
	@echo  ======================
	@echo  $(MAKE) -s -C sdl/mcrc/mcrcUt/am62ax-sk/mcu-r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C sdl/mcrc/mcrcFuncTest/am62ax-sk/mcu-r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C sdl/esm/esm_func_test/am62ax-sk/mcu-r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C sdl/esm/esm_unit_test/am62ax-sk/mcu-r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C sdl/vtm/vtm_func_test/am62ax-sk/mcu-r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C sdl/vtm/vtm_unit_test/am62ax-sk/mcu-r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C kernel/dpl/am62ax-sk/mcu-r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C kernel/dpl/am62ax-sk/mcu-r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C kernel/freertos/am62ax-sk/mcu-r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C kernel/rov/am62ax-sk/mcu-r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/gpio/am62ax-sk/mcu-r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/gtc/am62ax-sk/mcu-r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/sciclient/am62ax-sk/mcu-r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/i2c/am62ax-sk/mcu-r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/i2c/am62ax-sk/r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/uart/am62ax-sk/mcu-r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  .
	@echo  System Example build targets,
	@echo  =============================
	@echo  .

# Various Component Targets
BUILD_COMBO_unity = unity_r5f.ti-arm-clang
BUILD_COMBO_doxy_samples = doxy_samples_r5f.ti-arm-clang

# Combine all Components
BUILD_COMBO_ALL = $(BUILD_COMBO_unity) $(BUILD_COMBO_doxy_samples)

# Combine all Pre-built Components
BUILD_COMBO_PREBUILT_ALL =

# Combine all Private Components
BUILD_COMBO_PRIVATE_ALL =

libs: $(BUILD_COMBO_ALL)

libs-prebuilt: $(BUILD_COMBO_PREBUILT_ALL)

libs-private: $(BUILD_COMBO_PRIVATE_ALL)

$(BUILD_COMBO_unity):
	$(MAKE) -C unity -f makefile.am62ax.$(subst unity_,,$@) all

$(BUILD_COMBO_doxy_samples):
	$(MAKE) -C ../docs_src/docs/api_guide/doxy_samples -f makefile.am62ax.$(subst doxy_samples_,,$@) all


# Various Component Clean Targets
BUILD_COMBO_CLEAN_unity = unity_r5f.ti-arm-clang_clean
BUILD_COMBO_CLEAN_doxy_samples = doxy_samples_r5f.ti-arm-clang_clean

# Combine all Components Clean
BUILD_COMBO_CLEAN_ALL = $(BUILD_COMBO_CLEAN_unity) $(BUILD_COMBO_CLEAN_doxy_samples)

# Combine all Pre-built Components Clean
BUILD_COMBO_PREBUILT_CLEAN_ALL =

libs-clean: $(BUILD_COMBO_CLEAN_ALL)

libs-prebuilt-clean: $(BUILD_COMBO_PREBUILT_CLEAN_ALL)

$(BUILD_COMBO_CLEAN_unity):
	$(MAKE) -C unity -f makefile.am62ax.$(subst unity_,,$(subst _clean,,$@)) clean

$(BUILD_COMBO_CLEAN_doxy_samples):
	$(MAKE) -C ../docs_src/docs/api_guide/doxy_samples -f makefile.am62ax.$(subst doxy_samples_,,$(subst _clean,,$@)) clean


# Various Component Scrub Targets
BUILD_COMBO_SCRUB_unity = unity_r5f.ti-arm-clang_scrub_scrub
BUILD_COMBO_SCRUB_doxy_samples = doxy_samples_r5f.ti-arm-clang_scrub_scrub

# Combine all Components Scrub Targets
BUILD_COMBO_SCRUB_ALL = $(BUILD_COMBO_SCRUB_unity) $(BUILD_COMBO_SCRUB_doxy_samples)

# Combine all Pre-built Components Scrub Targets
BUILD_COMBO_PREBUILT_SCRUB_ALL =

libs-scrub: $(BUILD_COMBO_SCRUB_ALL)

libs-prebuilt-scrub: $(BUILD_COMBO_PREBUILT_SCRUB_ALL)

$(BUILD_COMBO_SCRUB_unity):
	$(MAKE) -C unity -f makefile.am62ax.$(subst unity_,,$(subst _scrub,,$@)) scrub

$(BUILD_COMBO_SCRUB_doxy_samples):
	$(MAKE) -C ../docs_src/docs/api_guide/doxy_samples -f makefile.am62ax.$(subst doxy_samples_,,$(subst _scrub,,$@)) scrub


BUILD_COMBO_EXAMPLE_ALL =
# Various Example Targets
BUILD_COMBO_EXAMPLE_ALL += mcrc_test_app_am62ax-sk_mcu-r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += sdl_mcrc_test_app_am62ax-sk_mcu-r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_esm_func_am62ax-sk_mcu-r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_esm_unit_am62ax-sk_mcu-r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += sdl_vtm_test_app_am62ax-sk_mcu-r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += vtm_test_app_am62ax-sk_mcu-r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_dpl_am62ax-sk_mcu-r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_dpl_am62ax-sk_mcu-r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_freertos_am62ax-sk_mcu-r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_rov_am62ax-sk_mcu-r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_gpio_am62ax-sk_mcu-r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_gtc_am62ax-sk_mcu-r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_sciclient_am62ax-sk_mcu-r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_i2c_am62ax-sk_mcu-r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_i2c_am62ax-sk_r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_uart_am62ax-sk_mcu-r5fss0-0_freertos_ti-arm-clang
# Various System Example Targets

BUILD_COMBO_EXAMPLE_PRIVATE_ALL =
# Various Private Example Targets
# Various Private System Example Targets

examples: $(BUILD_COMBO_EXAMPLE_ALL)

examples-private: $(BUILD_COMBO_EXAMPLE_PRIVATE_ALL)

 mcrc_test_app_am62ax-sk_mcu-r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C sdl/mcrc/mcrcUt/am62ax-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile all

 sdl_mcrc_test_app_am62ax-sk_mcu-r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C sdl/mcrc/mcrcFuncTest/am62ax-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile all

 test_esm_func_am62ax-sk_mcu-r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C sdl/esm/esm_func_test/am62ax-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile all

 test_esm_unit_am62ax-sk_mcu-r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C sdl/esm/esm_unit_test/am62ax-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile all

 sdl_vtm_test_app_am62ax-sk_mcu-r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C sdl/vtm/vtm_func_test/am62ax-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile all

 vtm_test_app_am62ax-sk_mcu-r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C sdl/vtm/vtm_unit_test/am62ax-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile all

 test_dpl_am62ax-sk_mcu-r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C kernel/dpl/am62ax-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile all

 test_dpl_am62ax-sk_mcu-r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C kernel/dpl/am62ax-sk/mcu-r5fss0-0_freertos/ti-arm-clang -f makefile all

 test_freertos_am62ax-sk_mcu-r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C kernel/freertos/am62ax-sk/mcu-r5fss0-0_freertos/ti-arm-clang -f makefile all

 test_rov_am62ax-sk_mcu-r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C kernel/rov/am62ax-sk/mcu-r5fss0-0_freertos/ti-arm-clang -f makefile all

 test_gpio_am62ax-sk_mcu-r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C drivers/gpio/am62ax-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile all

 test_gtc_am62ax-sk_mcu-r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C drivers/gtc/am62ax-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile all

 test_sciclient_am62ax-sk_mcu-r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C drivers/sciclient/am62ax-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile all

 test_i2c_am62ax-sk_mcu-r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C drivers/i2c/am62ax-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile all

 test_i2c_am62ax-sk_r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C drivers/i2c/am62ax-sk/r5fss0-0_nortos/ti-arm-clang -f makefile all

 test_uart_am62ax-sk_mcu-r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C drivers/uart/am62ax-sk/mcu-r5fss0-0_freertos/ti-arm-clang -f makefile all


BUILD_COMBO_EXAMPLE_CLEAN_ALL =
# Various Example Clean Targets
BUILD_COMBO_EXAMPLE_CLEAN_ALL += mcrc_test_app_am62ax-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += sdl_mcrc_test_app_am62ax-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_esm_func_am62ax-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_esm_unit_am62ax-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += sdl_vtm_test_app_am62ax-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += vtm_test_app_am62ax-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_dpl_am62ax-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_dpl_am62ax-sk_mcu-r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_freertos_am62ax-sk_mcu-r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_rov_am62ax-sk_mcu-r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_gpio_am62ax-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_gtc_am62ax-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_sciclient_am62ax-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_i2c_am62ax-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_i2c_am62ax-sk_r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_uart_am62ax-sk_mcu-r5fss0-0_freertos_ti-arm-clang_clean
# Various System Example Clean Targets

BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL =
# Various Private Example Targets
# Various Private System Example Targets

examples-clean: $(BUILD_COMBO_EXAMPLE_CLEAN_ALL)

examples-private-clean: $(BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL)

 mcrc_test_app_am62ax-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C sdl/mcrc/mcrcUt/am62ax-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile clean

 sdl_mcrc_test_app_am62ax-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C sdl/mcrc/mcrcFuncTest/am62ax-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile clean

 test_esm_func_am62ax-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C sdl/esm/esm_func_test/am62ax-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile clean

 test_esm_unit_am62ax-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C sdl/esm/esm_unit_test/am62ax-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile clean

 sdl_vtm_test_app_am62ax-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C sdl/vtm/vtm_func_test/am62ax-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile clean

 vtm_test_app_am62ax-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C sdl/vtm/vtm_unit_test/am62ax-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile clean

 test_dpl_am62ax-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C kernel/dpl/am62ax-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile clean

 test_dpl_am62ax-sk_mcu-r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C kernel/dpl/am62ax-sk/mcu-r5fss0-0_freertos/ti-arm-clang -f makefile clean

 test_freertos_am62ax-sk_mcu-r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C kernel/freertos/am62ax-sk/mcu-r5fss0-0_freertos/ti-arm-clang -f makefile clean

 test_rov_am62ax-sk_mcu-r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C kernel/rov/am62ax-sk/mcu-r5fss0-0_freertos/ti-arm-clang -f makefile clean

 test_gpio_am62ax-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C drivers/gpio/am62ax-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile clean

 test_gtc_am62ax-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C drivers/gtc/am62ax-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile clean

 test_sciclient_am62ax-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C drivers/sciclient/am62ax-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile clean

 test_i2c_am62ax-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C drivers/i2c/am62ax-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile clean

 test_i2c_am62ax-sk_r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C drivers/i2c/am62ax-sk/r5fss0-0_nortos/ti-arm-clang -f makefile clean

 test_uart_am62ax-sk_mcu-r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C drivers/uart/am62ax-sk/mcu-r5fss0-0_freertos/ti-arm-clang -f makefile clean


BUILD_COMBO_EXAMPLE_SCRUB_ALL =
# Various Example Scrub Targets
BUILD_COMBO_EXAMPLE_SCRUB_ALL += mcrc_test_app_am62ax-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += sdl_mcrc_test_app_am62ax-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_esm_func_am62ax-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_esm_unit_am62ax-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += sdl_vtm_test_app_am62ax-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += vtm_test_app_am62ax-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_dpl_am62ax-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_dpl_am62ax-sk_mcu-r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_freertos_am62ax-sk_mcu-r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_rov_am62ax-sk_mcu-r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_gpio_am62ax-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_gtc_am62ax-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_sciclient_am62ax-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_i2c_am62ax-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_i2c_am62ax-sk_r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_uart_am62ax-sk_mcu-r5fss0-0_freertos_ti-arm-clang_scrub
# Various System Example Scrub Targets

BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL =
# Various Private Example Targets
# Various Private System Example Targets

examples-scrub: $(BUILD_COMBO_EXAMPLE_SCRUB_ALL)

examples-scrub-private: $(BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL)

 mcrc_test_app_am62ax-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C sdl/mcrc/mcrcUt/am62ax-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 sdl_mcrc_test_app_am62ax-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C sdl/mcrc/mcrcFuncTest/am62ax-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 test_esm_func_am62ax-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C sdl/esm/esm_func_test/am62ax-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 test_esm_unit_am62ax-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C sdl/esm/esm_unit_test/am62ax-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 sdl_vtm_test_app_am62ax-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C sdl/vtm/vtm_func_test/am62ax-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 vtm_test_app_am62ax-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C sdl/vtm/vtm_unit_test/am62ax-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 test_dpl_am62ax-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C kernel/dpl/am62ax-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 test_dpl_am62ax-sk_mcu-r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C kernel/dpl/am62ax-sk/mcu-r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 test_freertos_am62ax-sk_mcu-r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C kernel/freertos/am62ax-sk/mcu-r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 test_rov_am62ax-sk_mcu-r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C kernel/rov/am62ax-sk/mcu-r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 test_gpio_am62ax-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C drivers/gpio/am62ax-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 test_gtc_am62ax-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C drivers/gtc/am62ax-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 test_sciclient_am62ax-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C drivers/sciclient/am62ax-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 test_i2c_am62ax-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C drivers/i2c/am62ax-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 test_i2c_am62ax-sk_r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C drivers/i2c/am62ax-sk/r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 test_uart_am62ax-sk_mcu-r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C drivers/uart/am62ax-sk/mcu-r5fss0-0_freertos/ti-arm-clang -f makefile scrub


sbl: libs

sbl-clean:

sbl-scrub:


.PHONY: all clean scrub help
.PHONY: libs libs-clean libs-scrub
.PHONY: libs-private
.PHONY: libs-prebuilt libs-prebuilt-clean libs-prebuilt-scrub
.PHONY: examples examples-clean examples-scrub
.PHONY: examples-private examples-private-clean examples-private-scrub
.PHONY: sbl sbl-clean sbl-scrub
.PHONY: $(BUILD_COMBO_ALL) $(BUILD_COMBO_CLEAN_ALL) $(BUILD_COMBO_SCRUB_ALL)
.PHONY: $(BUILD_COMBO_EXAMPLE_ALL) $(BUILD_COMBO_EXAMPLE_CLEAN_ALL) $(BUILD_COMBO_EXAMPLE_SCRUB_ALL)
.PHONY: $(BUILD_COMBO_EXAMPLE_PRIVATE_ALL) $(BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL) $(BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL)
