#
# Auto generated makefile
#

all:
	$(MAKE) -f makefile.j722s libs
	$(MAKE) -f makefile.j722s libs-external
	$(MAKE) -f makefile.j722s sbl
	$(MAKE) -f makefile.j722s examples

clean: libs-clean libs-external-clean sbl-clean examples-clean
scrub: libs-scrub libs-external-scrub sbl-scrub examples-scrub

help:
	@echo  Notes,
	@echo  - Use -j to invoke parallel builds
	@echo  - Use PROFILE=debug or PROFILE=release [default] to build in debug or release profile
	@echo  .
	@echo  Overall build targets,
	@echo  ======================
	@echo  $(MAKE) -s -f makefile.j722s help
	@echo  .
	@echo  $(MAKE) -s -f makefile.j722s all
	@echo  $(MAKE) -s -f makefile.j722s clean  # delete's tmp files for current profile
	@echo  $(MAKE) -s -f makefile.j722s scrub  # delete's all tmp files and folders for all profiles
	@echo  .
	@echo  $(MAKE) -s -f makefile.j722s libs
	@echo  $(MAKE) -s -f makefile.j722s libs-clean # delete's tmp files for current profile
	@echo  $(MAKE) -s -f makefile.j722s libs-scrub # delete's all tmp files and folders for all profiles
	@echo  .
	@echo  $(MAKE) -s -f makefile.j722s examples
	@echo  $(MAKE) -s -f makefile.j722s examples-clean # delete's tmp files for current profile
	@echo  $(MAKE) -s -f makefile.j722s examples-scrub # delete's all tmp files and folders for all profiles
	@echo  .
	@echo  Library build targets,
	@echo  ======================
	@echo  $(MAKE) -s -f makefile.j722s doxy_samples_r5f.ti-arm-clang
	@echo  $(MAKE) -s -f makefile.j722s unity_r5f.ti-arm-clang unity_a53.gcc-aarch64 unity_c75x.ti-c7000
	@echo  .
	@echo  Library clean targets,
	@echo  ======================
	@echo  $(MAKE) -s -f makefile.j722s doxy_samples_r5f.ti-arm-clang_clean
	@echo  $(MAKE) -s -f makefile.j722s unity_r5f.ti-arm-clang_clean unity_a53.gcc-aarch64_clean unity_c75x.ti-c7000_clean
	@echo  .
	@echo  Example build targets,
	@echo  ======================
	@echo  $(MAKE) -s -C board/flash/j722s-evm/wkup-r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/gpio/j722s-evm/mcu-r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/gpio/j722s-evm/main-r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/gpio/j722s-evm/wkup-r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/i2c/j722s-evm/mcu-r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/i2c/j722s-evm/wkup-r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/i2c/j722s-evm/main-r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/mmcsd/j722s-evm/mcu-r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/mmcsd/j722s-evm/wkup-r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/mmcsd/j722s-evm/main-r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/mmcsd/j722s-evm/main-r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/sciclient/sciclient_get_version/j722s-evm/mcu-r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/sciclient/sciclient_get_version/j722s-evm/main-r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/sciclient/sciclient_get_version/j722s-evm/wkup-r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/ospi/j722s-evm/mcu-r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/ospi/j722s-evm/wkup-r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/ospi/j722s-evm/main-r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/uart/j722s-evm/mcu-r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/uart/j722s-evm/wkup-r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/uart/j722s-evm/main-r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/uart/j722s-evm/mcu-r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/uart/j722s-evm/wkup-r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/uart/j722s-evm/main-r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/uart/j722s-evm/c75ss0-0_freertos/ti-c7000 [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/uart/j722s-evm/c75ss1-0_freertos/ti-c7000 [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C kernel/dpl/j722s-evm/mcu-r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C kernel/dpl/j722s-evm/wkup-r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C kernel/dpl/j722s-evm/main-r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C kernel/dpl/j722s-evm/mcu-r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C kernel/dpl/j722s-evm/wkup-r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C kernel/dpl/j722s-evm/main-r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C kernel/dpl/j722s-evm/c75ss0-0_freertos/ti-c7000 [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C kernel/dpl/j722s-evm/c75ss1-0_freertos/ti-c7000 [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C kernel/dpl_exception_test/j722s-evm/main-r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C kernel/dpl_core_r5_test/j722s-evm/mcu-r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C kernel/dpl_core_r5_test/j722s-evm/wkup-r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C kernel/dpl_core_r5_test/j722s-evm/main-r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C kernel/freertos/j722s-evm/mcu-r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C kernel/freertos/j722s-evm/wkup-r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C kernel/freertos/j722s-evm/main-r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C kernel/freertos/j722s-evm/c75ss0-0_freertos/ti-c7000 [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C kernel/freertos/j722s-evm/c75ss1-0_freertos/ti-c7000 [all clean syscfg-gui syscfg]
	@echo  .
	@echo  System Example build targets,
	@echo  =============================
	@echo  $(MAKE) -s -C drivers/ipc_notify/j722s-evm/system_freertos [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/ipc_rpmsg/j722s-evm/system_freertos [all clean syscfg-gui syscfg]
	@echo  .

# Various Component Targets
BUILD_COMBO_doxy_samples = doxy_samples_r5f.ti-arm-clang
BUILD_COMBO_unity = unity_r5f.ti-arm-clang unity_a53.gcc-aarch64 unity_c75x.ti-c7000

# Combine all Components
BUILD_COMBO_ALL = $(BUILD_COMBO_doxy_samples) $(BUILD_COMBO_unity)

# Combine all External Components
BUILD_COMBO_EXTERNAL_ALL =

# Combine all Pre-built Components
BUILD_COMBO_PREBUILT_ALL =

# Combine all Private Components
BUILD_COMBO_PRIVATE_ALL =

libs: $(BUILD_COMBO_ALL)

libs-external: $(BUILD_COMBO_EXTERNAL_ALL)

libs-prebuilt: $(BUILD_COMBO_PREBUILT_ALL)

libs-private: $(BUILD_COMBO_PRIVATE_ALL)

$(BUILD_COMBO_doxy_samples):
	$(MAKE) -C ../docs_src/docs/api_guide/doxy_samples -f makefile.j722s.$(subst doxy_samples_,,$@) all

$(BUILD_COMBO_unity):
	$(MAKE) -C unity -f makefile.j722s.$(subst unity_,,$@) all


# Various Component Clean Targets
BUILD_COMBO_CLEAN_doxy_samples = doxy_samples_r5f.ti-arm-clang_clean
BUILD_COMBO_CLEAN_unity = unity_r5f.ti-arm-clang_clean unity_a53.gcc-aarch64_clean unity_c75x.ti-c7000_clean

# Combine all Components Clean
BUILD_COMBO_CLEAN_ALL = $(BUILD_COMBO_CLEAN_doxy_samples) $(BUILD_COMBO_CLEAN_unity)

# Combine all External Components Clean
BUILD_COMBO_EXTERNAL_CLEAN_ALL =

# Combine all Pre-built Components Clean
BUILD_COMBO_PREBUILT_CLEAN_ALL =

libs-clean: $(BUILD_COMBO_CLEAN_ALL)

libs-external-clean: $(BUILD_COMBO_EXTERNAL_CLEAN_ALL)

libs-prebuilt-clean: $(BUILD_COMBO_PREBUILT_CLEAN_ALL)

$(BUILD_COMBO_CLEAN_doxy_samples):
	$(MAKE) -C ../docs_src/docs/api_guide/doxy_samples -f makefile.j722s.$(subst doxy_samples_,,$(subst _clean,,$@)) clean

$(BUILD_COMBO_CLEAN_unity):
	$(MAKE) -C unity -f makefile.j722s.$(subst unity_,,$(subst _clean,,$@)) clean


# Various Component Scrub Targets
BUILD_COMBO_SCRUB_doxy_samples = doxy_samples_r5f.ti-arm-clang_scrub_scrub
BUILD_COMBO_SCRUB_unity = unity_r5f.ti-arm-clang_scrub unity_a53.gcc-aarch64_scrub unity_c75x.ti-c7000_scrub_scrub

# Combine all Components Scrub Targets
BUILD_COMBO_SCRUB_ALL = $(BUILD_COMBO_SCRUB_doxy_samples) $(BUILD_COMBO_SCRUB_unity)

# Combine all External Components Scrub Targets
BUILD_COMBO_EXTERNAL_SCRUB_ALL =

# Combine all Pre-built Components Scrub Targets
BUILD_COMBO_PREBUILT_SCRUB_ALL =

libs-scrub: $(BUILD_COMBO_SCRUB_ALL)

libs-external-scrub: $(BUILD_COMBO_EXTERNAL_SCRUB_ALL)

libs-prebuilt-scrub: $(BUILD_COMBO_PREBUILT_SCRUB_ALL)

$(BUILD_COMBO_SCRUB_doxy_samples):
	$(MAKE) -C ../docs_src/docs/api_guide/doxy_samples -f makefile.j722s.$(subst doxy_samples_,,$(subst _scrub,,$@)) scrub

$(BUILD_COMBO_SCRUB_unity):
	$(MAKE) -C unity -f makefile.j722s.$(subst unity_,,$(subst _scrub,,$@)) scrub


BUILD_COMBO_EXAMPLE_ALL =
# Various Example Targets
BUILD_COMBO_EXAMPLE_ALL += test_flash_j722s-evm_wkup-r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_gpio_j722s-evm_mcu-r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_gpio_j722s-evm_main-r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_gpio_j722s-evm_wkup-r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_i2c_j722s-evm_mcu-r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_i2c_j722s-evm_wkup-r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_i2c_j722s-evm_main-r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_mmcsd_j722s-evm_mcu-r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_mmcsd_j722s-evm_wkup-r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_mmcsd_j722s-evm_main-r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_mmcsd_j722s-evm_main-r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_sciclient_j722s-evm_mcu-r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_sciclient_j722s-evm_main-r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_sciclient_j722s-evm_wkup-r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_ospi_j722s-evm_mcu-r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_ospi_j722s-evm_wkup-r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_ospi_j722s-evm_main-r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_uart_j722s-evm_mcu-r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_uart_j722s-evm_wkup-r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_uart_j722s-evm_main-r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_uart_j722s-evm_mcu-r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_uart_j722s-evm_wkup-r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_uart_j722s-evm_main-r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_uart_j722s-evm_c75ss0-0_freertos_ti-c7000
BUILD_COMBO_EXAMPLE_ALL += test_uart_j722s-evm_c75ss1-0_freertos_ti-c7000
BUILD_COMBO_EXAMPLE_ALL += test_dpl_j722s-evm_mcu-r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_dpl_j722s-evm_wkup-r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_dpl_j722s-evm_main-r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_dpl_j722s-evm_mcu-r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_dpl_j722s-evm_wkup-r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_dpl_j722s-evm_main-r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_dpl_j722s-evm_c75ss0-0_freertos_ti-c7000
BUILD_COMBO_EXAMPLE_ALL += test_dpl_j722s-evm_c75ss1-0_freertos_ti-c7000
BUILD_COMBO_EXAMPLE_ALL += test_dpl_exception_j722s-evm_main-r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += core_r5_test_j722s-evm_mcu-r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += core_r5_test_j722s-evm_wkup-r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += core_r5_test_j722s-evm_main-r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_freertos_j722s-evm_mcu-r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_freertos_j722s-evm_wkup-r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_freertos_j722s-evm_main-r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_freertos_j722s-evm_c75ss0-0_freertos_ti-c7000
BUILD_COMBO_EXAMPLE_ALL += test_freertos_j722s-evm_c75ss1-0_freertos_ti-c7000
# Various System Example Targets
BUILD_COMBO_EXAMPLE_ALL += test_ipc_notify_j722s-evm_system_freertos
BUILD_COMBO_EXAMPLE_ALL += test_ipc_rpmsg_j722s-evm_system_freertos

BUILD_COMBO_EXAMPLE_PRIVATE_ALL =
# Various Private Example Targets
# Various Private System Example Targets

examples: $(BUILD_COMBO_EXAMPLE_ALL)

examples-private: $(BUILD_COMBO_EXAMPLE_PRIVATE_ALL)

 test_flash_j722s-evm_wkup-r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C board/flash/j722s-evm/wkup-r5fss0-0_freertos/ti-arm-clang -f makefile all

 test_gpio_j722s-evm_mcu-r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C drivers/gpio/j722s-evm/mcu-r5fss0-0_freertos/ti-arm-clang -f makefile all

 test_gpio_j722s-evm_main-r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C drivers/gpio/j722s-evm/main-r5fss0-0_freertos/ti-arm-clang -f makefile all

 test_gpio_j722s-evm_wkup-r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C drivers/gpio/j722s-evm/wkup-r5fss0-0_freertos/ti-arm-clang -f makefile all

 test_i2c_j722s-evm_mcu-r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C drivers/i2c/j722s-evm/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile all

 test_i2c_j722s-evm_wkup-r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C drivers/i2c/j722s-evm/wkup-r5fss0-0_freertos/ti-arm-clang -f makefile all

 test_i2c_j722s-evm_main-r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C drivers/i2c/j722s-evm/main-r5fss0-0_freertos/ti-arm-clang -f makefile all

 test_mmcsd_j722s-evm_mcu-r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C drivers/mmcsd/j722s-evm/mcu-r5fss0-0_freertos/ti-arm-clang -f makefile all

 test_mmcsd_j722s-evm_wkup-r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C drivers/mmcsd/j722s-evm/wkup-r5fss0-0_freertos/ti-arm-clang -f makefile all

 test_mmcsd_j722s-evm_main-r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C drivers/mmcsd/j722s-evm/main-r5fss0-0_nortos/ti-arm-clang -f makefile all

 test_mmcsd_j722s-evm_main-r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C drivers/mmcsd/j722s-evm/main-r5fss0-0_freertos/ti-arm-clang -f makefile all

 test_sciclient_j722s-evm_mcu-r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C drivers/sciclient/sciclient_get_version/j722s-evm/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile all

 test_sciclient_j722s-evm_main-r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C drivers/sciclient/sciclient_get_version/j722s-evm/main-r5fss0-0_nortos/ti-arm-clang -f makefile all

 test_sciclient_j722s-evm_wkup-r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C drivers/sciclient/sciclient_get_version/j722s-evm/wkup-r5fss0-0_freertos/ti-arm-clang -f makefile all

 test_ospi_j722s-evm_mcu-r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C drivers/ospi/j722s-evm/mcu-r5fss0-0_freertos/ti-arm-clang -f makefile all

 test_ospi_j722s-evm_wkup-r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C drivers/ospi/j722s-evm/wkup-r5fss0-0_freertos/ti-arm-clang -f makefile all

 test_ospi_j722s-evm_main-r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C drivers/ospi/j722s-evm/main-r5fss0-0_freertos/ti-arm-clang -f makefile all

 test_uart_j722s-evm_mcu-r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C drivers/uart/j722s-evm/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile all

 test_uart_j722s-evm_wkup-r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C drivers/uart/j722s-evm/wkup-r5fss0-0_nortos/ti-arm-clang -f makefile all

 test_uart_j722s-evm_main-r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C drivers/uart/j722s-evm/main-r5fss0-0_nortos/ti-arm-clang -f makefile all

 test_uart_j722s-evm_mcu-r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C drivers/uart/j722s-evm/mcu-r5fss0-0_freertos/ti-arm-clang -f makefile all

 test_uart_j722s-evm_wkup-r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C drivers/uart/j722s-evm/wkup-r5fss0-0_freertos/ti-arm-clang -f makefile all

 test_uart_j722s-evm_main-r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C drivers/uart/j722s-evm/main-r5fss0-0_freertos/ti-arm-clang -f makefile all

 test_uart_j722s-evm_c75ss0-0_freertos_ti-c7000:
	$(MAKE) -C drivers/uart/j722s-evm/c75ss0-0_freertos/ti-c7000 -f makefile all

 test_uart_j722s-evm_c75ss1-0_freertos_ti-c7000:
	$(MAKE) -C drivers/uart/j722s-evm/c75ss1-0_freertos/ti-c7000 -f makefile all

 test_dpl_j722s-evm_mcu-r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C kernel/dpl/j722s-evm/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile all

 test_dpl_j722s-evm_wkup-r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C kernel/dpl/j722s-evm/wkup-r5fss0-0_nortos/ti-arm-clang -f makefile all

 test_dpl_j722s-evm_main-r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C kernel/dpl/j722s-evm/main-r5fss0-0_nortos/ti-arm-clang -f makefile all

 test_dpl_j722s-evm_mcu-r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C kernel/dpl/j722s-evm/mcu-r5fss0-0_freertos/ti-arm-clang -f makefile all

 test_dpl_j722s-evm_wkup-r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C kernel/dpl/j722s-evm/wkup-r5fss0-0_freertos/ti-arm-clang -f makefile all

 test_dpl_j722s-evm_main-r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C kernel/dpl/j722s-evm/main-r5fss0-0_freertos/ti-arm-clang -f makefile all

 test_dpl_j722s-evm_c75ss0-0_freertos_ti-c7000:
	$(MAKE) -C kernel/dpl/j722s-evm/c75ss0-0_freertos/ti-c7000 -f makefile all

 test_dpl_j722s-evm_c75ss1-0_freertos_ti-c7000:
	$(MAKE) -C kernel/dpl/j722s-evm/c75ss1-0_freertos/ti-c7000 -f makefile all

 test_dpl_exception_j722s-evm_main-r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C kernel/dpl_exception_test/j722s-evm/main-r5fss0-0_freertos/ti-arm-clang -f makefile all

 core_r5_test_j722s-evm_mcu-r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C kernel/dpl_core_r5_test/j722s-evm/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile all

 core_r5_test_j722s-evm_wkup-r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C kernel/dpl_core_r5_test/j722s-evm/wkup-r5fss0-0_nortos/ti-arm-clang -f makefile all

 core_r5_test_j722s-evm_main-r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C kernel/dpl_core_r5_test/j722s-evm/main-r5fss0-0_nortos/ti-arm-clang -f makefile all

 test_freertos_j722s-evm_mcu-r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C kernel/freertos/j722s-evm/mcu-r5fss0-0_freertos/ti-arm-clang -f makefile all

 test_freertos_j722s-evm_wkup-r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C kernel/freertos/j722s-evm/wkup-r5fss0-0_freertos/ti-arm-clang -f makefile all

 test_freertos_j722s-evm_main-r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C kernel/freertos/j722s-evm/main-r5fss0-0_freertos/ti-arm-clang -f makefile all

 test_freertos_j722s-evm_c75ss0-0_freertos_ti-c7000:
	$(MAKE) -C kernel/freertos/j722s-evm/c75ss0-0_freertos/ti-c7000 -f makefile all

 test_freertos_j722s-evm_c75ss1-0_freertos_ti-c7000:
	$(MAKE) -C kernel/freertos/j722s-evm/c75ss1-0_freertos/ti-c7000 -f makefile all

 test_ipc_notify_j722s-evm_system_freertos:
	$(MAKE) -C drivers/ipc_notify/j722s-evm/system_freertos -f makefile all

 test_ipc_rpmsg_j722s-evm_system_freertos:
	$(MAKE) -C drivers/ipc_rpmsg/j722s-evm/system_freertos -f makefile all


BUILD_COMBO_EXAMPLE_CLEAN_ALL =
# Various Example Clean Targets
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_flash_j722s-evm_wkup-r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_gpio_j722s-evm_mcu-r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_gpio_j722s-evm_main-r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_gpio_j722s-evm_wkup-r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_i2c_j722s-evm_mcu-r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_i2c_j722s-evm_wkup-r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_i2c_j722s-evm_main-r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_mmcsd_j722s-evm_mcu-r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_mmcsd_j722s-evm_wkup-r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_mmcsd_j722s-evm_main-r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_mmcsd_j722s-evm_main-r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_sciclient_j722s-evm_mcu-r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_sciclient_j722s-evm_main-r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_sciclient_j722s-evm_wkup-r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_ospi_j722s-evm_mcu-r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_ospi_j722s-evm_wkup-r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_ospi_j722s-evm_main-r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_uart_j722s-evm_mcu-r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_uart_j722s-evm_wkup-r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_uart_j722s-evm_main-r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_uart_j722s-evm_mcu-r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_uart_j722s-evm_wkup-r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_uart_j722s-evm_main-r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_uart_j722s-evm_c75ss0-0_freertos_ti-c7000_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_uart_j722s-evm_c75ss1-0_freertos_ti-c7000_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_dpl_j722s-evm_mcu-r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_dpl_j722s-evm_wkup-r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_dpl_j722s-evm_main-r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_dpl_j722s-evm_mcu-r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_dpl_j722s-evm_wkup-r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_dpl_j722s-evm_main-r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_dpl_j722s-evm_c75ss0-0_freertos_ti-c7000_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_dpl_j722s-evm_c75ss1-0_freertos_ti-c7000_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_dpl_exception_j722s-evm_main-r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += core_r5_test_j722s-evm_mcu-r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += core_r5_test_j722s-evm_wkup-r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += core_r5_test_j722s-evm_main-r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_freertos_j722s-evm_mcu-r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_freertos_j722s-evm_wkup-r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_freertos_j722s-evm_main-r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_freertos_j722s-evm_c75ss0-0_freertos_ti-c7000_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_freertos_j722s-evm_c75ss1-0_freertos_ti-c7000_clean
# Various System Example Clean Targets
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_ipc_notify_j722s-evm_system_freertos_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_ipc_rpmsg_j722s-evm_system_freertos_clean

BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL =
# Various Private Example Targets
# Various Private System Example Targets

examples-clean: $(BUILD_COMBO_EXAMPLE_CLEAN_ALL)

examples-private-clean: $(BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL)

 test_flash_j722s-evm_wkup-r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C board/flash/j722s-evm/wkup-r5fss0-0_freertos/ti-arm-clang -f makefile clean

 test_gpio_j722s-evm_mcu-r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C drivers/gpio/j722s-evm/mcu-r5fss0-0_freertos/ti-arm-clang -f makefile clean

 test_gpio_j722s-evm_main-r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C drivers/gpio/j722s-evm/main-r5fss0-0_freertos/ti-arm-clang -f makefile clean

 test_gpio_j722s-evm_wkup-r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C drivers/gpio/j722s-evm/wkup-r5fss0-0_freertos/ti-arm-clang -f makefile clean

 test_i2c_j722s-evm_mcu-r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C drivers/i2c/j722s-evm/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile clean

 test_i2c_j722s-evm_wkup-r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C drivers/i2c/j722s-evm/wkup-r5fss0-0_freertos/ti-arm-clang -f makefile clean

 test_i2c_j722s-evm_main-r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C drivers/i2c/j722s-evm/main-r5fss0-0_freertos/ti-arm-clang -f makefile clean

 test_mmcsd_j722s-evm_mcu-r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C drivers/mmcsd/j722s-evm/mcu-r5fss0-0_freertos/ti-arm-clang -f makefile clean

 test_mmcsd_j722s-evm_wkup-r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C drivers/mmcsd/j722s-evm/wkup-r5fss0-0_freertos/ti-arm-clang -f makefile clean

 test_mmcsd_j722s-evm_main-r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C drivers/mmcsd/j722s-evm/main-r5fss0-0_nortos/ti-arm-clang -f makefile clean

 test_mmcsd_j722s-evm_main-r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C drivers/mmcsd/j722s-evm/main-r5fss0-0_freertos/ti-arm-clang -f makefile clean

 test_sciclient_j722s-evm_mcu-r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C drivers/sciclient/sciclient_get_version/j722s-evm/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile clean

 test_sciclient_j722s-evm_main-r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C drivers/sciclient/sciclient_get_version/j722s-evm/main-r5fss0-0_nortos/ti-arm-clang -f makefile clean

 test_sciclient_j722s-evm_wkup-r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C drivers/sciclient/sciclient_get_version/j722s-evm/wkup-r5fss0-0_freertos/ti-arm-clang -f makefile clean

 test_ospi_j722s-evm_mcu-r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C drivers/ospi/j722s-evm/mcu-r5fss0-0_freertos/ti-arm-clang -f makefile clean

 test_ospi_j722s-evm_wkup-r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C drivers/ospi/j722s-evm/wkup-r5fss0-0_freertos/ti-arm-clang -f makefile clean

 test_ospi_j722s-evm_main-r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C drivers/ospi/j722s-evm/main-r5fss0-0_freertos/ti-arm-clang -f makefile clean

 test_uart_j722s-evm_mcu-r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C drivers/uart/j722s-evm/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile clean

 test_uart_j722s-evm_wkup-r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C drivers/uart/j722s-evm/wkup-r5fss0-0_nortos/ti-arm-clang -f makefile clean

 test_uart_j722s-evm_main-r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C drivers/uart/j722s-evm/main-r5fss0-0_nortos/ti-arm-clang -f makefile clean

 test_uart_j722s-evm_mcu-r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C drivers/uart/j722s-evm/mcu-r5fss0-0_freertos/ti-arm-clang -f makefile clean

 test_uart_j722s-evm_wkup-r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C drivers/uart/j722s-evm/wkup-r5fss0-0_freertos/ti-arm-clang -f makefile clean

 test_uart_j722s-evm_main-r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C drivers/uart/j722s-evm/main-r5fss0-0_freertos/ti-arm-clang -f makefile clean

 test_uart_j722s-evm_c75ss0-0_freertos_ti-c7000_clean:
	$(MAKE) -C drivers/uart/j722s-evm/c75ss0-0_freertos/ti-c7000 -f makefile clean

 test_uart_j722s-evm_c75ss1-0_freertos_ti-c7000_clean:
	$(MAKE) -C drivers/uart/j722s-evm/c75ss1-0_freertos/ti-c7000 -f makefile clean

 test_dpl_j722s-evm_mcu-r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C kernel/dpl/j722s-evm/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile clean

 test_dpl_j722s-evm_wkup-r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C kernel/dpl/j722s-evm/wkup-r5fss0-0_nortos/ti-arm-clang -f makefile clean

 test_dpl_j722s-evm_main-r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C kernel/dpl/j722s-evm/main-r5fss0-0_nortos/ti-arm-clang -f makefile clean

 test_dpl_j722s-evm_mcu-r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C kernel/dpl/j722s-evm/mcu-r5fss0-0_freertos/ti-arm-clang -f makefile clean

 test_dpl_j722s-evm_wkup-r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C kernel/dpl/j722s-evm/wkup-r5fss0-0_freertos/ti-arm-clang -f makefile clean

 test_dpl_j722s-evm_main-r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C kernel/dpl/j722s-evm/main-r5fss0-0_freertos/ti-arm-clang -f makefile clean

 test_dpl_j722s-evm_c75ss0-0_freertos_ti-c7000_clean:
	$(MAKE) -C kernel/dpl/j722s-evm/c75ss0-0_freertos/ti-c7000 -f makefile clean

 test_dpl_j722s-evm_c75ss1-0_freertos_ti-c7000_clean:
	$(MAKE) -C kernel/dpl/j722s-evm/c75ss1-0_freertos/ti-c7000 -f makefile clean

 test_dpl_exception_j722s-evm_main-r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C kernel/dpl_exception_test/j722s-evm/main-r5fss0-0_freertos/ti-arm-clang -f makefile clean

 core_r5_test_j722s-evm_mcu-r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C kernel/dpl_core_r5_test/j722s-evm/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile clean

 core_r5_test_j722s-evm_wkup-r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C kernel/dpl_core_r5_test/j722s-evm/wkup-r5fss0-0_nortos/ti-arm-clang -f makefile clean

 core_r5_test_j722s-evm_main-r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C kernel/dpl_core_r5_test/j722s-evm/main-r5fss0-0_nortos/ti-arm-clang -f makefile clean

 test_freertos_j722s-evm_mcu-r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C kernel/freertos/j722s-evm/mcu-r5fss0-0_freertos/ti-arm-clang -f makefile clean

 test_freertos_j722s-evm_wkup-r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C kernel/freertos/j722s-evm/wkup-r5fss0-0_freertos/ti-arm-clang -f makefile clean

 test_freertos_j722s-evm_main-r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C kernel/freertos/j722s-evm/main-r5fss0-0_freertos/ti-arm-clang -f makefile clean

 test_freertos_j722s-evm_c75ss0-0_freertos_ti-c7000_clean:
	$(MAKE) -C kernel/freertos/j722s-evm/c75ss0-0_freertos/ti-c7000 -f makefile clean

 test_freertos_j722s-evm_c75ss1-0_freertos_ti-c7000_clean:
	$(MAKE) -C kernel/freertos/j722s-evm/c75ss1-0_freertos/ti-c7000 -f makefile clean

 test_ipc_notify_j722s-evm_system_freertos_clean:
	$(MAKE) -C drivers/ipc_notify/j722s-evm/system_freertos -f makefile clean

 test_ipc_rpmsg_j722s-evm_system_freertos_clean:
	$(MAKE) -C drivers/ipc_rpmsg/j722s-evm/system_freertos -f makefile clean


BUILD_COMBO_EXAMPLE_SCRUB_ALL =
# Various Example Scrub Targets
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_flash_j722s-evm_wkup-r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_gpio_j722s-evm_mcu-r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_gpio_j722s-evm_main-r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_gpio_j722s-evm_wkup-r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_i2c_j722s-evm_mcu-r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_i2c_j722s-evm_wkup-r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_i2c_j722s-evm_main-r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_mmcsd_j722s-evm_mcu-r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_mmcsd_j722s-evm_wkup-r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_mmcsd_j722s-evm_main-r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_mmcsd_j722s-evm_main-r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_sciclient_j722s-evm_mcu-r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_sciclient_j722s-evm_main-r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_sciclient_j722s-evm_wkup-r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_ospi_j722s-evm_mcu-r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_ospi_j722s-evm_wkup-r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_ospi_j722s-evm_main-r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_uart_j722s-evm_mcu-r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_uart_j722s-evm_wkup-r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_uart_j722s-evm_main-r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_uart_j722s-evm_mcu-r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_uart_j722s-evm_wkup-r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_uart_j722s-evm_main-r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_uart_j722s-evm_c75ss0-0_freertos_ti-c7000_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_uart_j722s-evm_c75ss1-0_freertos_ti-c7000_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_dpl_j722s-evm_mcu-r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_dpl_j722s-evm_wkup-r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_dpl_j722s-evm_main-r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_dpl_j722s-evm_mcu-r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_dpl_j722s-evm_wkup-r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_dpl_j722s-evm_main-r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_dpl_j722s-evm_c75ss0-0_freertos_ti-c7000_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_dpl_j722s-evm_c75ss1-0_freertos_ti-c7000_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_dpl_exception_j722s-evm_main-r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += core_r5_test_j722s-evm_mcu-r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += core_r5_test_j722s-evm_wkup-r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += core_r5_test_j722s-evm_main-r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_freertos_j722s-evm_mcu-r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_freertos_j722s-evm_wkup-r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_freertos_j722s-evm_main-r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_freertos_j722s-evm_c75ss0-0_freertos_ti-c7000_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_freertos_j722s-evm_c75ss1-0_freertos_ti-c7000_scrub
# Various System Example Scrub Targets
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_ipc_notify_j722s-evm_system_freertos_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_ipc_rpmsg_j722s-evm_system_freertos_scrub

BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL =
# Various Private Example Targets
# Various Private System Example Targets

examples-scrub: $(BUILD_COMBO_EXAMPLE_SCRUB_ALL)

examples-scrub-private: $(BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL)

 test_flash_j722s-evm_wkup-r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C board/flash/j722s-evm/wkup-r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 test_gpio_j722s-evm_mcu-r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C drivers/gpio/j722s-evm/mcu-r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 test_gpio_j722s-evm_main-r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C drivers/gpio/j722s-evm/main-r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 test_gpio_j722s-evm_wkup-r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C drivers/gpio/j722s-evm/wkup-r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 test_i2c_j722s-evm_mcu-r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C drivers/i2c/j722s-evm/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 test_i2c_j722s-evm_wkup-r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C drivers/i2c/j722s-evm/wkup-r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 test_i2c_j722s-evm_main-r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C drivers/i2c/j722s-evm/main-r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 test_mmcsd_j722s-evm_mcu-r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C drivers/mmcsd/j722s-evm/mcu-r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 test_mmcsd_j722s-evm_wkup-r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C drivers/mmcsd/j722s-evm/wkup-r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 test_mmcsd_j722s-evm_main-r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C drivers/mmcsd/j722s-evm/main-r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 test_mmcsd_j722s-evm_main-r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C drivers/mmcsd/j722s-evm/main-r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 test_sciclient_j722s-evm_mcu-r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C drivers/sciclient/sciclient_get_version/j722s-evm/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 test_sciclient_j722s-evm_main-r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C drivers/sciclient/sciclient_get_version/j722s-evm/main-r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 test_sciclient_j722s-evm_wkup-r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C drivers/sciclient/sciclient_get_version/j722s-evm/wkup-r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 test_ospi_j722s-evm_mcu-r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C drivers/ospi/j722s-evm/mcu-r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 test_ospi_j722s-evm_wkup-r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C drivers/ospi/j722s-evm/wkup-r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 test_ospi_j722s-evm_main-r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C drivers/ospi/j722s-evm/main-r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 test_uart_j722s-evm_mcu-r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C drivers/uart/j722s-evm/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 test_uart_j722s-evm_wkup-r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C drivers/uart/j722s-evm/wkup-r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 test_uart_j722s-evm_main-r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C drivers/uart/j722s-evm/main-r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 test_uart_j722s-evm_mcu-r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C drivers/uart/j722s-evm/mcu-r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 test_uart_j722s-evm_wkup-r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C drivers/uart/j722s-evm/wkup-r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 test_uart_j722s-evm_main-r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C drivers/uart/j722s-evm/main-r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 test_uart_j722s-evm_c75ss0-0_freertos_ti-c7000_scrub:
	$(MAKE) -C drivers/uart/j722s-evm/c75ss0-0_freertos/ti-c7000 -f makefile scrub

 test_uart_j722s-evm_c75ss1-0_freertos_ti-c7000_scrub:
	$(MAKE) -C drivers/uart/j722s-evm/c75ss1-0_freertos/ti-c7000 -f makefile scrub

 test_dpl_j722s-evm_mcu-r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C kernel/dpl/j722s-evm/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 test_dpl_j722s-evm_wkup-r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C kernel/dpl/j722s-evm/wkup-r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 test_dpl_j722s-evm_main-r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C kernel/dpl/j722s-evm/main-r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 test_dpl_j722s-evm_mcu-r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C kernel/dpl/j722s-evm/mcu-r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 test_dpl_j722s-evm_wkup-r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C kernel/dpl/j722s-evm/wkup-r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 test_dpl_j722s-evm_main-r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C kernel/dpl/j722s-evm/main-r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 test_dpl_j722s-evm_c75ss0-0_freertos_ti-c7000_scrub:
	$(MAKE) -C kernel/dpl/j722s-evm/c75ss0-0_freertos/ti-c7000 -f makefile scrub

 test_dpl_j722s-evm_c75ss1-0_freertos_ti-c7000_scrub:
	$(MAKE) -C kernel/dpl/j722s-evm/c75ss1-0_freertos/ti-c7000 -f makefile scrub

 test_dpl_exception_j722s-evm_main-r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C kernel/dpl_exception_test/j722s-evm/main-r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 core_r5_test_j722s-evm_mcu-r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C kernel/dpl_core_r5_test/j722s-evm/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 core_r5_test_j722s-evm_wkup-r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C kernel/dpl_core_r5_test/j722s-evm/wkup-r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 core_r5_test_j722s-evm_main-r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C kernel/dpl_core_r5_test/j722s-evm/main-r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 test_freertos_j722s-evm_mcu-r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C kernel/freertos/j722s-evm/mcu-r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 test_freertos_j722s-evm_wkup-r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C kernel/freertos/j722s-evm/wkup-r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 test_freertos_j722s-evm_main-r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C kernel/freertos/j722s-evm/main-r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 test_freertos_j722s-evm_c75ss0-0_freertos_ti-c7000_scrub:
	$(MAKE) -C kernel/freertos/j722s-evm/c75ss0-0_freertos/ti-c7000 -f makefile scrub

 test_freertos_j722s-evm_c75ss1-0_freertos_ti-c7000_scrub:
	$(MAKE) -C kernel/freertos/j722s-evm/c75ss1-0_freertos/ti-c7000 -f makefile scrub

 test_ipc_notify_j722s-evm_system_freertos_scrub:
	$(MAKE) -C drivers/ipc_notify/j722s-evm/system_freertos -f makefile scrub

 test_ipc_rpmsg_j722s-evm_system_freertos_scrub:
	$(MAKE) -C drivers/ipc_rpmsg/j722s-evm/system_freertos -f makefile scrub


sbl: libs

sbl-clean:

sbl-scrub:


host-emu:
	$(MAKE) -C source/drivers/dmautils -f makefile.j722s.c75ssx-0.ti-c7x-hostemu all

host-emu-clean:
	$(MAKE) -C source/drivers/dmautils -f makefile.j722s.c75ssx-0.ti-c7x-hostemu clean

host-emu-scrub:
	$(MAKE) -C source/drivers/dmautils -f makefile.j722s.c75ssx-0.ti-c7x-hostemu scrub

.PHONY: all clean scrub help
.PHONY: libs libs-clean libs-scrub
.PHONY: libs-external libs-external-clean libs-external-scrub
.PHONY: libs-private
.PHONY: libs-prebuilt libs-prebuilt-clean libs-prebuilt-scrub
.PHONY: examples examples-clean examples-scrub
.PHONY: examples-private examples-private-clean examples-private-scrub
.PHONY: sbl sbl-clean sbl-scrub
.PHONY: $(BUILD_COMBO_ALL) $(BUILD_COMBO_CLEAN_ALL) $(BUILD_COMBO_SCRUB_ALL)
.PHONY: $(BUILD_COMBO_EXAMPLE_ALL) $(BUILD_COMBO_EXAMPLE_CLEAN_ALL) $(BUILD_COMBO_EXAMPLE_SCRUB_ALL)
.PHONY: $(BUILD_COMBO_EXAMPLE_PRIVATE_ALL) $(BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL) $(BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL)
