#
# Auto generated makefile
#

all:
	$(MAKE) -f makefile.am62lx libs
	$(MAKE) -f makefile.am62lx libs-external
	$(MAKE) -f makefile.am62lx sbl
	$(MAKE) -f makefile.am62lx examples

clean: libs-clean libs-external-clean sbl-clean examples-clean
scrub: libs-scrub libs-external-scrub sbl-scrub examples-scrub

help:
	@echo  Notes,
	@echo  - Use -j to invoke parallel builds
	@echo  - Use PROFILE=debug or PROFILE=release [default] to build in debug or release profile
	@echo  .
	@echo  Overall build targets,
	@echo  ======================
	@echo  $(MAKE) -s -f makefile.am62lx help
	@echo  .
	@echo  $(MAKE) -s -f makefile.am62lx all
	@echo  $(MAKE) -s -f makefile.am62lx clean  # delete's tmp files for current profile
	@echo  $(MAKE) -s -f makefile.am62lx scrub  # delete's all tmp files and folders for all profiles
	@echo  .
	@echo  $(MAKE) -s -f makefile.am62lx libs
	@echo  $(MAKE) -s -f makefile.am62lx libs-clean # delete's tmp files for current profile
	@echo  $(MAKE) -s -f makefile.am62lx libs-scrub # delete's all tmp files and folders for all profiles
	@echo  .
	@echo  $(MAKE) -s -f makefile.am62lx examples
	@echo  $(MAKE) -s -f makefile.am62lx examples-clean # delete's tmp files for current profile
	@echo  $(MAKE) -s -f makefile.am62lx examples-scrub # delete's all tmp files and folders for all profiles
	@echo  .
	@echo  Library build targets,
	@echo  ======================
	@echo  $(MAKE) -s -f makefile.am62lx unity_a53.gcc-aarch64
	@echo  $(MAKE) -s -f makefile.am62lx doxy_samples_a53.gcc-aarch64
	@echo  .
	@echo  Library clean targets,
	@echo  ======================
	@echo  $(MAKE) -s -f makefile.am62lx unity_a53.gcc-aarch64_clean
	@echo  $(MAKE) -s -f makefile.am62lx doxy_samples_a53.gcc-aarch64_clean
	@echo  .
	@echo  Example build targets,
	@echo  ======================
	@echo  $(MAKE) -s -C drivers/adc/am62lx-evm/a53ss0-0_nortos/gcc-aarch64 [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/adc/am62lx-evm/a53ss0-0_freertos/gcc-aarch64 [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/ecap/am62lx-evm/a53ss0-0_nortos/gcc-aarch64 [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/ecap/am62lx-evm/a53ss0-0_freertos/gcc-aarch64 [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/epwm/am62lx-evm/a53ss0-0_nortos/gcc-aarch64 [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/epwm/am62lx-evm/a53ss0-0_freertos/gcc-aarch64 [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/eqep/am62lx-evm/a53ss0-0_nortos/gcc-aarch64 [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/eqep/am62lx-evm/a53ss0-0_freertos/gcc-aarch64 [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/gpio/am62lx-evm/a53ss0-0_nortos/gcc-aarch64 [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/gpio/am62lx-evm/a53ss0-0_freertos/gcc-aarch64 [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/gtc/am62lx-evm/a53ss0-0_nortos/gcc-aarch64 [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/gtc/am62lx-evm/a53ss0-0_freertos/gcc-aarch64 [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/i2c/am62lx-evm/a53ss0-0_nortos/gcc-aarch64 [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/i2c/am62lx-evm/a53ss0-0_freertos/gcc-aarch64 [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/mmcsd/am62lx-evm/a53ss0-0_freertos/gcc-aarch64 [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/mmcsd/am62lx-evm/a53ss0-0_nortos/gcc-aarch64 [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/ospi/am62lx-evm/a53ss0-0_nortos/gcc-aarch64 [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/ospi/am62lx-evm/a53ss0-0_freertos/gcc-aarch64 [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/scp/scmi/am62lx-evm/a53ss0-0_nortos/gcc-aarch64 [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/scp/scmi/am62lx-evm/a53ss0-0_freertos/gcc-aarch64 [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/uart/am62lx-evm/a53ss0-0_nortos/gcc-aarch64 [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/uart/am62lx-evm/a53ss0-0_freertos/gcc-aarch64 [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C kernel/dpl/am62lx-evm/a53ss0-0_nortos/gcc-aarch64 [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C kernel/dpl/am62lx-evm/a53ss0-0_freertos/gcc-aarch64 [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C kernel/dpl/am62lx-evm/a53ss0-1_nortos/gcc-aarch64 [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C kernel/dpl/am62lx-evm/a53ss0-1_freertos/gcc-aarch64 [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C kernel/freertos/am62lx-evm/a53ss0-0_freertos/gcc-aarch64 [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C kernel/freertos/am62lx-evm/a53ss0-1_freertos/gcc-aarch64 [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C kernel/rov/am62lx-evm/a53ss0-0_freertos/gcc-aarch64 [all clean syscfg-gui syscfg]
	@echo  .
	@echo  System Example build targets,
	@echo  =============================
	@echo  .

# Various Component Targets
BUILD_COMBO_unity = unity_a53.gcc-aarch64
BUILD_COMBO_doxy_samples = doxy_samples_a53.gcc-aarch64

# Combine all Components
BUILD_COMBO_ALL = $(BUILD_COMBO_unity) $(BUILD_COMBO_doxy_samples)

# Combine all External Components
BUILD_COMBO_EXTERNAL_ALL =

# Combine all Pre-built Components
BUILD_COMBO_PREBUILT_ALL =

# Combine all Private Components
BUILD_COMBO_PRIVATE_ALL =

libs: $(BUILD_COMBO_ALL)

libs-external: $(BUILD_COMBO_EXTERNAL_ALL)

libs-prebuilt: $(BUILD_COMBO_PREBUILT_ALL)

libs-private: $(BUILD_COMBO_PRIVATE_ALL)

$(BUILD_COMBO_unity):
	$(MAKE) -C unity -f makefile.am62lx.$(subst unity_,,$@) all

$(BUILD_COMBO_doxy_samples):
	$(MAKE) -C ../docs_src/docs/api_guide/doxy_samples -f makefile.am62lx.$(subst doxy_samples_,,$@) all


# Various Component Clean Targets
BUILD_COMBO_CLEAN_unity = unity_a53.gcc-aarch64_clean
BUILD_COMBO_CLEAN_doxy_samples = doxy_samples_a53.gcc-aarch64_clean

# Combine all Components Clean
BUILD_COMBO_CLEAN_ALL = $(BUILD_COMBO_CLEAN_unity) $(BUILD_COMBO_CLEAN_doxy_samples)

# Combine all External Components Clean
BUILD_COMBO_EXTERNAL_CLEAN_ALL =

# Combine all Pre-built Components Clean
BUILD_COMBO_PREBUILT_CLEAN_ALL =

libs-clean: $(BUILD_COMBO_CLEAN_ALL)

libs-external-clean: $(BUILD_COMBO_EXTERNAL_CLEAN_ALL)

libs-prebuilt-clean: $(BUILD_COMBO_PREBUILT_CLEAN_ALL)

$(BUILD_COMBO_CLEAN_unity):
	$(MAKE) -C unity -f makefile.am62lx.$(subst unity_,,$(subst _clean,,$@)) clean

$(BUILD_COMBO_CLEAN_doxy_samples):
	$(MAKE) -C ../docs_src/docs/api_guide/doxy_samples -f makefile.am62lx.$(subst doxy_samples_,,$(subst _clean,,$@)) clean


# Various Component Scrub Targets
BUILD_COMBO_SCRUB_unity = unity_a53.gcc-aarch64_scrub_scrub
BUILD_COMBO_SCRUB_doxy_samples = doxy_samples_a53.gcc-aarch64_scrub_scrub

# Combine all Components Scrub Targets
BUILD_COMBO_SCRUB_ALL = $(BUILD_COMBO_SCRUB_unity) $(BUILD_COMBO_SCRUB_doxy_samples)

# Combine all External Components Scrub Targets
BUILD_COMBO_EXTERNAL_SCRUB_ALL =

# Combine all Pre-built Components Scrub Targets
BUILD_COMBO_PREBUILT_SCRUB_ALL =

libs-scrub: $(BUILD_COMBO_SCRUB_ALL)

libs-external-scrub: $(BUILD_COMBO_EXTERNAL_SCRUB_ALL)

libs-prebuilt-scrub: $(BUILD_COMBO_PREBUILT_SCRUB_ALL)

$(BUILD_COMBO_SCRUB_unity):
	$(MAKE) -C unity -f makefile.am62lx.$(subst unity_,,$(subst _scrub,,$@)) scrub

$(BUILD_COMBO_SCRUB_doxy_samples):
	$(MAKE) -C ../docs_src/docs/api_guide/doxy_samples -f makefile.am62lx.$(subst doxy_samples_,,$(subst _scrub,,$@)) scrub


BUILD_COMBO_EXAMPLE_ALL =
# Various Example Targets
BUILD_COMBO_EXAMPLE_ALL += test_adc_am62lx-evm_a53ss0-0_nortos_gcc-aarch64
BUILD_COMBO_EXAMPLE_ALL += test_adc_am62lx-evm_a53ss0-0_freertos_gcc-aarch64
BUILD_COMBO_EXAMPLE_ALL += test_ecap_am62lx-evm_a53ss0-0_nortos_gcc-aarch64
BUILD_COMBO_EXAMPLE_ALL += test_ecap_am62lx-evm_a53ss0-0_freertos_gcc-aarch64
BUILD_COMBO_EXAMPLE_ALL += test_epwm_am62lx-evm_a53ss0-0_nortos_gcc-aarch64
BUILD_COMBO_EXAMPLE_ALL += test_epwm_am62lx-evm_a53ss0-0_freertos_gcc-aarch64
BUILD_COMBO_EXAMPLE_ALL += test_eqep_am62lx-evm_a53ss0-0_nortos_gcc-aarch64
BUILD_COMBO_EXAMPLE_ALL += test_eqep_am62lx-evm_a53ss0-0_freertos_gcc-aarch64
BUILD_COMBO_EXAMPLE_ALL += test_gpio_am62lx-evm_a53ss0-0_nortos_gcc-aarch64
BUILD_COMBO_EXAMPLE_ALL += test_gpio_am62lx-evm_a53ss0-0_freertos_gcc-aarch64
BUILD_COMBO_EXAMPLE_ALL += test_gtc_am62lx-evm_a53ss0-0_nortos_gcc-aarch64
BUILD_COMBO_EXAMPLE_ALL += test_gtc_am62lx-evm_a53ss0-0_freertos_gcc-aarch64
BUILD_COMBO_EXAMPLE_ALL += test_i2c_am62lx-evm_a53ss0-0_nortos_gcc-aarch64
BUILD_COMBO_EXAMPLE_ALL += test_i2c_am62lx-evm_a53ss0-0_freertos_gcc-aarch64
BUILD_COMBO_EXAMPLE_ALL += test_mmcsd_am62lx-evm_a53ss0-0_freertos_gcc-aarch64
BUILD_COMBO_EXAMPLE_ALL += test_mmcsd_am62lx-evm_a53ss0-0_nortos_gcc-aarch64
BUILD_COMBO_EXAMPLE_ALL += test_ospi_am62lx-evm_a53ss0-0_nortos_gcc-aarch64
BUILD_COMBO_EXAMPLE_ALL += test_ospi_am62lx-evm_a53ss0-0_freertos_gcc-aarch64
BUILD_COMBO_EXAMPLE_ALL += test_scmi_am62lx-evm_a53ss0-0_nortos_gcc-aarch64
BUILD_COMBO_EXAMPLE_ALL += test_scmi_am62lx-evm_a53ss0-0_freertos_gcc-aarch64
BUILD_COMBO_EXAMPLE_ALL += test_uart_am62lx-evm_a53ss0-0_nortos_gcc-aarch64
BUILD_COMBO_EXAMPLE_ALL += test_uart_am62lx-evm_a53ss0-0_freertos_gcc-aarch64
BUILD_COMBO_EXAMPLE_ALL += test_dpl_am62lx-evm_a53ss0-0_nortos_gcc-aarch64
BUILD_COMBO_EXAMPLE_ALL += test_dpl_am62lx-evm_a53ss0-0_freertos_gcc-aarch64
BUILD_COMBO_EXAMPLE_ALL += test_dpl_am62lx-evm_a53ss0-1_nortos_gcc-aarch64
BUILD_COMBO_EXAMPLE_ALL += test_dpl_am62lx-evm_a53ss0-1_freertos_gcc-aarch64
BUILD_COMBO_EXAMPLE_ALL += test_freertos_am62lx-evm_a53ss0-0_freertos_gcc-aarch64
BUILD_COMBO_EXAMPLE_ALL += test_freertos_am62lx-evm_a53ss0-1_freertos_gcc-aarch64
BUILD_COMBO_EXAMPLE_ALL += test_rov_am62lx-evm_a53ss0-0_freertos_gcc-aarch64
# Various System Example Targets

BUILD_COMBO_EXAMPLE_PRIVATE_ALL =
# Various Private Example Targets
# Various Private System Example Targets

examples: $(BUILD_COMBO_EXAMPLE_ALL)

examples-private: $(BUILD_COMBO_EXAMPLE_PRIVATE_ALL)

 test_adc_am62lx-evm_a53ss0-0_nortos_gcc-aarch64:
	$(MAKE) -C drivers/adc/am62lx-evm/a53ss0-0_nortos/gcc-aarch64 -f makefile all

 test_adc_am62lx-evm_a53ss0-0_freertos_gcc-aarch64:
	$(MAKE) -C drivers/adc/am62lx-evm/a53ss0-0_freertos/gcc-aarch64 -f makefile all

 test_ecap_am62lx-evm_a53ss0-0_nortos_gcc-aarch64:
	$(MAKE) -C drivers/ecap/am62lx-evm/a53ss0-0_nortos/gcc-aarch64 -f makefile all

 test_ecap_am62lx-evm_a53ss0-0_freertos_gcc-aarch64:
	$(MAKE) -C drivers/ecap/am62lx-evm/a53ss0-0_freertos/gcc-aarch64 -f makefile all

 test_epwm_am62lx-evm_a53ss0-0_nortos_gcc-aarch64:
	$(MAKE) -C drivers/epwm/am62lx-evm/a53ss0-0_nortos/gcc-aarch64 -f makefile all

 test_epwm_am62lx-evm_a53ss0-0_freertos_gcc-aarch64:
	$(MAKE) -C drivers/epwm/am62lx-evm/a53ss0-0_freertos/gcc-aarch64 -f makefile all

 test_eqep_am62lx-evm_a53ss0-0_nortos_gcc-aarch64:
	$(MAKE) -C drivers/eqep/am62lx-evm/a53ss0-0_nortos/gcc-aarch64 -f makefile all

 test_eqep_am62lx-evm_a53ss0-0_freertos_gcc-aarch64:
	$(MAKE) -C drivers/eqep/am62lx-evm/a53ss0-0_freertos/gcc-aarch64 -f makefile all

 test_gpio_am62lx-evm_a53ss0-0_nortos_gcc-aarch64:
	$(MAKE) -C drivers/gpio/am62lx-evm/a53ss0-0_nortos/gcc-aarch64 -f makefile all

 test_gpio_am62lx-evm_a53ss0-0_freertos_gcc-aarch64:
	$(MAKE) -C drivers/gpio/am62lx-evm/a53ss0-0_freertos/gcc-aarch64 -f makefile all

 test_gtc_am62lx-evm_a53ss0-0_nortos_gcc-aarch64:
	$(MAKE) -C drivers/gtc/am62lx-evm/a53ss0-0_nortos/gcc-aarch64 -f makefile all

 test_gtc_am62lx-evm_a53ss0-0_freertos_gcc-aarch64:
	$(MAKE) -C drivers/gtc/am62lx-evm/a53ss0-0_freertos/gcc-aarch64 -f makefile all

 test_i2c_am62lx-evm_a53ss0-0_nortos_gcc-aarch64:
	$(MAKE) -C drivers/i2c/am62lx-evm/a53ss0-0_nortos/gcc-aarch64 -f makefile all

 test_i2c_am62lx-evm_a53ss0-0_freertos_gcc-aarch64:
	$(MAKE) -C drivers/i2c/am62lx-evm/a53ss0-0_freertos/gcc-aarch64 -f makefile all

 test_mmcsd_am62lx-evm_a53ss0-0_freertos_gcc-aarch64:
	$(MAKE) -C drivers/mmcsd/am62lx-evm/a53ss0-0_freertos/gcc-aarch64 -f makefile all

 test_mmcsd_am62lx-evm_a53ss0-0_nortos_gcc-aarch64:
	$(MAKE) -C drivers/mmcsd/am62lx-evm/a53ss0-0_nortos/gcc-aarch64 -f makefile all

 test_ospi_am62lx-evm_a53ss0-0_nortos_gcc-aarch64:
	$(MAKE) -C drivers/ospi/am62lx-evm/a53ss0-0_nortos/gcc-aarch64 -f makefile all

 test_ospi_am62lx-evm_a53ss0-0_freertos_gcc-aarch64:
	$(MAKE) -C drivers/ospi/am62lx-evm/a53ss0-0_freertos/gcc-aarch64 -f makefile all

 test_scmi_am62lx-evm_a53ss0-0_nortos_gcc-aarch64:
	$(MAKE) -C drivers/scp/scmi/am62lx-evm/a53ss0-0_nortos/gcc-aarch64 -f makefile all

 test_scmi_am62lx-evm_a53ss0-0_freertos_gcc-aarch64:
	$(MAKE) -C drivers/scp/scmi/am62lx-evm/a53ss0-0_freertos/gcc-aarch64 -f makefile all

 test_uart_am62lx-evm_a53ss0-0_nortos_gcc-aarch64:
	$(MAKE) -C drivers/uart/am62lx-evm/a53ss0-0_nortos/gcc-aarch64 -f makefile all

 test_uart_am62lx-evm_a53ss0-0_freertos_gcc-aarch64:
	$(MAKE) -C drivers/uart/am62lx-evm/a53ss0-0_freertos/gcc-aarch64 -f makefile all

 test_dpl_am62lx-evm_a53ss0-0_nortos_gcc-aarch64:
	$(MAKE) -C kernel/dpl/am62lx-evm/a53ss0-0_nortos/gcc-aarch64 -f makefile all

 test_dpl_am62lx-evm_a53ss0-0_freertos_gcc-aarch64:
	$(MAKE) -C kernel/dpl/am62lx-evm/a53ss0-0_freertos/gcc-aarch64 -f makefile all

 test_dpl_am62lx-evm_a53ss0-1_nortos_gcc-aarch64:
	$(MAKE) -C kernel/dpl/am62lx-evm/a53ss0-1_nortos/gcc-aarch64 -f makefile all

 test_dpl_am62lx-evm_a53ss0-1_freertos_gcc-aarch64:
	$(MAKE) -C kernel/dpl/am62lx-evm/a53ss0-1_freertos/gcc-aarch64 -f makefile all

 test_freertos_am62lx-evm_a53ss0-0_freertos_gcc-aarch64:
	$(MAKE) -C kernel/freertos/am62lx-evm/a53ss0-0_freertos/gcc-aarch64 -f makefile all

 test_freertos_am62lx-evm_a53ss0-1_freertos_gcc-aarch64:
	$(MAKE) -C kernel/freertos/am62lx-evm/a53ss0-1_freertos/gcc-aarch64 -f makefile all

 test_rov_am62lx-evm_a53ss0-0_freertos_gcc-aarch64:
	$(MAKE) -C kernel/rov/am62lx-evm/a53ss0-0_freertos/gcc-aarch64 -f makefile all


BUILD_COMBO_EXAMPLE_CLEAN_ALL =
# Various Example Clean Targets
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_adc_am62lx-evm_a53ss0-0_nortos_gcc-aarch64_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_adc_am62lx-evm_a53ss0-0_freertos_gcc-aarch64_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_ecap_am62lx-evm_a53ss0-0_nortos_gcc-aarch64_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_ecap_am62lx-evm_a53ss0-0_freertos_gcc-aarch64_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_epwm_am62lx-evm_a53ss0-0_nortos_gcc-aarch64_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_epwm_am62lx-evm_a53ss0-0_freertos_gcc-aarch64_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_eqep_am62lx-evm_a53ss0-0_nortos_gcc-aarch64_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_eqep_am62lx-evm_a53ss0-0_freertos_gcc-aarch64_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_gpio_am62lx-evm_a53ss0-0_nortos_gcc-aarch64_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_gpio_am62lx-evm_a53ss0-0_freertos_gcc-aarch64_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_gtc_am62lx-evm_a53ss0-0_nortos_gcc-aarch64_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_gtc_am62lx-evm_a53ss0-0_freertos_gcc-aarch64_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_i2c_am62lx-evm_a53ss0-0_nortos_gcc-aarch64_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_i2c_am62lx-evm_a53ss0-0_freertos_gcc-aarch64_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_mmcsd_am62lx-evm_a53ss0-0_freertos_gcc-aarch64_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_mmcsd_am62lx-evm_a53ss0-0_nortos_gcc-aarch64_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_ospi_am62lx-evm_a53ss0-0_nortos_gcc-aarch64_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_ospi_am62lx-evm_a53ss0-0_freertos_gcc-aarch64_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_scmi_am62lx-evm_a53ss0-0_nortos_gcc-aarch64_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_scmi_am62lx-evm_a53ss0-0_freertos_gcc-aarch64_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_uart_am62lx-evm_a53ss0-0_nortos_gcc-aarch64_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_uart_am62lx-evm_a53ss0-0_freertos_gcc-aarch64_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_dpl_am62lx-evm_a53ss0-0_nortos_gcc-aarch64_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_dpl_am62lx-evm_a53ss0-0_freertos_gcc-aarch64_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_dpl_am62lx-evm_a53ss0-1_nortos_gcc-aarch64_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_dpl_am62lx-evm_a53ss0-1_freertos_gcc-aarch64_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_freertos_am62lx-evm_a53ss0-0_freertos_gcc-aarch64_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_freertos_am62lx-evm_a53ss0-1_freertos_gcc-aarch64_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_rov_am62lx-evm_a53ss0-0_freertos_gcc-aarch64_clean
# Various System Example Clean Targets

BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL =
# Various Private Example Targets
# Various Private System Example Targets

examples-clean: $(BUILD_COMBO_EXAMPLE_CLEAN_ALL)

examples-private-clean: $(BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL)

 test_adc_am62lx-evm_a53ss0-0_nortos_gcc-aarch64_clean:
	$(MAKE) -C drivers/adc/am62lx-evm/a53ss0-0_nortos/gcc-aarch64 -f makefile clean

 test_adc_am62lx-evm_a53ss0-0_freertos_gcc-aarch64_clean:
	$(MAKE) -C drivers/adc/am62lx-evm/a53ss0-0_freertos/gcc-aarch64 -f makefile clean

 test_ecap_am62lx-evm_a53ss0-0_nortos_gcc-aarch64_clean:
	$(MAKE) -C drivers/ecap/am62lx-evm/a53ss0-0_nortos/gcc-aarch64 -f makefile clean

 test_ecap_am62lx-evm_a53ss0-0_freertos_gcc-aarch64_clean:
	$(MAKE) -C drivers/ecap/am62lx-evm/a53ss0-0_freertos/gcc-aarch64 -f makefile clean

 test_epwm_am62lx-evm_a53ss0-0_nortos_gcc-aarch64_clean:
	$(MAKE) -C drivers/epwm/am62lx-evm/a53ss0-0_nortos/gcc-aarch64 -f makefile clean

 test_epwm_am62lx-evm_a53ss0-0_freertos_gcc-aarch64_clean:
	$(MAKE) -C drivers/epwm/am62lx-evm/a53ss0-0_freertos/gcc-aarch64 -f makefile clean

 test_eqep_am62lx-evm_a53ss0-0_nortos_gcc-aarch64_clean:
	$(MAKE) -C drivers/eqep/am62lx-evm/a53ss0-0_nortos/gcc-aarch64 -f makefile clean

 test_eqep_am62lx-evm_a53ss0-0_freertos_gcc-aarch64_clean:
	$(MAKE) -C drivers/eqep/am62lx-evm/a53ss0-0_freertos/gcc-aarch64 -f makefile clean

 test_gpio_am62lx-evm_a53ss0-0_nortos_gcc-aarch64_clean:
	$(MAKE) -C drivers/gpio/am62lx-evm/a53ss0-0_nortos/gcc-aarch64 -f makefile clean

 test_gpio_am62lx-evm_a53ss0-0_freertos_gcc-aarch64_clean:
	$(MAKE) -C drivers/gpio/am62lx-evm/a53ss0-0_freertos/gcc-aarch64 -f makefile clean

 test_gtc_am62lx-evm_a53ss0-0_nortos_gcc-aarch64_clean:
	$(MAKE) -C drivers/gtc/am62lx-evm/a53ss0-0_nortos/gcc-aarch64 -f makefile clean

 test_gtc_am62lx-evm_a53ss0-0_freertos_gcc-aarch64_clean:
	$(MAKE) -C drivers/gtc/am62lx-evm/a53ss0-0_freertos/gcc-aarch64 -f makefile clean

 test_i2c_am62lx-evm_a53ss0-0_nortos_gcc-aarch64_clean:
	$(MAKE) -C drivers/i2c/am62lx-evm/a53ss0-0_nortos/gcc-aarch64 -f makefile clean

 test_i2c_am62lx-evm_a53ss0-0_freertos_gcc-aarch64_clean:
	$(MAKE) -C drivers/i2c/am62lx-evm/a53ss0-0_freertos/gcc-aarch64 -f makefile clean

 test_mmcsd_am62lx-evm_a53ss0-0_freertos_gcc-aarch64_clean:
	$(MAKE) -C drivers/mmcsd/am62lx-evm/a53ss0-0_freertos/gcc-aarch64 -f makefile clean

 test_mmcsd_am62lx-evm_a53ss0-0_nortos_gcc-aarch64_clean:
	$(MAKE) -C drivers/mmcsd/am62lx-evm/a53ss0-0_nortos/gcc-aarch64 -f makefile clean

 test_ospi_am62lx-evm_a53ss0-0_nortos_gcc-aarch64_clean:
	$(MAKE) -C drivers/ospi/am62lx-evm/a53ss0-0_nortos/gcc-aarch64 -f makefile clean

 test_ospi_am62lx-evm_a53ss0-0_freertos_gcc-aarch64_clean:
	$(MAKE) -C drivers/ospi/am62lx-evm/a53ss0-0_freertos/gcc-aarch64 -f makefile clean

 test_scmi_am62lx-evm_a53ss0-0_nortos_gcc-aarch64_clean:
	$(MAKE) -C drivers/scp/scmi/am62lx-evm/a53ss0-0_nortos/gcc-aarch64 -f makefile clean

 test_scmi_am62lx-evm_a53ss0-0_freertos_gcc-aarch64_clean:
	$(MAKE) -C drivers/scp/scmi/am62lx-evm/a53ss0-0_freertos/gcc-aarch64 -f makefile clean

 test_uart_am62lx-evm_a53ss0-0_nortos_gcc-aarch64_clean:
	$(MAKE) -C drivers/uart/am62lx-evm/a53ss0-0_nortos/gcc-aarch64 -f makefile clean

 test_uart_am62lx-evm_a53ss0-0_freertos_gcc-aarch64_clean:
	$(MAKE) -C drivers/uart/am62lx-evm/a53ss0-0_freertos/gcc-aarch64 -f makefile clean

 test_dpl_am62lx-evm_a53ss0-0_nortos_gcc-aarch64_clean:
	$(MAKE) -C kernel/dpl/am62lx-evm/a53ss0-0_nortos/gcc-aarch64 -f makefile clean

 test_dpl_am62lx-evm_a53ss0-0_freertos_gcc-aarch64_clean:
	$(MAKE) -C kernel/dpl/am62lx-evm/a53ss0-0_freertos/gcc-aarch64 -f makefile clean

 test_dpl_am62lx-evm_a53ss0-1_nortos_gcc-aarch64_clean:
	$(MAKE) -C kernel/dpl/am62lx-evm/a53ss0-1_nortos/gcc-aarch64 -f makefile clean

 test_dpl_am62lx-evm_a53ss0-1_freertos_gcc-aarch64_clean:
	$(MAKE) -C kernel/dpl/am62lx-evm/a53ss0-1_freertos/gcc-aarch64 -f makefile clean

 test_freertos_am62lx-evm_a53ss0-0_freertos_gcc-aarch64_clean:
	$(MAKE) -C kernel/freertos/am62lx-evm/a53ss0-0_freertos/gcc-aarch64 -f makefile clean

 test_freertos_am62lx-evm_a53ss0-1_freertos_gcc-aarch64_clean:
	$(MAKE) -C kernel/freertos/am62lx-evm/a53ss0-1_freertos/gcc-aarch64 -f makefile clean

 test_rov_am62lx-evm_a53ss0-0_freertos_gcc-aarch64_clean:
	$(MAKE) -C kernel/rov/am62lx-evm/a53ss0-0_freertos/gcc-aarch64 -f makefile clean


BUILD_COMBO_EXAMPLE_SCRUB_ALL =
# Various Example Scrub Targets
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_adc_am62lx-evm_a53ss0-0_nortos_gcc-aarch64_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_adc_am62lx-evm_a53ss0-0_freertos_gcc-aarch64_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_ecap_am62lx-evm_a53ss0-0_nortos_gcc-aarch64_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_ecap_am62lx-evm_a53ss0-0_freertos_gcc-aarch64_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_epwm_am62lx-evm_a53ss0-0_nortos_gcc-aarch64_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_epwm_am62lx-evm_a53ss0-0_freertos_gcc-aarch64_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_eqep_am62lx-evm_a53ss0-0_nortos_gcc-aarch64_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_eqep_am62lx-evm_a53ss0-0_freertos_gcc-aarch64_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_gpio_am62lx-evm_a53ss0-0_nortos_gcc-aarch64_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_gpio_am62lx-evm_a53ss0-0_freertos_gcc-aarch64_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_gtc_am62lx-evm_a53ss0-0_nortos_gcc-aarch64_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_gtc_am62lx-evm_a53ss0-0_freertos_gcc-aarch64_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_i2c_am62lx-evm_a53ss0-0_nortos_gcc-aarch64_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_i2c_am62lx-evm_a53ss0-0_freertos_gcc-aarch64_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_mmcsd_am62lx-evm_a53ss0-0_freertos_gcc-aarch64_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_mmcsd_am62lx-evm_a53ss0-0_nortos_gcc-aarch64_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_ospi_am62lx-evm_a53ss0-0_nortos_gcc-aarch64_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_ospi_am62lx-evm_a53ss0-0_freertos_gcc-aarch64_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_scmi_am62lx-evm_a53ss0-0_nortos_gcc-aarch64_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_scmi_am62lx-evm_a53ss0-0_freertos_gcc-aarch64_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_uart_am62lx-evm_a53ss0-0_nortos_gcc-aarch64_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_uart_am62lx-evm_a53ss0-0_freertos_gcc-aarch64_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_dpl_am62lx-evm_a53ss0-0_nortos_gcc-aarch64_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_dpl_am62lx-evm_a53ss0-0_freertos_gcc-aarch64_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_dpl_am62lx-evm_a53ss0-1_nortos_gcc-aarch64_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_dpl_am62lx-evm_a53ss0-1_freertos_gcc-aarch64_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_freertos_am62lx-evm_a53ss0-0_freertos_gcc-aarch64_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_freertos_am62lx-evm_a53ss0-1_freertos_gcc-aarch64_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_rov_am62lx-evm_a53ss0-0_freertos_gcc-aarch64_scrub
# Various System Example Scrub Targets

BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL =
# Various Private Example Targets
# Various Private System Example Targets

examples-scrub: $(BUILD_COMBO_EXAMPLE_SCRUB_ALL)

examples-scrub-private: $(BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL)

 test_adc_am62lx-evm_a53ss0-0_nortos_gcc-aarch64_scrub:
	$(MAKE) -C drivers/adc/am62lx-evm/a53ss0-0_nortos/gcc-aarch64 -f makefile scrub

 test_adc_am62lx-evm_a53ss0-0_freertos_gcc-aarch64_scrub:
	$(MAKE) -C drivers/adc/am62lx-evm/a53ss0-0_freertos/gcc-aarch64 -f makefile scrub

 test_ecap_am62lx-evm_a53ss0-0_nortos_gcc-aarch64_scrub:
	$(MAKE) -C drivers/ecap/am62lx-evm/a53ss0-0_nortos/gcc-aarch64 -f makefile scrub

 test_ecap_am62lx-evm_a53ss0-0_freertos_gcc-aarch64_scrub:
	$(MAKE) -C drivers/ecap/am62lx-evm/a53ss0-0_freertos/gcc-aarch64 -f makefile scrub

 test_epwm_am62lx-evm_a53ss0-0_nortos_gcc-aarch64_scrub:
	$(MAKE) -C drivers/epwm/am62lx-evm/a53ss0-0_nortos/gcc-aarch64 -f makefile scrub

 test_epwm_am62lx-evm_a53ss0-0_freertos_gcc-aarch64_scrub:
	$(MAKE) -C drivers/epwm/am62lx-evm/a53ss0-0_freertos/gcc-aarch64 -f makefile scrub

 test_eqep_am62lx-evm_a53ss0-0_nortos_gcc-aarch64_scrub:
	$(MAKE) -C drivers/eqep/am62lx-evm/a53ss0-0_nortos/gcc-aarch64 -f makefile scrub

 test_eqep_am62lx-evm_a53ss0-0_freertos_gcc-aarch64_scrub:
	$(MAKE) -C drivers/eqep/am62lx-evm/a53ss0-0_freertos/gcc-aarch64 -f makefile scrub

 test_gpio_am62lx-evm_a53ss0-0_nortos_gcc-aarch64_scrub:
	$(MAKE) -C drivers/gpio/am62lx-evm/a53ss0-0_nortos/gcc-aarch64 -f makefile scrub

 test_gpio_am62lx-evm_a53ss0-0_freertos_gcc-aarch64_scrub:
	$(MAKE) -C drivers/gpio/am62lx-evm/a53ss0-0_freertos/gcc-aarch64 -f makefile scrub

 test_gtc_am62lx-evm_a53ss0-0_nortos_gcc-aarch64_scrub:
	$(MAKE) -C drivers/gtc/am62lx-evm/a53ss0-0_nortos/gcc-aarch64 -f makefile scrub

 test_gtc_am62lx-evm_a53ss0-0_freertos_gcc-aarch64_scrub:
	$(MAKE) -C drivers/gtc/am62lx-evm/a53ss0-0_freertos/gcc-aarch64 -f makefile scrub

 test_i2c_am62lx-evm_a53ss0-0_nortos_gcc-aarch64_scrub:
	$(MAKE) -C drivers/i2c/am62lx-evm/a53ss0-0_nortos/gcc-aarch64 -f makefile scrub

 test_i2c_am62lx-evm_a53ss0-0_freertos_gcc-aarch64_scrub:
	$(MAKE) -C drivers/i2c/am62lx-evm/a53ss0-0_freertos/gcc-aarch64 -f makefile scrub

 test_mmcsd_am62lx-evm_a53ss0-0_freertos_gcc-aarch64_scrub:
	$(MAKE) -C drivers/mmcsd/am62lx-evm/a53ss0-0_freertos/gcc-aarch64 -f makefile scrub

 test_mmcsd_am62lx-evm_a53ss0-0_nortos_gcc-aarch64_scrub:
	$(MAKE) -C drivers/mmcsd/am62lx-evm/a53ss0-0_nortos/gcc-aarch64 -f makefile scrub

 test_ospi_am62lx-evm_a53ss0-0_nortos_gcc-aarch64_scrub:
	$(MAKE) -C drivers/ospi/am62lx-evm/a53ss0-0_nortos/gcc-aarch64 -f makefile scrub

 test_ospi_am62lx-evm_a53ss0-0_freertos_gcc-aarch64_scrub:
	$(MAKE) -C drivers/ospi/am62lx-evm/a53ss0-0_freertos/gcc-aarch64 -f makefile scrub

 test_scmi_am62lx-evm_a53ss0-0_nortos_gcc-aarch64_scrub:
	$(MAKE) -C drivers/scp/scmi/am62lx-evm/a53ss0-0_nortos/gcc-aarch64 -f makefile scrub

 test_scmi_am62lx-evm_a53ss0-0_freertos_gcc-aarch64_scrub:
	$(MAKE) -C drivers/scp/scmi/am62lx-evm/a53ss0-0_freertos/gcc-aarch64 -f makefile scrub

 test_uart_am62lx-evm_a53ss0-0_nortos_gcc-aarch64_scrub:
	$(MAKE) -C drivers/uart/am62lx-evm/a53ss0-0_nortos/gcc-aarch64 -f makefile scrub

 test_uart_am62lx-evm_a53ss0-0_freertos_gcc-aarch64_scrub:
	$(MAKE) -C drivers/uart/am62lx-evm/a53ss0-0_freertos/gcc-aarch64 -f makefile scrub

 test_dpl_am62lx-evm_a53ss0-0_nortos_gcc-aarch64_scrub:
	$(MAKE) -C kernel/dpl/am62lx-evm/a53ss0-0_nortos/gcc-aarch64 -f makefile scrub

 test_dpl_am62lx-evm_a53ss0-0_freertos_gcc-aarch64_scrub:
	$(MAKE) -C kernel/dpl/am62lx-evm/a53ss0-0_freertos/gcc-aarch64 -f makefile scrub

 test_dpl_am62lx-evm_a53ss0-1_nortos_gcc-aarch64_scrub:
	$(MAKE) -C kernel/dpl/am62lx-evm/a53ss0-1_nortos/gcc-aarch64 -f makefile scrub

 test_dpl_am62lx-evm_a53ss0-1_freertos_gcc-aarch64_scrub:
	$(MAKE) -C kernel/dpl/am62lx-evm/a53ss0-1_freertos/gcc-aarch64 -f makefile scrub

 test_freertos_am62lx-evm_a53ss0-0_freertos_gcc-aarch64_scrub:
	$(MAKE) -C kernel/freertos/am62lx-evm/a53ss0-0_freertos/gcc-aarch64 -f makefile scrub

 test_freertos_am62lx-evm_a53ss0-1_freertos_gcc-aarch64_scrub:
	$(MAKE) -C kernel/freertos/am62lx-evm/a53ss0-1_freertos/gcc-aarch64 -f makefile scrub

 test_rov_am62lx-evm_a53ss0-0_freertos_gcc-aarch64_scrub:
	$(MAKE) -C kernel/rov/am62lx-evm/a53ss0-0_freertos/gcc-aarch64 -f makefile scrub


sbl: libs

sbl-clean:

sbl-scrub:



.PHONY: all clean scrub help
.PHONY: libs libs-clean libs-scrub
.PHONY: libs-external libs-external-clean libs-external-scrub
.PHONY: libs-private
.PHONY: libs-prebuilt libs-prebuilt-clean libs-prebuilt-scrub
.PHONY: examples examples-clean examples-scrub
.PHONY: examples-private examples-private-clean examples-private-scrub
.PHONY: sbl sbl-clean sbl-scrub
.PHONY: $(BUILD_COMBO_ALL) $(BUILD_COMBO_CLEAN_ALL) $(BUILD_COMBO_SCRUB_ALL)
.PHONY: $(BUILD_COMBO_EXAMPLE_ALL) $(BUILD_COMBO_EXAMPLE_CLEAN_ALL) $(BUILD_COMBO_EXAMPLE_SCRUB_ALL)
.PHONY: $(BUILD_COMBO_EXAMPLE_PRIVATE_ALL) $(BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL) $(BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL)
