#
# Auto generated makefile
#

all:
	$(MAKE) -f makefile.am62px libs
	$(MAKE) -f makefile.am62px sbl
	$(MAKE) -f makefile.am62px examples

clean: libs-clean sbl-clean examples-clean
scrub: libs-scrub sbl-scrub examples-scrub

help:
	@echo  Notes,
	@echo  - Use -j to invoke parallel builds
	@echo  - Use PROFILE=debug or PROFILE=release [default] to build in debug or release profile
	@echo  .
	@echo  Overall build targets,
	@echo  ======================
	@echo  $(MAKE) -s -f makefile.am62px help
	@echo  .
	@echo  $(MAKE) -s -f makefile.am62px all
	@echo  $(MAKE) -s -f makefile.am62px clean  # delete's tmp files for current profile
	@echo  $(MAKE) -s -f makefile.am62px scrub  # delete's all tmp files and folders for all profiles
	@echo  .
	@echo  $(MAKE) -s -f makefile.am62px libs
	@echo  $(MAKE) -s -f makefile.am62px libs-clean # delete's tmp files for current profile
	@echo  $(MAKE) -s -f makefile.am62px libs-scrub # delete's all tmp files and folders for all profiles
	@echo  .
	@echo  $(MAKE) -s -f makefile.am62px examples
	@echo  $(MAKE) -s -f makefile.am62px examples-clean # delete's tmp files for current profile
	@echo  $(MAKE) -s -f makefile.am62px examples-scrub # delete's all tmp files and folders for all profiles
	@echo  .
	@echo  Library build targets,
	@echo  ======================
	@echo  $(MAKE) -s -f makefile.am62px doxy_samples_r5f.ti-arm-clang
	@echo  $(MAKE) -s -f makefile.am62px unity_r5f.ti-arm-clang
	@echo  .
	@echo  Library clean targets,
	@echo  ======================
	@echo  $(MAKE) -s -f makefile.am62px doxy_samples_r5f.ti-arm-clang_clean
	@echo  $(MAKE) -s -f makefile.am62px unity_r5f.ti-arm-clang_clean
	@echo  .
	@echo  Example build targets,
	@echo  ======================
	@echo  $(MAKE) -s -C sdl/dcc/dcc_unit_test/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C sdl/dcc/dcc_func_test/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C sdl/ecc/ecc_sdl_funcTest/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C sdl/ecc/ecc_sdl_unitTest/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C sdl/esm/esm_func_test/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C sdl/esm/esm_unit_test/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C sdl/lbist/am62px-sk/wkup-r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C sdl/lbist/am62px-sk/wkup-r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C sdl/mcrc/mcrcAutomodeTest/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C sdl/mcrc/mcrcFuncTest/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C sdl/mcrc/mcrcSemimodeTest/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C sdl/mcrc/mcrcUt/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C sdl/mtog/mtog_functest/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C sdl/mtog/mtog_unit_test/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C sdl/pbist/ip_pbist_test/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C sdl/pbist/ip_pbist_test/am62px-sk/mcu-r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C sdl/pbist/sdl_pbist_test/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C sdl/pbist/sdl_pbist_test/am62px-sk/mcu-r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C sdl/pok/pokFuncTest/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C sdl/pok/pokUt/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C sdl/rom_checksum/functional_test/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C sdl/rom_checksum/unit_test/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C sdl/rti/rtiFuncTest/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C sdl/rti/rtiUt/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C sdl/stog/stog_func_test/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C sdl/stog/stog_unit_test/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C sdl/vtm/vtm_func_test/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C sdl/vtm/vtm_unit_test/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C board/flash/am62px-sk/wkup-r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C board/led/am62px-sk/wkup-r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/boot/sbl_ospi_linux_multistage_ddr_ecc/sbl_ospi_linux_stage1/am62px-sk/wkup-r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/ddr/am62px-sk/wkup-r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/gpio/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/gpio/am62px-sk/wkup-r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/gtc/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/mmcsd/am62px-sk/wkup-r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/sciclient/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/sciclient/am62px-sk/wkup-r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/i2c/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/i2c/am62px-sk/wkup-r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/ospi/am62px-sk/wkup-r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/uart/am62px-sk/mcu-r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C kernel/dpl/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C kernel/dpl/am62px-sk/mcu-r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C kernel/dpl/am62px-sk/wkup-r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C kernel/freertos/am62px-sk/mcu-r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C kernel/freertos/am62px-sk/wkup-r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C kernel/rov/am62px-sk/mcu-r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  .
	@echo  System Example build targets,
	@echo  =============================
	@echo  $(MAKE) -s -C drivers/ipc_notify/am62px-sk/system_freertos_nortos [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/ipc_rpmsg/am62px-sk/system_freertos [all clean syscfg-gui syscfg]
	@echo  .

# Various Component Targets
BUILD_COMBO_doxy_samples = doxy_samples_r5f.ti-arm-clang
BUILD_COMBO_unity = unity_r5f.ti-arm-clang

# Combine all Components
BUILD_COMBO_ALL = $(BUILD_COMBO_doxy_samples) $(BUILD_COMBO_unity)

# Combine all Pre-built Components
BUILD_COMBO_PREBUILT_ALL =

# Combine all Private Components
BUILD_COMBO_PRIVATE_ALL =

libs: $(BUILD_COMBO_ALL)

libs-prebuilt: $(BUILD_COMBO_PREBUILT_ALL)

libs-private: $(BUILD_COMBO_PRIVATE_ALL)

$(BUILD_COMBO_doxy_samples):
	$(MAKE) -C ../docs_src/docs/api_guide/doxy_samples -f makefile.am62px.$(subst doxy_samples_,,$@) all

$(BUILD_COMBO_unity):
	$(MAKE) -C unity -f makefile.am62px.$(subst unity_,,$@) all


# Various Component Clean Targets
BUILD_COMBO_CLEAN_doxy_samples = doxy_samples_r5f.ti-arm-clang_clean
BUILD_COMBO_CLEAN_unity = unity_r5f.ti-arm-clang_clean

# Combine all Components Clean
BUILD_COMBO_CLEAN_ALL = $(BUILD_COMBO_CLEAN_doxy_samples) $(BUILD_COMBO_CLEAN_unity)

# Combine all Pre-built Components Clean
BUILD_COMBO_PREBUILT_CLEAN_ALL =

libs-clean: $(BUILD_COMBO_CLEAN_ALL)

libs-prebuilt-clean: $(BUILD_COMBO_PREBUILT_CLEAN_ALL)

$(BUILD_COMBO_CLEAN_doxy_samples):
	$(MAKE) -C ../docs_src/docs/api_guide/doxy_samples -f makefile.am62px.$(subst doxy_samples_,,$(subst _clean,,$@)) clean

$(BUILD_COMBO_CLEAN_unity):
	$(MAKE) -C unity -f makefile.am62px.$(subst unity_,,$(subst _clean,,$@)) clean


# Various Component Scrub Targets
BUILD_COMBO_SCRUB_doxy_samples = doxy_samples_r5f.ti-arm-clang_scrub_scrub
BUILD_COMBO_SCRUB_unity = unity_r5f.ti-arm-clang_scrub_scrub

# Combine all Components Scrub Targets
BUILD_COMBO_SCRUB_ALL = $(BUILD_COMBO_SCRUB_doxy_samples) $(BUILD_COMBO_SCRUB_unity)

# Combine all Pre-built Components Scrub Targets
BUILD_COMBO_PREBUILT_SCRUB_ALL =

libs-scrub: $(BUILD_COMBO_SCRUB_ALL)

libs-prebuilt-scrub: $(BUILD_COMBO_PREBUILT_SCRUB_ALL)

$(BUILD_COMBO_SCRUB_doxy_samples):
	$(MAKE) -C ../docs_src/docs/api_guide/doxy_samples -f makefile.am62px.$(subst doxy_samples_,,$(subst _scrub,,$@)) scrub

$(BUILD_COMBO_SCRUB_unity):
	$(MAKE) -C unity -f makefile.am62px.$(subst unity_,,$(subst _scrub,,$@)) scrub


BUILD_COMBO_EXAMPLE_ALL =
# Various Example Targets
BUILD_COMBO_EXAMPLE_ALL += dcc_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += dcc_func_test_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += sdl_ecc_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += ecc_ut_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_esm_func_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += esm_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_lbist_func_am62px-sk_wkup-r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_lbist_func_am62px-sk_wkup-r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += sdl_mcrc_auto_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += sdl_mcrc_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += sdl_mcrc_semi_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += mcrc_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += sdl_mtog_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += mtog_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += pbist_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += pbist_test_app_am62px-sk_mcu-r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += sdl_pbist_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += sdl_pbist_test_app_am62px-sk_mcu-r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += pok_func_test_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += pok_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += rom_checksum_func_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += rom_checksum_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += sdl_rti_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += rti_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += stog_func_test_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += tog_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += sdl_vtm_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += vtm_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_flash_am62px-sk_wkup-r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_led_am62px-sk_wkup-r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_gpio_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_gpio_am62px-sk_wkup-r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_gtc_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_mmcsd_am62px-sk_wkup-r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_sciclient_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_sciclient_am62px-sk_wkup-r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_i2c_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_i2c_am62px-sk_wkup-r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_ospi_am62px-sk_wkup-r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_uart_am62px-sk_mcu-r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_dpl_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_dpl_am62px-sk_mcu-r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_dpl_am62px-sk_wkup-r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_freertos_am62px-sk_mcu-r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_freertos_am62px-sk_wkup-r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_rov_am62px-sk_mcu-r5fss0-0_freertos_ti-arm-clang
# Various System Example Targets
BUILD_COMBO_EXAMPLE_ALL += test_ipc_notify_am62px-sk_system_freertos_nortos
BUILD_COMBO_EXAMPLE_ALL += test_ipc_rpmsg_am62px-sk_system_freertos

BUILD_COMBO_EXAMPLE_PRIVATE_ALL =
# Various Private Example Targets
# Various Private System Example Targets

examples: $(BUILD_COMBO_EXAMPLE_ALL)

examples-private: $(BUILD_COMBO_EXAMPLE_PRIVATE_ALL)

 dcc_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C sdl/dcc/dcc_unit_test/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile all

 dcc_func_test_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C sdl/dcc/dcc_func_test/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile all

 sdl_ecc_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C sdl/ecc/ecc_sdl_funcTest/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile all

 ecc_ut_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C sdl/ecc/ecc_sdl_unitTest/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile all

 test_esm_func_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C sdl/esm/esm_func_test/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile all

 esm_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C sdl/esm/esm_unit_test/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile all

 test_lbist_func_am62px-sk_wkup-r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C sdl/lbist/am62px-sk/wkup-r5fss0-0_nortos/ti-arm-clang -f makefile all

 test_lbist_func_am62px-sk_wkup-r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C sdl/lbist/am62px-sk/wkup-r5fss0-0_freertos/ti-arm-clang -f makefile all

 sdl_mcrc_auto_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C sdl/mcrc/mcrcAutomodeTest/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile all

 sdl_mcrc_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C sdl/mcrc/mcrcFuncTest/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile all

 sdl_mcrc_semi_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C sdl/mcrc/mcrcSemimodeTest/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile all

 mcrc_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C sdl/mcrc/mcrcUt/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile all

 sdl_mtog_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C sdl/mtog/mtog_functest/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile all

 mtog_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C sdl/mtog/mtog_unit_test/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile all

 pbist_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C sdl/pbist/ip_pbist_test/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile all

 pbist_test_app_am62px-sk_mcu-r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C sdl/pbist/ip_pbist_test/am62px-sk/mcu-r5fss0-0_freertos/ti-arm-clang -f makefile all

 sdl_pbist_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C sdl/pbist/sdl_pbist_test/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile all

 sdl_pbist_test_app_am62px-sk_mcu-r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C sdl/pbist/sdl_pbist_test/am62px-sk/mcu-r5fss0-0_freertos/ti-arm-clang -f makefile all

 pok_func_test_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C sdl/pok/pokFuncTest/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile all

 pok_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C sdl/pok/pokUt/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile all

 rom_checksum_func_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C sdl/rom_checksum/functional_test/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile all

 rom_checksum_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C sdl/rom_checksum/unit_test/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile all

 sdl_rti_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C sdl/rti/rtiFuncTest/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile all

 rti_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C sdl/rti/rtiUt/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile all

 stog_func_test_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C sdl/stog/stog_func_test/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile all

 tog_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C sdl/stog/stog_unit_test/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile all

 sdl_vtm_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C sdl/vtm/vtm_func_test/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile all

 vtm_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C sdl/vtm/vtm_unit_test/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile all

 test_flash_am62px-sk_wkup-r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C board/flash/am62px-sk/wkup-r5fss0-0_freertos/ti-arm-clang -f makefile all

 test_led_am62px-sk_wkup-r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C board/led/am62px-sk/wkup-r5fss0-0_freertos/ti-arm-clang -f makefile all

 sbl_ospi_linux_stage1_ddr_ecc_am62px-sk_wkup-r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C drivers/boot/sbl_ospi_linux_multistage_ddr_ecc/sbl_ospi_linux_stage1/am62px-sk/wkup-r5fss0-0_nortos/ti-arm-clang -f makefile all

 test_ddr_am62px-sk_wkup-r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C drivers/ddr/am62px-sk/wkup-r5fss0-0_nortos/ti-arm-clang -f makefile all

 test_gpio_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C drivers/gpio/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile all

 test_gpio_am62px-sk_wkup-r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C drivers/gpio/am62px-sk/wkup-r5fss0-0_freertos/ti-arm-clang -f makefile all

 test_gtc_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C drivers/gtc/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile all

 test_mmcsd_am62px-sk_wkup-r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C drivers/mmcsd/am62px-sk/wkup-r5fss0-0_freertos/ti-arm-clang -f makefile all

 test_sciclient_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C drivers/sciclient/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile all

 test_sciclient_am62px-sk_wkup-r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C drivers/sciclient/am62px-sk/wkup-r5fss0-0_freertos/ti-arm-clang -f makefile all

 test_i2c_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C drivers/i2c/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile all

 test_i2c_am62px-sk_wkup-r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C drivers/i2c/am62px-sk/wkup-r5fss0-0_freertos/ti-arm-clang -f makefile all

 test_ospi_am62px-sk_wkup-r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C drivers/ospi/am62px-sk/wkup-r5fss0-0_freertos/ti-arm-clang -f makefile all

 test_uart_am62px-sk_mcu-r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C drivers/uart/am62px-sk/mcu-r5fss0-0_freertos/ti-arm-clang -f makefile all

 test_dpl_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C kernel/dpl/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile all

 test_dpl_am62px-sk_mcu-r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C kernel/dpl/am62px-sk/mcu-r5fss0-0_freertos/ti-arm-clang -f makefile all

 test_dpl_am62px-sk_wkup-r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C kernel/dpl/am62px-sk/wkup-r5fss0-0_freertos/ti-arm-clang -f makefile all

 test_freertos_am62px-sk_mcu-r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C kernel/freertos/am62px-sk/mcu-r5fss0-0_freertos/ti-arm-clang -f makefile all

 test_freertos_am62px-sk_wkup-r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C kernel/freertos/am62px-sk/wkup-r5fss0-0_freertos/ti-arm-clang -f makefile all

 test_rov_am62px-sk_mcu-r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C kernel/rov/am62px-sk/mcu-r5fss0-0_freertos/ti-arm-clang -f makefile all

 test_ipc_notify_am62px-sk_system_freertos_nortos:
	$(MAKE) -C drivers/ipc_notify/am62px-sk/system_freertos_nortos -f makefile all

 test_ipc_rpmsg_am62px-sk_system_freertos:
	$(MAKE) -C drivers/ipc_rpmsg/am62px-sk/system_freertos -f makefile all


BUILD_COMBO_EXAMPLE_CLEAN_ALL =
# Various Example Clean Targets
BUILD_COMBO_EXAMPLE_CLEAN_ALL += dcc_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += dcc_func_test_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += sdl_ecc_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += ecc_ut_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_esm_func_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += esm_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_lbist_func_am62px-sk_wkup-r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_lbist_func_am62px-sk_wkup-r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += sdl_mcrc_auto_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += sdl_mcrc_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += sdl_mcrc_semi_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += mcrc_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += sdl_mtog_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += mtog_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += pbist_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += pbist_test_app_am62px-sk_mcu-r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += sdl_pbist_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += sdl_pbist_test_app_am62px-sk_mcu-r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += pok_func_test_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += pok_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += rom_checksum_func_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += rom_checksum_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += sdl_rti_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += rti_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += stog_func_test_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += tog_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += sdl_vtm_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += vtm_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_flash_am62px-sk_wkup-r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_led_am62px-sk_wkup-r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_gpio_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_gpio_am62px-sk_wkup-r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_gtc_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_mmcsd_am62px-sk_wkup-r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_sciclient_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_sciclient_am62px-sk_wkup-r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_i2c_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_i2c_am62px-sk_wkup-r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_ospi_am62px-sk_wkup-r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_uart_am62px-sk_mcu-r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_dpl_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_dpl_am62px-sk_mcu-r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_dpl_am62px-sk_wkup-r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_freertos_am62px-sk_mcu-r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_freertos_am62px-sk_wkup-r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_rov_am62px-sk_mcu-r5fss0-0_freertos_ti-arm-clang_clean
# Various System Example Clean Targets
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_ipc_notify_am62px-sk_system_freertos_nortos_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_ipc_rpmsg_am62px-sk_system_freertos_clean

BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL =
# Various Private Example Targets
# Various Private System Example Targets

examples-clean: $(BUILD_COMBO_EXAMPLE_CLEAN_ALL)

examples-private-clean: $(BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL)

 dcc_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C sdl/dcc/dcc_unit_test/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile clean

 dcc_func_test_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C sdl/dcc/dcc_func_test/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile clean

 sdl_ecc_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C sdl/ecc/ecc_sdl_funcTest/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile clean

 ecc_ut_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C sdl/ecc/ecc_sdl_unitTest/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile clean

 test_esm_func_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C sdl/esm/esm_func_test/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile clean

 esm_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C sdl/esm/esm_unit_test/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile clean

 test_lbist_func_am62px-sk_wkup-r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C sdl/lbist/am62px-sk/wkup-r5fss0-0_nortos/ti-arm-clang -f makefile clean

 test_lbist_func_am62px-sk_wkup-r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C sdl/lbist/am62px-sk/wkup-r5fss0-0_freertos/ti-arm-clang -f makefile clean

 sdl_mcrc_auto_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C sdl/mcrc/mcrcAutomodeTest/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile clean

 sdl_mcrc_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C sdl/mcrc/mcrcFuncTest/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile clean

 sdl_mcrc_semi_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C sdl/mcrc/mcrcSemimodeTest/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile clean

 mcrc_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C sdl/mcrc/mcrcUt/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile clean

 sdl_mtog_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C sdl/mtog/mtog_functest/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile clean

 mtog_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C sdl/mtog/mtog_unit_test/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile clean

 pbist_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C sdl/pbist/ip_pbist_test/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile clean

 pbist_test_app_am62px-sk_mcu-r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C sdl/pbist/ip_pbist_test/am62px-sk/mcu-r5fss0-0_freertos/ti-arm-clang -f makefile clean

 sdl_pbist_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C sdl/pbist/sdl_pbist_test/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile clean

 sdl_pbist_test_app_am62px-sk_mcu-r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C sdl/pbist/sdl_pbist_test/am62px-sk/mcu-r5fss0-0_freertos/ti-arm-clang -f makefile clean

 pok_func_test_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C sdl/pok/pokFuncTest/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile clean

 pok_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C sdl/pok/pokUt/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile clean

 rom_checksum_func_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C sdl/rom_checksum/functional_test/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile clean

 rom_checksum_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C sdl/rom_checksum/unit_test/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile clean

 sdl_rti_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C sdl/rti/rtiFuncTest/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile clean

 rti_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C sdl/rti/rtiUt/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile clean

 stog_func_test_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C sdl/stog/stog_func_test/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile clean

 tog_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C sdl/stog/stog_unit_test/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile clean

 sdl_vtm_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C sdl/vtm/vtm_func_test/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile clean

 vtm_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C sdl/vtm/vtm_unit_test/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile clean

 test_flash_am62px-sk_wkup-r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C board/flash/am62px-sk/wkup-r5fss0-0_freertos/ti-arm-clang -f makefile clean

 test_led_am62px-sk_wkup-r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C board/led/am62px-sk/wkup-r5fss0-0_freertos/ti-arm-clang -f makefile clean

 sbl_ospi_linux_stage1_ddr_ecc_am62px-sk_wkup-r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C drivers/boot/sbl_ospi_linux_multistage_ddr_ecc/sbl_ospi_linux_stage1/am62px-sk/wkup-r5fss0-0_nortos/ti-arm-clang -f makefile clean

 test_ddr_am62px-sk_wkup-r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C drivers/ddr/am62px-sk/wkup-r5fss0-0_nortos/ti-arm-clang -f makefile clean

 test_gpio_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C drivers/gpio/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile clean

 test_gpio_am62px-sk_wkup-r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C drivers/gpio/am62px-sk/wkup-r5fss0-0_freertos/ti-arm-clang -f makefile clean

 test_gtc_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C drivers/gtc/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile clean

 test_mmcsd_am62px-sk_wkup-r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C drivers/mmcsd/am62px-sk/wkup-r5fss0-0_freertos/ti-arm-clang -f makefile clean

 test_sciclient_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C drivers/sciclient/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile clean

 test_sciclient_am62px-sk_wkup-r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C drivers/sciclient/am62px-sk/wkup-r5fss0-0_freertos/ti-arm-clang -f makefile clean

 test_i2c_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C drivers/i2c/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile clean

 test_i2c_am62px-sk_wkup-r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C drivers/i2c/am62px-sk/wkup-r5fss0-0_freertos/ti-arm-clang -f makefile clean

 test_ospi_am62px-sk_wkup-r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C drivers/ospi/am62px-sk/wkup-r5fss0-0_freertos/ti-arm-clang -f makefile clean

 test_uart_am62px-sk_mcu-r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C drivers/uart/am62px-sk/mcu-r5fss0-0_freertos/ti-arm-clang -f makefile clean

 test_dpl_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C kernel/dpl/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile clean

 test_dpl_am62px-sk_mcu-r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C kernel/dpl/am62px-sk/mcu-r5fss0-0_freertos/ti-arm-clang -f makefile clean

 test_dpl_am62px-sk_wkup-r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C kernel/dpl/am62px-sk/wkup-r5fss0-0_freertos/ti-arm-clang -f makefile clean

 test_freertos_am62px-sk_mcu-r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C kernel/freertos/am62px-sk/mcu-r5fss0-0_freertos/ti-arm-clang -f makefile clean

 test_freertos_am62px-sk_wkup-r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C kernel/freertos/am62px-sk/wkup-r5fss0-0_freertos/ti-arm-clang -f makefile clean

 test_rov_am62px-sk_mcu-r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C kernel/rov/am62px-sk/mcu-r5fss0-0_freertos/ti-arm-clang -f makefile clean

 test_ipc_notify_am62px-sk_system_freertos_nortos_clean:
	$(MAKE) -C drivers/ipc_notify/am62px-sk/system_freertos_nortos -f makefile clean

 test_ipc_rpmsg_am62px-sk_system_freertos_clean:
	$(MAKE) -C drivers/ipc_rpmsg/am62px-sk/system_freertos -f makefile clean


BUILD_COMBO_EXAMPLE_SCRUB_ALL =
# Various Example Scrub Targets
BUILD_COMBO_EXAMPLE_SCRUB_ALL += dcc_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += dcc_func_test_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += sdl_ecc_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += ecc_ut_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_esm_func_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += esm_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_lbist_func_am62px-sk_wkup-r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_lbist_func_am62px-sk_wkup-r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += sdl_mcrc_auto_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += sdl_mcrc_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += sdl_mcrc_semi_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += mcrc_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += sdl_mtog_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += mtog_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += pbist_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += pbist_test_app_am62px-sk_mcu-r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += sdl_pbist_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += sdl_pbist_test_app_am62px-sk_mcu-r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += pok_func_test_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += pok_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += rom_checksum_func_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += rom_checksum_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += sdl_rti_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += rti_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += stog_func_test_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += tog_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += sdl_vtm_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += vtm_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_flash_am62px-sk_wkup-r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_led_am62px-sk_wkup-r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_gpio_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_gpio_am62px-sk_wkup-r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_gtc_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_mmcsd_am62px-sk_wkup-r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_sciclient_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_sciclient_am62px-sk_wkup-r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_i2c_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_i2c_am62px-sk_wkup-r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_ospi_am62px-sk_wkup-r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_uart_am62px-sk_mcu-r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_dpl_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_dpl_am62px-sk_mcu-r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_dpl_am62px-sk_wkup-r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_freertos_am62px-sk_mcu-r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_freertos_am62px-sk_wkup-r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_rov_am62px-sk_mcu-r5fss0-0_freertos_ti-arm-clang_scrub
# Various System Example Scrub Targets
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_ipc_notify_am62px-sk_system_freertos_nortos_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_ipc_rpmsg_am62px-sk_system_freertos_scrub

BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL =
# Various Private Example Targets
# Various Private System Example Targets

examples-scrub: $(BUILD_COMBO_EXAMPLE_SCRUB_ALL)

examples-scrub-private: $(BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL)

 dcc_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C sdl/dcc/dcc_unit_test/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 dcc_func_test_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C sdl/dcc/dcc_func_test/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 sdl_ecc_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C sdl/ecc/ecc_sdl_funcTest/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 ecc_ut_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C sdl/ecc/ecc_sdl_unitTest/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 test_esm_func_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C sdl/esm/esm_func_test/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 esm_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C sdl/esm/esm_unit_test/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 test_lbist_func_am62px-sk_wkup-r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C sdl/lbist/am62px-sk/wkup-r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 test_lbist_func_am62px-sk_wkup-r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C sdl/lbist/am62px-sk/wkup-r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 sdl_mcrc_auto_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C sdl/mcrc/mcrcAutomodeTest/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 sdl_mcrc_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C sdl/mcrc/mcrcFuncTest/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 sdl_mcrc_semi_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C sdl/mcrc/mcrcSemimodeTest/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 mcrc_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C sdl/mcrc/mcrcUt/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 sdl_mtog_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C sdl/mtog/mtog_functest/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 mtog_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C sdl/mtog/mtog_unit_test/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 pbist_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C sdl/pbist/ip_pbist_test/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 pbist_test_app_am62px-sk_mcu-r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C sdl/pbist/ip_pbist_test/am62px-sk/mcu-r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 sdl_pbist_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C sdl/pbist/sdl_pbist_test/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 sdl_pbist_test_app_am62px-sk_mcu-r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C sdl/pbist/sdl_pbist_test/am62px-sk/mcu-r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 pok_func_test_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C sdl/pok/pokFuncTest/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 pok_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C sdl/pok/pokUt/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 rom_checksum_func_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C sdl/rom_checksum/functional_test/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 rom_checksum_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C sdl/rom_checksum/unit_test/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 sdl_rti_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C sdl/rti/rtiFuncTest/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 rti_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C sdl/rti/rtiUt/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 stog_func_test_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C sdl/stog/stog_func_test/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 tog_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C sdl/stog/stog_unit_test/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 sdl_vtm_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C sdl/vtm/vtm_func_test/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 vtm_test_app_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C sdl/vtm/vtm_unit_test/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 test_flash_am62px-sk_wkup-r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C board/flash/am62px-sk/wkup-r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 test_led_am62px-sk_wkup-r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C board/led/am62px-sk/wkup-r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 sbl_ospi_linux_stage1_ddr_ecc_am62px-sk_wkup-r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C drivers/boot/sbl_ospi_linux_multistage_ddr_ecc/sbl_ospi_linux_stage1/am62px-sk/wkup-r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 test_ddr_am62px-sk_wkup-r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C drivers/ddr/am62px-sk/wkup-r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 test_gpio_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C drivers/gpio/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 test_gpio_am62px-sk_wkup-r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C drivers/gpio/am62px-sk/wkup-r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 test_gtc_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C drivers/gtc/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 test_mmcsd_am62px-sk_wkup-r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C drivers/mmcsd/am62px-sk/wkup-r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 test_sciclient_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C drivers/sciclient/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 test_sciclient_am62px-sk_wkup-r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C drivers/sciclient/am62px-sk/wkup-r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 test_i2c_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C drivers/i2c/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 test_i2c_am62px-sk_wkup-r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C drivers/i2c/am62px-sk/wkup-r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 test_ospi_am62px-sk_wkup-r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C drivers/ospi/am62px-sk/wkup-r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 test_uart_am62px-sk_mcu-r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C drivers/uart/am62px-sk/mcu-r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 test_dpl_am62px-sk_mcu-r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C kernel/dpl/am62px-sk/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 test_dpl_am62px-sk_mcu-r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C kernel/dpl/am62px-sk/mcu-r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 test_dpl_am62px-sk_wkup-r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C kernel/dpl/am62px-sk/wkup-r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 test_freertos_am62px-sk_mcu-r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C kernel/freertos/am62px-sk/mcu-r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 test_freertos_am62px-sk_wkup-r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C kernel/freertos/am62px-sk/wkup-r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 test_rov_am62px-sk_mcu-r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C kernel/rov/am62px-sk/mcu-r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 test_ipc_notify_am62px-sk_system_freertos_nortos_scrub:
	$(MAKE) -C drivers/ipc_notify/am62px-sk/system_freertos_nortos -f makefile scrub

 test_ipc_rpmsg_am62px-sk_system_freertos_scrub:
	$(MAKE) -C drivers/ipc_rpmsg/am62px-sk/system_freertos -f makefile scrub


sbl: libs
	$(MAKE) -C drivers/boot/sbl_ospi_linux_multistage_ddr_ecc/sbl_ospi_linux_stage1/am62px-sk/wkup-r5fss0-0_nortos/ti-arm-clang -f makefile all
	$(MAKE) -C drivers/ddr/am62px-sk/wkup-r5fss0-0_nortos/ti-arm-clang -f makefile all

sbl-clean:
	$(MAKE) -C drivers/boot/sbl_ospi_linux_multistage_ddr_ecc/sbl_ospi_linux_stage1/am62px-sk/wkup-r5fss0-0_nortos/ti-arm-clang -f makefile clean
	$(MAKE) -C drivers/ddr/am62px-sk/wkup-r5fss0-0_nortos/ti-arm-clang -f makefile clean

sbl-scrub:
	$(MAKE) -C drivers/boot/sbl_ospi_linux_multistage_ddr_ecc/sbl_ospi_linux_stage1/am62px-sk/wkup-r5fss0-0_nortos/ti-arm-clang -f makefile scrub
	$(MAKE) -C drivers/ddr/am62px-sk/wkup-r5fss0-0_nortos/ti-arm-clang -f makefile scrub



.PHONY: all clean scrub help
.PHONY: libs libs-clean libs-scrub
.PHONY: libs-private
.PHONY: libs-prebuilt libs-prebuilt-clean libs-prebuilt-scrub
.PHONY: examples examples-clean examples-scrub
.PHONY: examples-private examples-private-clean examples-private-scrub
.PHONY: sbl sbl-clean sbl-scrub
.PHONY: $(BUILD_COMBO_ALL) $(BUILD_COMBO_CLEAN_ALL) $(BUILD_COMBO_SCRUB_ALL)
.PHONY: $(BUILD_COMBO_EXAMPLE_ALL) $(BUILD_COMBO_EXAMPLE_CLEAN_ALL) $(BUILD_COMBO_EXAMPLE_SCRUB_ALL)
.PHONY: $(BUILD_COMBO_EXAMPLE_PRIVATE_ALL) $(BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL) $(BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL)
