let path = require('path');

let device = "am275x";

const files_r5f = {
    common: [
        "aasrc.c",
        "aasrc_ch.c",
        "aasrc_clocking.c",
        "aasrc_dma.c",
        "aasrc_intr.c",
        "aasrc_soc.c",
        "aasrc_transactions.c",
        "adc.c",
        "csl_bcdma.c",
        "csl_dru.c",
        "csl_intaggr.c",
        "csl_lcdma_ringacc.c",
        "csl_pktdma.c",
        "csl_sec_proxy.c",
        "ecap.c",
        "epwm.c",
        "flc.c",
        "gpio.c",
        "gtc.c",
        "gtc_soc.c",
        "hyperbus_soc.c",
        "hyperbus_v0.c",
        "i2c_v0.c",
        "i2c_v0_lld.c",
        "i2c_soc.c",
        "ipc_notify_v0.c",
        "ipc_notify_v0_cfg.c",
        "ipc_rpmsg.c",
        "ipc_rpmsg_vring.c",
        "mcasp.c",
        "mcasp_dma.c",
        "mcasp_soc.c",
        "mcan.c",
        "mmcsd_v0.c",
        "mmcsd_priv.c",
        "mmcsd_soc.c",
        "mcspi_v0.c",
        "mcspi_dma.c",
        "mcspi_dma_udma.c",
        "ospi_v0.c",
        "ospi_dma.c",
        "ospi_dma_udma.c",
        "ospi_nor_flash.c",
        "ospi_phy.c",
        "ospi_phy_tuning.c",
        "pinmux.c",
	    "pmu.c",
        "rl2.c",
        "rtc.c",
        "rtc_soc.c",
        "sciclient.c",
        "sciclient_lpm.c",
        "sciclient_pm.c",
        "sciclient_rm.c",
        "sciclient_rm_irq.c",
        "sciclient_procboot.c",
        "sciclient_firewall.c",
        "sciclient_irq_rm.c",
        "sciclient_fmwSecureProxyMap.c",
        "sciclient_soc_priv.c",
        "spinlock.c",
        "soc.c",
        "uart_v0.c",
        "uart_dma.c",
        "uart_dma_udma.c",
        "udma.c",
        "udma_ch.c",
        "udma_event.c",
        "udma_flow.c",
        "udma_ring_common.c",
        "udma_ring_lcdma.c",
        "udma_rm.c",
        "udma_rmcfg_common.c",
        "udma_utils.c",
        "udma_rmcfg.c",
        "udma_soc.c",
        "utils.c",
        "vtm.c",
        "watchdog_rti.c",
        "watchdog_soc.c",
    ],
};

const files_wkup_r5f = {
    common: [
        "bootloader.c",
        "bootloader_dma.c",
        "bootloader_flash.c",
        "bootloader_mcelf.c",
        "bootloader_mem.c",
        "bootloader_mmcsd_raw.c",
        "bootloader_profile.c",
        "bootloader_sd.c",
        "bootloader_soc.c",
        "bootloader_uart.c",
        "bootloader_uniflash.c",
        "bootloader_xmodem.c",
        "crc16.c",
        "csl_bcdma.c",
        "csl_dru.c",
        "csl_intaggr.c",
        "csl_lcdma_ringacc.c",
        "csl_pktdma.c",
        "csl_sec_proxy.c",
        "gpio.c",
        "gtc.c",
        "gtc_soc.c",
        "hyperbus_soc.c",
        "hyperbus_v0.c",
        "i2c_v0.c",
        "i2c_v0_lld.c",
        "i2c_soc.c",
        "ipc_notify_v0.c",
        "ipc_notify_v0_cfg.c",
        "ipc_rpmsg.c",
        "ipc_rpmsg_vring.c",
        "mcspi_v0.c",
        "mcspi_dma.c",
        "mcspi_dma_udma.c",
        "mmcsd_v0.c",
        "mmcsd_priv.c",
        "mmcsd_soc.c",
        "ospi_v0.c",
        "ospi_dma.c",
        "ospi_dma_udma.c",
        "ospi_nor_flash.c",
        "ospi_phy.c",
        "ospi_phy_tuning.c",
        "pinmux.c",
	    "pmu.c",
        "qos.c",
        "soc.c",
        "sciclient_irq_rm.c",
        "sciclient_fmwSecureProxyMap.c",
        "sciclient_soc_priv.c",
        "sysfw_hs_fs_signed.c",
        "sciclient_defaultBoardcfg.c",
        "tielfup32.c",
        "uart_v0.c",
        "uart_dma.c",
        "udma.c",
        "udma_ch.c",
        "udma_event.c",
        "udma_flow.c",
        "udma_ring_common.c",
        "udma_ring_lcdma.c",
        "udma_rm.c",
        "udma_rmcfg_common.c",
        "udma_utils.c",
        "udma_rmcfg.c",
        "udma_soc.c",
        "utils.c",
        "vtm.c",
        "watchdog_rti.c",
        "watchdog_soc.c",
        "xmodem.c",
    ]
};

const files_c75 = {
    common: [
        "aasrc.c",
        "aasrc_ch.c",
        "aasrc_clocking.c",
        "aasrc_dma.c",
        "aasrc_intr.c",
        "aasrc_soc.c",
        "aasrc_transactions.c",
        "csl_sec_proxy.c",
        "ecap.c",
        "epwm.c",
        "gpio.c",
        "gtc.c",
        "gtc_soc.c",
        "hyperbus_soc.c",
        "hyperbus_v0.c",
        "i2c_v0.c",
        "i2c_v0_lld.c",
        "i2c_soc.c",
        "ipc_notify_v0.c",
        "ipc_notify_v0_cfg.c",
        "ipc_rpmsg.c",
        "ipc_rpmsg_vring.c",
        "mcasp.c",
        "mcasp_dma.c",
        "mcasp_soc.c",
        "mcspi_v0.c",
        "mcspi_dma.c",
        "mcspi_dma_udma.c",
        "mmcsd_v0.c",
        "mmcsd_priv.c",
        "mmcsd_soc.c",
        "ospi_v0.c",
        "ospi_dma.c",
        "ospi_dma_udma.c",
        "ospi_nor_flash.c",
        "ospi_phy.c",
        "ospi_phy_tuning.c",
        "pinmux.c",
        "sciclient.c",
        "sciclient_pm.c",
        "sciclient_rm.c",
        "sciclient_rm_irq.c",
        "sciclient_procboot.c",
        "sciclient_firewall.c",
        "sciclient_irq_rm.c",
        "sciclient_fmwSecureProxyMap.c",
        "sciclient_soc_priv.c",
        "spinlock.c",
        "soc.c",
        "uart_v0.c",
        "uart_dma.c",
        "uart_dma_udma.c",
        "utils.c",
        "vtm.c",
        "watchdog_rti.c",
        "watchdog_soc.c",
    ],
};

const filedirs_common = {
    common: [
        "adc/v0",
        "aasrc/v0",
        "aasrc/v0/soc/am275x",
        "ecap/v0",
        "epwm/v0",
        "gpio/v0",
        "gtc/v0",
        'gtc/v0/soc/am275x',
        "hw_include/dru/v2/",
        "hw_include/ringacc/V0/priv/",
        "hyperbus/v0",
        "hyperbus/v0/soc/am275x",
        "i2c/v0",
        "i2c/v0/lld",
        "i2c/v0/soc/am275x",
        "ipc_notify/v0",
        "ipc_notify/v0/soc/am275x",
        "ipc_rpmsg/",
        "mcan/v0",
        "mcasp/v1",
        "mcasp/v1/dma_priv",
        "mcasp/v1/soc/am275x",
        "mcspi/v0",
        "mcspi/v0/dma",
        "mcspi/v0/dma/udma",
        "mmcsd",
        "mmcsd/v0",
        "mmcsd/soc",
        "mmcsd/soc/am275x",
        "optiflash/v0/flc",
        "optiflash/v0/rl2",
        "ospi",
        "ospi/v0",
        "ospi/v0/dma",
        "ospi/v0/dma/udma",
        "ospi/v0/ospi_tuning/ospi_tuning_algo/algo_v1",
        "pinmux/am275x",
        "pmu",
        "rtc",
        "rtc/v0",
        "rtc/v0/soc/am275x",
        "sciclient",
        "sciclient/soc/am275x",
        "spinlock/v0",
        "soc/am275x",
        "uart/v0",
        "uart/v0/dma",
        "uart/v0/dma/udma",
        "udma/v0",
        "udma/v0/hw_include",
        "udma/v0/soc",
        "udma/v0/soc/am275x",
        "utils",
        "watchdog/v1",
        `watchdog/v1/soc/am275x`,
    ],
};

const filedirs_wkup_r5f = {
    common: [
        "bootloader/soc/am275x",
        "bootloader/tiELFuParser",
        "bootloader",
        "gpio/v0",
        "gtc/v0",
        'gtc/v0/soc/am275x',
        "hw_include/dru/v2/",
        "hw_include/ringacc/V0/priv/",
        "hyperbus/v0",
        "hyperbus/v0/soc/am275x",
        "i2c/v0",
        "i2c/v0/lld",
        "i2c/v0/soc/am275x",
        "ipc_notify/v0",
        "ipc_notify/v0/soc/am275x",
        "ipc_rpmsg/",
        "mcan/v0",
        "mcasp/v1",
        "mcasp/v1/dma_priv",
        "mcasp/v1/soc/am275x",
        "mcspi/v0",
        "mcspi/v0/dma",
        "mcspi/v0/dma/udma",
        "mmcsd",
        "mmcsd/v0",
        "mmcsd/soc",
        "mmcsd/soc/am275x",
        "ospi",
        "ospi/v0",
        "ospi/v0/dma",
        "ospi/v0/dma/udma",
        "ospi/v0/ospi_tuning/ospi_tuning_algo/algo_v1",
        "pinmux/am275x",
        "pmu",
        "qos",
        "qos/v0",
        "sciclient",
        "sciclient/soc/am275x",
        "sciclient/sciclient_default_boardcfg/am275x",
        "soc/am275x",
        "uart/v0",
        "uart/v0/dma",
        "uart/v0/dma/udma",
        "udma/v0",
        "udma/v0/hw_include",
        "udma/v0/soc",
        "udma/v0/soc/am275x",
        "utils",
        "watchdog/v1",
        `watchdog/v1/soc/am275x`,
    ],
};

const filedirs_c75   = {
    common: [
        "aasrc/v0",
        "aasrc/v0/soc/am275x",
        "ecap/v0",
        "epwm/v0",
        "gpio/v0",
        "gtc/v0",
        'gtc/v0/soc/am275x',
        "hw_include/dru/v2/",
        "hw_include/ringacc/V0/priv/",
        "hyperbus/v0",
        "hyperbus/v0/soc/am275x",
        "i2c/v0",
        "i2c/v0/lld",
        "i2c/v0/soc/am275x",
        "ipc_notify/v0",
        "ipc_notify/v0/soc/am275x",
        "ipc_rpmsg/",
        "mcasp/v1",
        "mcasp/v1/dma_priv",
        "mcasp/v1/soc/am275x",
        "mcspi/v0",
        "mcspi/v0/dma",
        "mcspi/v0/dma/udma",
        "mmcsd",
        "mmcsd/v0",
        "mmcsd/soc",
        "mmcsd/soc/am275x",
        "ospi",
        "ospi/v0",
        "ospi/v0/dma",
        "ospi/v0/dma/udma",
        "ospi/v0/ospi_tuning/ospi_tuning_algo/algo_v1",
        "pinmux/am275x",
        "sciclient",
        "sciclient/soc/am275x",
        "spinlock/v0",
        "soc/am275x",
        "uart/v0",
        "uart/v0/dma",
        "uart/v0/dma/udma",
        "udma/v0",
        "udma/v0/hw_include",
        "udma/v0/soc",
        "udma/v0/soc/am275x",
        "utils",
        "watchdog/v1",
        `watchdog/v1/soc/am275x`,
    ],
};

const defines_wkup_r5 = {
    common: [
        "ENABLE_SCICLIENT_DIRECT",
        "ENABLE_PHY_TUNING_SOC_BUILD",
    ],
};

const defines_r5 = {
    common: [
        "MCU_R5",
        "ENABLE_PHY_TUNING_SOC_BUILD",
        "SCICLIENT_INTERRUPT_MODE",
    ],
};

const defines_c7x = {
    common: [
        "ENABLE_PHY_TUNING_SOC_BUILD",
        "SCICLIENT_INTERRUPT_MODE",
    ],
};

const includes_wkup_r5f = {
    common: [
        "${MCU_PLUS_SDK_PATH}/source/fs/freertos_fat/FreeRTOS-FAT/include",
        "${MCU_PLUS_SDK_PATH}/source/fs/freertos_fat/portable",
        "${MCU_PLUS_SDK_PATH}/source/fs/freertos_fat/portable/nortos",
        "${MCU_PLUS_SDK_PATH}/source/fs/freertos_fat/config",
    ],
};

const buildOptionCombos = [
    { device: device, cpu: "r5f", cgt: "ti-arm-clang"},
    { device: device, cpu: "wkup-r5f", cgt: "ti-arm-clang"},
    { device: device, cpu: "c75x", cgt: "ti-c7000"},
];

function getComponentProperty() {
    let property = {};

    property.dirPath = path.resolve(__dirname, "..");
    property.type = "library";
    property.name = "drivers";
    property.isInternal = false;
    property.buildOptionCombos = buildOptionCombos;

    return property;
}

function getComponentBuildProperty(buildOption) {
    let build_property = {};

    build_property.filedirs = filedirs_common;

    if(buildOption.cpu.match(/wkup-r5f*/)) {
        build_property.filedirs = filedirs_wkup_r5f;
        build_property.files = files_wkup_r5f;
        build_property.includes = includes_wkup_r5f;
        build_property.defines = defines_wkup_r5;
    }else if(buildOption.cpu.match(/r5f*/)) {
        build_property.files = files_r5f;
        build_property.defines = defines_r5;
    }else if(buildOption.cpu.match(/c75*/)) {
        build_property.filedirs = filedirs_c75;
        build_property.files = files_c75;
        build_property.defines = defines_c7x;
    }
    return build_property;
}

module.exports = {
    getComponentProperty,
    getComponentBuildProperty,
};
