let path = require('path');

let device = "am62ax";

const files_mcu_r5f = {
    common: [
        "csl_dru.c",
        "csl_emif.c",
        "csl_sec_proxy.c",
        "csl_bcdma.c",
        "csl_intaggr.c",
        "csl_lcdma_ringacc.c",
        "csl_pktdma.c",
        "ddr.c",
        "ddr_soc.c",
        "gpio.c",
        "gtc.c",
        "gtc_soc.c",
        "i2c_v0.c",
        "i2c_v0_lld.c",
        "i2c_soc.c",
        "ipc_notify_v0.c",
        "ipc_notify_v0_cfg.c",
        "ipc_rpmsg.c",
        "ipc_rpmsg_vring.c",
        "mcan.c",
        "mcspi_v0.c",
        "mcspi_dma.c",
        "mcspi_dma_udma.c",
        "pinmux.c",
        "ospi_v0.c",
        "ospi_dma.c",
        "ospi_dma_udma.c",
        "ospi_nor_flash.c",
        "ospi_phy.c",
        "ospi_phy_tuning.c",
	    "pmu.c",
        "rtc.c",
        "rtc_soc.c",
        "sciclient.c",
        "sciclient_lpm.c",
        "sciclient_pm.c",
        "sciclient_rm.c",
        "sciclient_rm_irq.c",
        "sciclient_procboot.c",
        "sciclient_firewall.c",
        "sciclient_irq_rm.c",
        "sciclient_fmwSecureProxyMap.c",
        "sciclient_soc_priv.c",
        "soc.c",
        "uart_v0.c",
        "uart_dma.c",
        "udma.c",
        "udma_ch.c",
        "udma_event.c",
        "udma_flow.c",
        "udma_ring_common.c",
        "udma_ring_lcdma.c",
        "udma_rm.c",
        "udma_rmcfg_common.c",
        "udma_utils.c",
        "udma_rmcfg.c",
        "udma_soc.c",
        "utils.c",
        "vtm.c",
    ],
};

const files_r5f = {
    common: [
        "bootloader.c",
        "bootloader_dma.c",
        "bootloader_flash.c",
        "bootloader_mem.c",
        "bootloader_mmcsd_raw.c",
        "bootloader_rprc.c",
        "bootloader_soc.c",
        "bootloader_xmodem.c",
        "bootloader_uniflash.c",
        "bootloader_profile.c",
        "csl_sec_proxy.c",
        "csl_emif.c",
        "csl_bcdma.c",
        "csl_dru.c",
        "csl_intaggr.c",
        "csl_lcdma_ringacc.c",
        "csl_pktdma.c",
        "crc16.c",
        "csl_ringacc.c",
        "ddr.c",
        "ddr_soc.c",
        "ddr_perf.c",
        "ecap.c",
        "epwm.c",
        "eqep.c",
        "fvid2_drvMgr.c",
        "fvid2_graph.c",
        "fvid2_utils.c",
        "fvid2_trace.c",
        "gpio.c",
        "gtc.c",
        "gtc_soc.c",
        "i2c_v0.c",
        "i2c_v0_lld.c",
        "i2c_soc.c",
        "ipc_notify_v0.c",
        "ipc_notify_v0_cfg.c",
        "ipc_rpmsg.c",
        "ipc_rpmsg_vring.c",
        "lpddr4_obj_if.c",
        "lpddr4.c",
        "lpddr4_am6x.c",
        "lpddr4_ctl_regs_rw_masks.c",
        "mcasp.c",
        "mcasp_dma.c",
        "mcasp_soc.c",
        "mcspi_v0.c",
        "mcspi_dma.c",
        "mcspi_dma_udma.c",
        "mmcsd_v0.c",
        "mmcsd_priv.c",
        "mmcsd_soc.c",
        "ospi_v0.c",
        "ospi_dma.c",
        "ospi_dma_udma.c",
        "ospi_nor_flash.c",
        "ospi_phy.c",
        "ospi_phy_tuning.c",
        "pinmux.c",
	    "pmu.c",
        "qos.c",
        "rtc.c",
        "rtc_soc.c",
        "soc.c",
        "sciclient_irq_rm.c",
        "sciclient_fmwSecureProxyMap.c",
        "uart_v0.c",
        "uart_dma.c",
        "udma.c",
        "udma_ch.c",
        "udma_event.c",
        "udma_flow.c",
        "udma_ring_common.c",
        "udma_ring_lcdma.c",
        "udma_rm.c",
        "udma_rmcfg_common.c",
        "udma_utils.c",
        "udma_rmcfg.c",
        "udma_soc.c",
        "utils.c",
        "vtm.c",
        "xmodem.c",
        "csirx_sanity.c",
        "csirx_ss.c",
        "csirx.c",
        "csirx_soc.c",
        "csirx_drv.c",
        "csirx_drvInit.c",
        "csirx_drvUdma.c",
        "csirx_event.c",
    ]
};

const files_c75 = {
    common: [
        "csl_dru.c",
        "csl_sec_proxy.c",
        "csl_emif.c",
        "csl_bcdma.c",
        "csl_dru.c",
        "csl_intaggr.c",
        "csl_lcdma_ringacc.c",
        "csl_pktdma.c",
        "ecap.c",
        "epwm.c",
        "eqep.c",
        "gpio.c",
        "i2c_v0.c",
        "i2c_v0_lld.c",
        "i2c_soc.c",
        "ipc_notify_v0.c",
        "ipc_notify_v0_cfg.c",
        "ipc_rpmsg.c",
        "ipc_rpmsg_vring.c",
        "mcasp.c",
        "mcasp_dma.c",
        "mcasp_soc.c",
        "pinmux.c",
        "sciclient.c",
        "sciclient_lpm.c",
        "sciclient_pm.c",
        "sciclient_rm.c",
        "sciclient_rm_irq.c",
        "sciclient_procboot.c",
        "sciclient_firewall.c",
        "sciclient_irq_rm.c",
        "sciclient_fmwSecureProxyMap.c",
        "sciclient_soc_priv.c",
        "soc.c",
        "uart_v0.c",
        "uart_dma.c",
        "utils.c",
        "udma.c",
        "udma_ch.c",
        "udma_event.c",
        "udma_flow.c",
        "udma_ring_common.c",
        "udma_ring_lcdma.c",
        "udma_rm.c",
        "udma_rmcfg_common.c",
        "udma_utils.c",
        "udma_rmcfg.c",
        "udma_soc.c",
    ],
};

/*
 * a53 support for am62ax
 */
const files_a53 = {
    common: [
        "ecap.c",
        "epwm.c",
        "csl_sec_proxy.c",
        "csl_bcdma.c",
        "csl_dru.c",
        "csl_intaggr.c",
        "csl_lcdma_ringacc.c",
        "csl_pktdma.c",
        "epwm.c",
        "eqep.c",
        "gpio.c",
        "gtc.c",
        "gtc_soc.c",
        "i2c_v0.c",
        "i2c_v0_lld.c",
        "i2c_soc.c",
        "ipc_notify_v0.c",
        "ipc_notify_v0_cfg.c",
        "ipc_rpmsg.c",
        "ipc_rpmsg_vring.c",
        "mcan.c",
        "mcasp.c",
        "mcasp_dma.c",
        "mcasp_soc.c",
        "mcspi_v0.c",
        "mcspi_dma.c",
        "mcspi_dma_udma.c",
        "mmcsd_v0.c",
        "mmcsd_priv.c",
        "mmcsd_soc.c",
        "ospi_v0.c",
        "ospi_dma.c",
        "ospi_dma_udma.c",
        "ospi_nor_flash.c",
        "ospi_phy.c",
        "ospi_phy_tuning.c",
        "pinmux.c",
        "sciclient.c",
        "sciclient_pm.c",
        "sciclient_rm.c",
        "sciclient_rm_irq.c",
        "sciclient_procboot.c",
        "sciclient_firewall.c",
        "sciclient_irq_rm.c",
        "sciclient_fmwSecureProxyMap.c",
        "sciclient_soc_priv.c",
        "soc.c",
        "uart_v0.c",
        "uart_dma.c",
        "uart_dma_udma.c",
        "udma.c",
        "udma_ch.c",
        "udma_event.c",
        "udma_flow.c",
        "udma_ring_common.c",
        "udma_ring_lcdma.c",
        "udma_rm.c",
        "udma_rmcfg_common.c",
        "udma_utils.c",
        "udma_rmcfg.c",
        "udma_soc.c",
        "utils.c",
        "vtm.c",
        "watchdog_rti.c",
        "watchdog_soc.c",
        ],
};

const filedirs = {
    common: [
        "bootloader",
        `bootloader/soc/am62ax`,
        "ddr/v1",
        "ddr/cdn_drv/",
        "ddr/cdn_drv/common/include",
        "ddr/cdn_drv/v1/include",
        "ddr/cdn_drv/common",
        "ddr/cdn_drv/v1",
        "ddr",
        "ddr/v1/soc/am62ax",
        "ecap/v0",
        "epwm/v0",
        "eqep/v0",
        "fvid2/v0",
        "gpio/v0",
        "gtc/v0",
        'gtc/v0/soc/am62ax',
        "hw_include/dru/v2/",
        "hw_include/ringacc/V0/priv/",
        "i2c/v0",
        "i2c/v0/lld",
        "i2c/v0/soc/am62ax",
        "ipc_notify/v0",
        "ipc_notify/v0/soc/am62ax",
        "ipc_rpmsg/",
        "mcan/v0",
        "mcasp/v1",
        "mcasp/v1/dma_priv",
        "mcasp/v1/soc/am62ax",
        "mcspi/v0",
        "mcspi/v0/dma",
        "mcspi/v0/dma/udma",
        "mmcsd",
        "mmcsd/v0",
        "mmcsd/soc",
        "mmcsd/soc/am62ax",
        "ospi",
        "ospi/v0",
        "ospi/v0/dma",
        "ospi/v0/dma/udma",
        "ospi/v0/ospi_tuning/ospi_tuning_algo/algo_v1",
        "pmu",
        "qos",
        "qos/v0",
        "pinmux/am62ax",
        "rtc",
        "rtc/v0",
        "rtc/v0/soc/am62ax",
        "sciclient",
        "sciclient/soc/am62ax",
        `soc/am62ax`,
        "soc/am62ax",
        "uart/v0",
        "uart/v0/dma",
        "uart/v0/dma/udma",
        "udma/v0",
        "udma/v0/hw_include",
        "udma/v0/soc",
        "udma/v0/soc/am62ax",
        "soc/am62ax",
        "utils",
        "csirx/v0/hw_include",
        "csirx/v0/soc/am62ax",
        "csirx/v0/src",
        "csirx/v0",
        "csirx/v0/include",
    ],
};

const defines_dm_r5 = {
    common: [
        "ENABLE_SCICLIENT_DIRECT",
        "FVID2_CFG_TRACE_ENABLE",
        "FVID2_CFG_ASSERT_ENABLE",
        "ENABLE_PHY_TUNING_SOC_BUILD",
    ],
};

const defines_r5 = {
    common: [
        "MCU_R5",
        "ENABLE_PHY_TUNING_SOC_BUILD",
    ],
};

const defines_a53 = {
    common: [
        "ENABLE_PHY_TUNING_SOC_BUILD",
    ],
};

const cflags_dm_r5 = {
    debug: []
}

const filedirs_a53 =  {
    common: [
        "ecap/v0",
        "epwm/v0",
        "eqep/v0",
        "gpio/v0",
        "gtc/v0",
        'gtc/v0/soc/am62ax',
        "hw_include/dru/v2/",
        "i2c/v0",
        "i2c/v0/lld",
        "i2c/v0/soc/am62ax",
        "ipc_notify/v0",
        `ipc_notify/v0/soc/${device}`,
        "ipc_rpmsg/",
        "mcspi/v0",
        "mcspi/v0/dma",
        "mcspi/v0/dma/udma",
        "mcan/v0",
        "mcasp/v1",
        "mcasp/v1/dma_priv",
        "mcasp/v1/soc/am62ax",
        "mmcsd",
        "mmcsd/v0",
        "mmcsd/soc",
        "mmcsd/soc/am62ax",
        "ospi",
        "ospi/v0",
        "ospi/v0/dma",
        "ospi/v0/dma/udma",
        "ospi/v0/ospi_tuning/ospi_tuning_algo/algo_v1",
        "pinmux/am62ax",
        "pinmux/am62ax",
        "sciclient",
        "sciclient/soc/am62ax",
        "soc/am62ax",
        "uart/v0",
        "uart/v0/dma",
        "uart/v0/dma/udma",
        "udma/v0",
        "udma/v0/hw_include",
        "udma/v0/soc",
        "udma/v0/soc/am62ax",
        "utils",
        "watchdog/v1",
        `watchdog/v1/soc/am62ax`,
    ],
};

const buildOptionCombos = [
    { device: device, cpu: "r5f", cgt: "ti-arm-clang"},
    { device: device, cpu: "dm-r5f", cgt: "ti-arm-clang"},
    { device: device, cpu: "c75x", cgt: "ti-c7000"},
    { device: device, cpu: "a53", cgt: "gcc-aarch64"},
];

function getComponentProperty() {
    let property = {};

    property.dirPath = path.resolve(__dirname, "..");
    property.type = "library";
    property.name = "drivers";
    property.isInternal = false;
    property.buildOptionCombos = buildOptionCombos;

    return property;
}

function getComponentBuildProperty(buildOption) {
    let build_property = {};

    build_property.filedirs = filedirs;

    if(buildOption.cpu.match(/dm-r5f*/)) {
        build_property.files = files_r5f;
        build_property.defines = defines_dm_r5;
        build_property.cflags = cflags_dm_r5;
    }else if(buildOption.cpu.match(/r5f*/)) {
        build_property.files = files_mcu_r5f;
        build_property.defines = defines_r5;
    }else if(buildOption.cpu.match(/c75*/)) {
        build_property.files = files_c75;
    }else if(buildOption.cpu.match(/a53*/)) {
        build_property.filedirs = filedirs_a53;
        build_property.files = files_a53;
        build_property.defines = defines_a53;
    }

    return build_property;
}

module.exports = {
    getComponentProperty,
    getComponentBuildProperty,
};
