/********************************************************************
*
* GICSS0 INTERRUPT MAP. header file
*
* Copyright (C) 2015-2023 Texas Instruments Incorporated.
*  Redistribution and use in source and binary forms, with or without
*  modification, are permitted provided that the following conditions
*  are met:
*
*    Redistributions of source code must retain the above copyright
*    notice, this list of conditions and the following disclaimer.
*
*    Redistributions in binary form must reproduce the above copyright
*    notice, this list of conditions and the following disclaimer in the
*    documentation and/or other materials provided with the
*    distribution.
*
*    Neither the name of Texas Instruments Incorporated nor the names of
*    its contributors may be used to endorse or promote products derived
*    from this software without specific prior written permission.
*
*  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
*  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
*  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
*  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
*  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
*  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
*  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
*  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
*  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
*  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
*  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*
*/
#ifndef CSLR_GICSS0_INTERRUPT_MAP_H_
#define CSLR_GICSS0_INTERRUPT_MAP_H_

#include <drivers/hw_include/cslr.h>
#include <drivers/hw_include/tistdtypes.h>
#ifdef __cplusplus
extern "C"
{
#endif

/*
* List of intr sources for receiver: GICSS0
*/

#define CSLR_GICSS0_PPI0_1_COMPUTE_CLUSTER0_ARM_COREPACK_0_CTIIRQ0_0                               (17U)
#define CSLR_GICSS0_PPI0_0_COMPUTE_CLUSTER0_ARM_COREPACK_0_CTIIRQ1_0                               (18U)
#define CSLR_GICSS0_PPI0_0_COMPUTE_CLUSTER0_ARM_COREPACK_0_COMMIRQ0_0                              (22U)
#define CSLR_GICSS0_PPI0_1_COMPUTE_CLUSTER0_ARM_COREPACK_0_COMMIRQ1_0                              (22U)
#define CSLR_GICSS0_PPI0_0_COMPUTE_CLUSTER0_ARM_COREPACK_0_PMUIRQ0_0                               (23U)
#define CSLR_GICSS0_PPI0_1_COMPUTE_CLUSTER0_ARM_COREPACK_0_PMUIRQ1_0                               (23U)
#define CSLR_GICSS0_PPI0_0_COMPUTE_CLUSTER0_ARM_COREPACK_0_CTIIRQ0_0                               (24U)
#define CSLR_GICSS0_PPI0_1_COMPUTE_CLUSTER0_ARM_COREPACK_0_CTIIRQ1_0                               (24U)
#define CSLR_GICSS0_PPI0_0_COMPUTE_CLUSTER0_ARM_COREPACK_0_VCPUMNTIRQ0_0                           (25U)
#define CSLR_GICSS0_PPI0_1_COMPUTE_CLUSTER0_ARM_COREPACK_0_VCPUMNTIRQ1_0                           (25U)
#define CSLR_GICSS0_PPI0_0_COMPUTE_CLUSTER0_ARM_COREPACK_0_CNTHPIRQ0_0                             (26U)
#define CSLR_GICSS0_PPI0_1_COMPUTE_CLUSTER0_ARM_COREPACK_0_CNTHPIRQ1_0                             (26U)
#define CSLR_GICSS0_PPI0_0_COMPUTE_CLUSTER0_ARM_COREPACK_0_CNTVIRQ0_0                              (27U)
#define CSLR_GICSS0_PPI0_1_COMPUTE_CLUSTER0_ARM_COREPACK_0_CNTVIRQ1_0                              (27U)
#define CSLR_GICSS0_PPI0_0_COMPUTE_CLUSTER0_ARM_COREPACK_0_CNTPSIRQ0_0                             (29U)
#define CSLR_GICSS0_PPI0_1_COMPUTE_CLUSTER0_ARM_COREPACK_0_CNTPSIRQ1_0                             (29U)
#define CSLR_GICSS0_PPI0_0_COMPUTE_CLUSTER0_ARM_COREPACK_0_CNTPNSIRQ0_0                            (30U)
#define CSLR_GICSS0_PPI0_1_COMPUTE_CLUSTER0_ARM_COREPACK_0_CNTPNSIRQ1_0                            (30U)
#define CSLR_GICSS0_SPI_WKUP_SMS_LITE0_MAILBOX_0_MAILBOX_CLUSTER0_PEND_0                           (32U)
#define CSLR_GICSS0_SPI_WKUP_SMS_LITE0_MAILBOX_1_MAILBOX_CLUSTER1_PEND_0                           (33U)
#define CSLR_GICSS0_SPI_CTRL_MMR0_IPC_SET0_IPC_SET_IPCFG_0                                         (43U)
#define CSLR_GICSS0_SPI_COMPUTE_CLUSTER0_ARM_COREPACK_0_EXTERRIRQ_0                                (47U)
#define CSLR_GICSS0_SPI_DDR16SS0_DDRSS_CONTROLLER_0                                                (48U)
#define CSLR_GICSS0_SPI_DDR16SS0_DDRSS_PLL_FREQ_CHANGE_REQ_0                                       (49U)
#define CSLR_GICSS0_SPI_DDR16SS0_DDRSS_V2A_OTHER_ERR_LVL_0                                         (50U)
#define CSLR_GICSS0_SPI_WKUP_EFUSE0_EFC_ERROR_0                                                    (52U)
#define CSLR_GICSS0_SPI_GLUELOGIC_EFUSE_SCAN_GLUE_CRC_ERR_0                                        (53U)
#define CSLR_GICSS0_SPI_WKUP_VTM0_THERM_LVL_GT_TH1_INTR_0                                          (55U)
#define CSLR_GICSS0_SPI_WKUP_VTM0_THERM_LVL_GT_TH2_INTR_0                                          (56U)
#define CSLR_GICSS0_SPI_WKUP_VTM0_THERM_LVL_LT_TH0_INTR_0                                          (57U)
#define CSLR_GICSS0_SPI_GLUELOGIC_MAINRESET_REQUEST_GLUE_MAIN_RESETZ_SYNC_STRETCH_0                (59U)
#define CSLR_GICSS0_SPI_WKUP_RTCSS0_RTC_EVENT_PEND_0                                               (60U)
#define CSLR_GICSS0_SPI_RTI0_INTR_WWD_0                                                            (61U)
#define CSLR_GICSS0_SPI_RTI1_INTR_WWD_0                                                            (62U)
#define CSLR_GICSS0_SPI_DEBUGSS0_AQCMPINTR_LEVEL_0                                                 (65U)
#define CSLR_GICSS0_SPI_PSC0_PSC_ALLINT_0                                                          (67U)
#define CSLR_GICSS0_SPI_MCU_MCU0_VDD_CORE_GLDTC_STAT_THRESH_HI_FLAG_IPCFG_0                        (68U)
#define CSLR_GICSS0_SPI_MCU_MCU0_VDD_CORE_GLDTC_STAT_THRESH_LOW_FLAG_IPCFG_0                       (69U)
#define CSLR_GICSS0_SPI_GLUELOGIC_GLUE_EXT_INTN_OUT_0                                              (70U)
#define CSLR_GICSS0_SPI_WKUP_SMS_LITE0_COMMON_0_COMBINED_SEC_IN_0                                  (71U)
#define CSLR_GICSS0_SPI_WKUP_SMS_LITE0_TIFS_CHAN_CBASS_0_DEFAULT_EXCEPTION_PENDING_0               (72U)
#define CSLR_GICSS0_SPI_GLUELOGIC_SOC_CBASS_ERR_INTR_GLUE_AGGREGATED_CBASS_ERROR_0                 (74U)
#define CSLR_GICSS0_SPI_GLUELOGIC_AGGREGATED_MMRACCESS_ERR_OUT_0                                   (75U)
#define CSLR_GICSS0_SPI_GLUELOGIC_INTRGLUE_PBIST_CPU_MAIN_OUT_0                                    (76U)
#define CSLR_GICSS0_SPI_WKUP_PBIST0_DFT_PBIST_CPU_0                                                (77U)
#define CSLR_GICSS0_SPI_TRNG_DRBG_EIP76D_WRAP0_TRNG_0                                              (79U)
#define CSLR_GICSS0_SPI_WKUP_DMASS0_AES_P_0                                                        (80U)
#define CSLR_GICSS0_SPI_DMASS0_BCDMA_INTR_RX_AES_0                                                 (81U)
#define CSLR_GICSS0_SPI_DMASS0_BCDMA_INTR_TX_AES_0                                                 (82U)
#define CSLR_GICSS0_SPI_WKUP_DMASS0_SHA_P_0                                                        (83U)
#define CSLR_GICSS0_SPI_DMASS0_BCDMA_INTR_TX_SHA_0                                                 (84U)
#define CSLR_GICSS0_SPI_GICSS0_AXIM_ERR_0                                                          (85U)
#define CSLR_GICSS0_SPI_GICSS0_ECC_FATAL_0                                                         (86U)
#define CSLR_GICSS0_SPI_DSS_DSI0_DSI_0_FUNC_INTR_0                                                 (89U)
#define CSLR_GICSS0_SPI_DSS_DSI0_DSI_0_SAFETY_ERROR_FATAL_INTR_0                                   (90U)
#define CSLR_GICSS0_SPI_DSS_DSI0_DSI_0_SAFETY_ERROR_NONFATAL_INTR_0                                (91U)
#define CSLR_GICSS0_SPI_DSS0_DISPC_INTR_REQ_0_0                                                    (92U)
#define CSLR_GICSS0_SPI_DSS0_DISPC_INTR_REQ_1_0                                                    (93U)
#define CSLR_GICSS0_SPI_I2C0_POINTRPEND_0                                                          (96U)
#define CSLR_GICSS0_SPI_I2C1_POINTRPEND_0                                                          (97U)
#define CSLR_GICSS0_SPI_I2C2_POINTRPEND_0                                                          (98U)
#define CSLR_GICSS0_SPI_I2C3_POINTRPEND_0                                                          (99U)
#define CSLR_GICSS0_SPI_WKUP_I2C0_POINTRPEND_0                                                     (108U)
#define CSLR_GICSS0_SPI_MCSPI0_INTR_SPI_0                                                          (112U)
#define CSLR_GICSS0_SPI_MCSPI1_INTR_SPI_0                                                          (113U)
#define CSLR_GICSS0_SPI_MCSPI2_INTR_SPI_0                                                          (114U)
#define CSLR_GICSS0_SPI_MCSPI3_INTR_SPI_0                                                          (115U)
#define CSLR_GICSS0_SPI_UART0_USART_IRQ_0                                                          (128U)
#define CSLR_GICSS0_SPI_UART1_USART_IRQ_0                                                          (129U)
#define CSLR_GICSS0_SPI_UART2_USART_IRQ_0                                                          (130U)
#define CSLR_GICSS0_SPI_UART3_USART_IRQ_0                                                          (131U)
#define CSLR_GICSS0_SPI_UART4_USART_IRQ_0                                                          (132U)
#define CSLR_GICSS0_SPI_UART5_USART_IRQ_0                                                          (133U)
#define CSLR_GICSS0_SPI_UART6_USART_IRQ_0                                                          (134U)
#define CSLR_GICSS0_SPI_WKUP_UART0_USART_IRQ_0                                                     (140U)
#define CSLR_GICSS0_SPI_MCAN0_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                                     (144U)
#define CSLR_GICSS0_SPI_MCAN0_MCANSS_MCAN_LVL_INT_0                                                (145U)
#define CSLR_GICSS0_SPI_MCAN0_MCANSS_MCAN_LVL_INT_1                                                (146U)
#define CSLR_GICSS0_SPI_MCAN1_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                                     (147U)
#define CSLR_GICSS0_SPI_MCAN1_MCANSS_MCAN_LVL_INT_0                                                (148U)
#define CSLR_GICSS0_SPI_MCAN1_MCANSS_MCAN_LVL_INT_1                                                (149U)
#define CSLR_GICSS0_SPI_MCAN2_MCANSS_EXT_TS_ROLLOVER_LVL_INT_0                                     (150U)
#define CSLR_GICSS0_SPI_MCAN2_MCANSS_MCAN_LVL_INT_0                                                (151U)
#define CSLR_GICSS0_SPI_MCAN2_MCANSS_MCAN_LVL_INT_1                                                (152U)
#define CSLR_GICSS0_SPI_EPWM0_EPWM_ETINT_0                                                         (168U)
#define CSLR_GICSS0_SPI_EPWM0_EPWM_TRIPZINT_0                                                      (169U)
#define CSLR_GICSS0_SPI_EPWM1_EPWM_ETINT_0                                                         (170U)
#define CSLR_GICSS0_SPI_EPWM1_EPWM_TRIPZINT_0                                                      (171U)
#define CSLR_GICSS0_SPI_EPWM2_EPWM_ETINT_0                                                         (172U)
#define CSLR_GICSS0_SPI_EPWM2_EPWM_TRIPZINT_0                                                      (173U)
#define CSLR_GICSS0_SPI_ECAP0_ECAP_INT_0                                                           (186U)
#define CSLR_GICSS0_SPI_ECAP1_ECAP_INT_0                                                           (187U)
#define CSLR_GICSS0_SPI_ECAP2_ECAP_INT_0                                                           (188U)
#define CSLR_GICSS0_SPI_EQEP0_EQEP_INT_0                                                           (194U)
#define CSLR_GICSS0_SPI_EQEP1_EQEP_INT_0                                                           (195U)
#define CSLR_GICSS0_SPI_EQEP2_EQEP_INT_0                                                           (196U)
#define CSLR_GICSS0_SPI_TIMER0_INTR_PEND_0                                                         (202U)
#define CSLR_GICSS0_SPI_TIMER1_INTR_PEND_0                                                         (203U)
#define CSLR_GICSS0_SPI_TIMER2_INTR_PEND_0                                                         (204U)
#define CSLR_GICSS0_SPI_TIMER3_INTR_PEND_0                                                         (205U)
#define CSLR_GICSS0_SPI_WKUP_TIMER0_INTR_PEND_0                                                    (222U)
#define CSLR_GICSS0_SPI_WKUP_TIMER1_INTR_PEND_0                                                    (223U)
#define CSLR_GICSS0_SPI_PLLFRACF2_SSMOD0_LOCKLOSS_IPCFG_0                                          (226U)
#define CSLR_GICSS0_SPI_PLLFRACF2_SSMOD8_LOCKLOSS_IPCFG_0                                          (234U)
#define CSLR_GICSS0_SPI_PLLFRACF2_SSMOD17_LOCKLOSS_IPCFG_0                                         (243U)
#define CSLR_GICSS0_SPI_USB0_HOST_SYSTEM_ERROR_0                                                   (246U)
#define CSLR_GICSS0_SPI_USB0_IRQ_0                                                                 (247U)
#define CSLR_GICSS0_SPI_USB0_IRQ_1                                                                 (248U)
#define CSLR_GICSS0_SPI_USB0_IRQ_2                                                                 (249U)
#define CSLR_GICSS0_SPI_USB0_IRQ_3                                                                 (250U)
#define CSLR_GICSS0_SPI_USB0_IRQ_4                                                                 (251U)
#define CSLR_GICSS0_SPI_USB0_IRQ_5                                                                 (252U)
#define CSLR_GICSS0_SPI_USB0_IRQ_6                                                                 (253U)
#define CSLR_GICSS0_SPI_USB0_IRQ_7                                                                 (254U)
#define CSLR_GICSS0_SPI_USB0_MISC_LEVEL_0                                                          (255U)
#define CSLR_GICSS0_SPI_USB1_HOST_SYSTEM_ERROR_0                                                   (256U)
#define CSLR_GICSS0_SPI_USB1_IRQ_0                                                                 (257U)
#define CSLR_GICSS0_SPI_USB1_IRQ_1                                                                 (258U)
#define CSLR_GICSS0_SPI_USB1_IRQ_2                                                                 (259U)
#define CSLR_GICSS0_SPI_USB1_IRQ_3                                                                 (260U)
#define CSLR_GICSS0_SPI_USB1_IRQ_4                                                                 (261U)
#define CSLR_GICSS0_SPI_USB1_IRQ_5                                                                 (262U)
#define CSLR_GICSS0_SPI_USB1_IRQ_6                                                                 (263U)
#define CSLR_GICSS0_SPI_USB1_IRQ_7                                                                 (264U)
#define CSLR_GICSS0_SPI_USB1_MISC_LEVEL_0                                                          (265U)
#define CSLR_GICSS0_SPI_CPSW0_EVNT_PEND_0                                                          (266U)
#define CSLR_GICSS0_SPI_CPSW0_MDIO_PEND_0                                                          (267U)
#define CSLR_GICSS0_SPI_CPSW0_STAT_PEND_0                                                          (268U)
#define CSLR_GICSS0_SPI_MMCSD1_EMMCSDSS_INTR_0                                                     (269U)
#define CSLR_GICSS0_SPI_MMCSD2_EMMCSDSS_INTR_0                                                     (270U)
#define CSLR_GICSS0_SPI_MMCSD0_EMMCSDSS_INTR_0                                                     (271U)
#define CSLR_GICSS0_SPI_FSS0_OSPI0_LVL_INTR_0                                                      (272U)
#define CSLR_GICSS0_SPI_FSS0_FSAS_ECC_INTR_ERR_PEND_0                                              (273U)
#define CSLR_GICSS0_SPI_ELM0_ELM_POROCPSINTERRUPT_LVL_0                                            (275U)
#define CSLR_GICSS0_SPI_GPMC0_GPMC_SINTERRUPT_0                                                    (276U)
#define CSLR_GICSS0_SPI_MCASP0_REC_INTR_PEND_0                                                     (277U)
#define CSLR_GICSS0_SPI_MCASP0_XMIT_INTR_PEND_0                                                    (278U)
#define CSLR_GICSS0_SPI_MCASP1_REC_INTR_PEND_0                                                     (279U)
#define CSLR_GICSS0_SPI_MCASP1_XMIT_INTR_PEND_0                                                    (280U)
#define CSLR_GICSS0_SPI_MCASP2_REC_INTR_PEND_0                                                     (281U)
#define CSLR_GICSS0_SPI_MCASP2_XMIT_INTR_PEND_0                                                    (282U)
#define CSLR_GICSS0_SPI_ADC0_GEN_LEVEL_0                                                           (285U)
#define CSLR_GICSS0_SPI_CPSW0_CPTS_COMP_0                                                          (287U)
#define CSLR_GICSS0_SPI_GPIO0_GPIO_BANK_0                                                          (292U)
#define CSLR_GICSS0_SPI_GPIO0_GPIO_BANK_1                                                          (293U)
#define CSLR_GICSS0_SPI_GPIO0_GPIO_BANK_2                                                          (294U)
#define CSLR_GICSS0_SPI_GPIO0_GPIO_BANK_3                                                          (295U)
#define CSLR_GICSS0_SPI_GPIO0_GPIO_BANK_4                                                          (296U)
#define CSLR_GICSS0_SPI_GPIO0_GPIO_BANK_5                                                          (297U)
#define CSLR_GICSS0_SPI_GPIO0_GPIO_BANK_6                                                          (298U)
#define CSLR_GICSS0_SPI_GPIO0_GPIO_BANK_7                                                          (299U)
#define CSLR_GICSS0_SPI_WKUP_GPIO0_GPIO_BANK_0                                                     (308U)
#define CSLR_GICSS0_SPI_GPIO2_GPIO_BANK_0                                                          (312U)
#define CSLR_GICSS0_SPI_GPIO2_GPIO_BANK_1                                                          (313U)
#define CSLR_GICSS0_SPI_GPIO2_GPIO_BANK_2                                                          (314U)
#define CSLR_GICSS0_SPI_GPIO2_GPIO_BANK_3                                                          (315U)
#define CSLR_GICSS0_SPI_GPIO2_GPIO_BANK_4                                                          (316U)
#define CSLR_GICSS0_SPI_GPIO2_GPIO_BANK_5                                                          (317U)
#define CSLR_GICSS0_SPI_GPIO2_GPIO_BANK_6                                                          (318U)
#define CSLR_GICSS0_SPI_GPIO2_GPIO_BANK_7                                                          (319U)
#define CSLR_GICSS0_SPI_DMASS0_BCDMA_INTR_RX_SHARED_SPI0_0                                         (352U)
#define CSLR_GICSS0_SPI_DMASS0_BCDMA_INTR_TX_SHARED_SPI0_0                                         (353U)
#define CSLR_GICSS0_SPI_DMASS0_PKTDMA_INTR_RX_SHARED_SPI0_0                                        (354U)
#define CSLR_GICSS0_SPI_DMASS0_PKTDMA_INTR_TX_SHARED_SPI0_0                                        (355U)
#define CSLR_GICSS0_SPI_DMASS0_BCDMA_INTR_RX_SHARED_SPI1_0                                         (356U)
#define CSLR_GICSS0_SPI_DMASS0_BCDMA_INTR_TX_SHARED_SPI1_0                                         (357U)
#define CSLR_GICSS0_SPI_DMASS0_PKTDMA_INTR_RX_SHARED_SPI1_0                                        (358U)
#define CSLR_GICSS0_SPI_DMASS0_PKTDMA_INTR_TX_SHARED_SPI1_0                                        (359U)
#define CSLR_GICSS0_SPI_DMASS0_BCDMA_INTR_RX_SHARED_SPI2_0                                         (360U)
#define CSLR_GICSS0_SPI_DMASS0_BCDMA_INTR_TX_SHARED_SPI2_0                                         (361U)
#define CSLR_GICSS0_SPI_DMASS0_PKTDMA_INTR_RX_SHARED_SPI2_0                                        (362U)
#define CSLR_GICSS0_SPI_DMASS0_PKTDMA_INTR_TX_SHARED_SPI2_0                                        (363U)
#define CSLR_GICSS0_SPI_DMASS0_BCDMA_INTR_RX_SHARED_SPI3_0                                         (364U)
#define CSLR_GICSS0_SPI_DMASS0_BCDMA_INTR_TX_SHARED_SPI3_0                                         (365U)
#define CSLR_GICSS0_SPI_DMASS0_PKTDMA_INTR_RX_SHARED_SPI3_0                                        (366U)
#define CSLR_GICSS0_SPI_DMASS0_PKTDMA_INTR_TX_SHARED_SPI3_0                                        (367U)
#define CSLR_GICSS0_SPI_DMASS0_BCDMA_INTR_RX_UART0_0                                               (384U)
#define CSLR_GICSS0_SPI_DMASS0_BCDMA_INTR_TX_UART0_0                                               (385U)
#define CSLR_GICSS0_SPI_DMASS0_PKTDMA_INTR_RX_UART0_0                                              (386U)
#define CSLR_GICSS0_SPI_DMASS0_PKTDMA_INTR_TX_UART0_0                                              (387U)
#define CSLR_GICSS0_SPI_DMASS0_BCDMA_INTR_RX_UART1_0                                               (388U)
#define CSLR_GICSS0_SPI_DMASS0_BCDMA_INTR_TX_UART1_0                                               (389U)
#define CSLR_GICSS0_SPI_DMASS0_PKTDMA_INTR_RX_UART1_0                                              (390U)
#define CSLR_GICSS0_SPI_DMASS0_PKTDMA_INTR_TX_UART1_0                                              (391U)
#define CSLR_GICSS0_SPI_DMASS0_BCDMA_INTR_RX_UART2_0                                               (392U)
#define CSLR_GICSS0_SPI_DMASS0_BCDMA_INTR_TX_UART2_0                                               (393U)
#define CSLR_GICSS0_SPI_DMASS0_PKTDMA_INTR_RX_UART2_0                                              (394U)
#define CSLR_GICSS0_SPI_DMASS0_PKTDMA_INTR_TX_UART2_0                                              (395U)
#define CSLR_GICSS0_SPI_DMASS0_BCDMA_INTR_RX_UART3_0                                               (396U)
#define CSLR_GICSS0_SPI_DMASS0_BCDMA_INTR_TX_UART3_0                                               (397U)
#define CSLR_GICSS0_SPI_DMASS0_PKTDMA_INTR_RX_UART3_0                                              (398U)
#define CSLR_GICSS0_SPI_DMASS0_PKTDMA_INTR_TX_UART3_0                                              (399U)
#define CSLR_GICSS0_SPI_DMASS0_BCDMA_INTR_RX_UART4_0                                               (400U)
#define CSLR_GICSS0_SPI_DMASS0_BCDMA_INTR_TX_UART4_0                                               (401U)
#define CSLR_GICSS0_SPI_DMASS0_PKTDMA_INTR_RX_UART4_0                                              (402U)
#define CSLR_GICSS0_SPI_DMASS0_PKTDMA_INTR_TX_UART4_0                                              (403U)
#define CSLR_GICSS0_SPI_DMASS0_BCDMA_INTR_RX_UART5_0                                               (404U)
#define CSLR_GICSS0_SPI_DMASS0_BCDMA_INTR_TX_UART5_0                                               (405U)
#define CSLR_GICSS0_SPI_DMASS0_PKTDMA_INTR_RX_UART5_0                                              (406U)
#define CSLR_GICSS0_SPI_DMASS0_PKTDMA_INTR_TX_UART5_0                                              (407U)
#define CSLR_GICSS0_SPI_DMASS0_BCDMA_INTR_RX_UART6_0                                               (408U)
#define CSLR_GICSS0_SPI_DMASS0_BCDMA_INTR_TX_UART6_0                                               (409U)
#define CSLR_GICSS0_SPI_DMASS0_PKTDMA_INTR_RX_UART6_0                                              (410U)
#define CSLR_GICSS0_SPI_DMASS0_PKTDMA_INTR_TX_UART6_0                                              (411U)
#define CSLR_GICSS0_SPI_DMASS0_BCDMA_INTR_RX_MCASP0_CH0_0                                          (416U)
#define CSLR_GICSS0_SPI_DMASS0_BCDMA_INTR_TX_MCASP0_CH0_0                                          (417U)
#define CSLR_GICSS0_SPI_DMASS0_BCDMA_INTR_RX_MCASP1_CH0_0                                          (418U)
#define CSLR_GICSS0_SPI_DMASS0_BCDMA_INTR_TX_MCASP1_CH0_0                                          (419U)
#define CSLR_GICSS0_SPI_DMASS0_BCDMA_INTR_RX_MCASP2_CH0_0                                          (420U)
#define CSLR_GICSS0_SPI_DMASS0_BCDMA_INTR_TX_MCASP2_CH0_0                                          (421U)
#define CSLR_GICSS0_SPI_DMASS0_BCDMA_INTR_RX_SHARED_ADC_0                                          (514U)
#define CSLR_GICSS0_SPI_DMASS0_PKTDMA_INTR_RX_CPSW_CH_0_FLOW0_0                                    (516U)
#define CSLR_GICSS0_SPI_DMASS0_PKTDMA_INTR_RX_CPSW_CH_0_FLOW1_0                                    (517U)
#define CSLR_GICSS0_SPI_DMASS0_PKTDMA_INTR_RX_CPSW_CH_0_FLOW2_0                                    (518U)
#define CSLR_GICSS0_SPI_DMASS0_PKTDMA_INTR_RX_CPSW_CH_0_FLOW3_0                                    (519U)
#define CSLR_GICSS0_SPI_DMASS0_PKTDMA_INTR_RX_CPSW_CH_0_FLOW4_0                                    (520U)
#define CSLR_GICSS0_SPI_DMASS0_PKTDMA_INTR_RX_CPSW_CH_0_FLOW5_0                                    (521U)
#define CSLR_GICSS0_SPI_DMASS0_PKTDMA_INTR_RX_CPSW_CH_0_FLOW6_0                                    (522U)
#define CSLR_GICSS0_SPI_DMASS0_PKTDMA_INTR_RX_CPSW_CH_0_FLOW7_0                                    (523U)
#define CSLR_GICSS0_SPI_DMASS0_PKTDMA_INTR_RX_CPSW_CH_0_FLOW8_0                                    (524U)
#define CSLR_GICSS0_SPI_DMASS0_PKTDMA_INTR_RX_CPSW_CH_0_FLOW9_0                                    (525U)
#define CSLR_GICSS0_SPI_DMASS0_PKTDMA_INTR_RX_CPSW_CH_0_FLOW10_0                                   (526U)
#define CSLR_GICSS0_SPI_DMASS0_PKTDMA_INTR_RX_CPSW_CH_0_FLOW11_0                                   (527U)
#define CSLR_GICSS0_SPI_DMASS0_PKTDMA_INTR_RX_CPSW_CH_0_FLOW12_0                                   (528U)
#define CSLR_GICSS0_SPI_DMASS0_PKTDMA_INTR_RX_CPSW_CH_0_FLOW13_0                                   (529U)
#define CSLR_GICSS0_SPI_DMASS0_PKTDMA_INTR_RX_CPSW_CH_0_FLOW14_0                                   (530U)
#define CSLR_GICSS0_SPI_DMASS0_PKTDMA_INTR_RX_CPSW_CH_0_FLOW15_0                                   (531U)
#define CSLR_GICSS0_SPI_DMASS0_PKTDMA_INTR_TX_CPSW_CH_0_FLOW0_0                                    (532U)
#define CSLR_GICSS0_SPI_DMASS0_PKTDMA_INTR_TX_CPSW_CH_0_FLOW1_0                                    (533U)
#define CSLR_GICSS0_SPI_DMASS0_PKTDMA_INTR_TX_CPSW_CH_1_FLOW0_0                                    (534U)
#define CSLR_GICSS0_SPI_DMASS0_PKTDMA_INTR_TX_CPSW_CH_1_FLOW1_0                                    (535U)
#define CSLR_GICSS0_SPI_DMASS0_PKTDMA_INTR_TX_CPSW_CH_2_FLOW0_0                                    (536U)
#define CSLR_GICSS0_SPI_DMASS0_PKTDMA_INTR_TX_CPSW_CH_2_FLOW1_0                                    (537U)
#define CSLR_GICSS0_SPI_DMASS0_PKTDMA_INTR_TX_CPSW_CH_3_FLOW0_0                                    (538U)
#define CSLR_GICSS0_SPI_DMASS0_PKTDMA_INTR_TX_CPSW_CH_3_FLOW1_0                                    (539U)
#define CSLR_GICSS0_SPI_DMASS0_PKTDMA_INTR_TX_CPSW_CH_4_FLOW0_0                                    (540U)
#define CSLR_GICSS0_SPI_DMASS0_PKTDMA_INTR_TX_CPSW_CH_4_FLOW1_0                                    (541U)
#define CSLR_GICSS0_SPI_DMASS0_PKTDMA_INTR_TX_CPSW_CH_5_FLOW0_0                                    (542U)
#define CSLR_GICSS0_SPI_DMASS0_PKTDMA_INTR_TX_CPSW_CH_5_FLOW1_0                                    (543U)
#define CSLR_GICSS0_SPI_DMASS0_PKTDMA_INTR_TX_CPSW_CH_6_FLOW0_0                                    (544U)
#define CSLR_GICSS0_SPI_DMASS0_PKTDMA_INTR_TX_CPSW_CH_6_FLOW1_0                                    (545U)
#define CSLR_GICSS0_SPI_DMASS0_PKTDMA_INTR_TX_CPSW_CH_7_FLOW0_0                                    (546U)
#define CSLR_GICSS0_SPI_DMASS0_PKTDMA_INTR_TX_CPSW_CH_7_FLOW1_0                                    (547U)
#define CSLR_GICSS0_SPI_DMASS0_BCDMA_INTR_BC_BC0_0                                                 (548U)
#define CSLR_GICSS0_SPI_DMASS0_BCDMA_INTR_BC_BC1_0                                                 (549U)
#define CSLR_GICSS0_SPI_DMASS0_BCDMA_INTR_BC_BC2_0                                                 (550U)
#define CSLR_GICSS0_SPI_DMASS0_BCDMA_INTR_BC_BC3_0                                                 (551U)
#define CSLR_GICSS0_SPI_DMASS0_BCDMA_INTR_BC_BC4_0                                                 (552U)
#define CSLR_GICSS0_SPI_DMASS0_BCDMA_INTR_BC_BC5_0                                                 (553U)
#define CSLR_GICSS0_SPI_DMASS0_BCDMA_INTR_BC_BC6_0                                                 (554U)
#define CSLR_GICSS0_SPI_DMASS0_BCDMA_INTR_BC_BC7_0                                                 (555U)
#define CSLR_GICSS0_SPI_DMASS0_BCDMA_INTR_BC_BC8_0                                                 (556U)
#define CSLR_GICSS0_SPI_DMASS0_BCDMA_INTR_BC_BC9_0                                                 (557U)
#define CSLR_GICSS0_SPI_DMASS0_BCDMA_INTR_BC_BC10_0                                                (558U)
#define CSLR_GICSS0_SPI_DMASS0_BCDMA_INTR_BC_BC11_0                                                (559U)
#define CSLR_GICSS0_SPI_DMASS0_BCDMA_INTR_BC_BC12_0                                                (560U)
#define CSLR_GICSS0_SPI_DMASS0_BCDMA_INTR_BC_BC13_0                                                (561U)
#define CSLR_GICSS0_SPI_DMASS0_BCDMA_INTR_BC_BC14_0                                                (562U)
#define CSLR_GICSS0_SPI_DMASS0_BCDMA_INTR_BC_BC15_0                                                (563U)
#define CSLR_GICSS0_SPI_DMASS0_BCDMA_INTR_TX_SHARED_CRC_0                                          (580U)
#define CSLR_GICSS0_SPI_RTI0_INTR_RTI_0                                                            (672U)
#define CSLR_GICSS0_SPI_RTI0_INTR_RTI_1                                                            (673U)
#define CSLR_GICSS0_SPI_RTI0_INTR_RTI_2                                                            (674U)
#define CSLR_GICSS0_SPI_RTI0_INTR_RTI_3                                                            (675U)
#define CSLR_GICSS0_SPI_RTI0_INTR_TIMEBASE_0                                                       (676U)
#define CSLR_GICSS0_SPI_RTI0_INTR_OVERFLOW_0                                                       (677U)
#define CSLR_GICSS0_SPI_RTI0_INTR_OVERFLOW_1                                                       (678U)
#define CSLR_GICSS0_SPI_RTI1_INTR_RTI_0                                                            (680U)
#define CSLR_GICSS0_SPI_RTI1_INTR_RTI_1                                                            (681U)
#define CSLR_GICSS0_SPI_RTI1_INTR_RTI_2                                                            (682U)
#define CSLR_GICSS0_SPI_RTI1_INTR_RTI_3                                                            (683U)
#define CSLR_GICSS0_SPI_RTI1_INTR_TIMEBASE_0                                                       (684U)
#define CSLR_GICSS0_SPI_RTI1_INTR_OVERFLOW_0                                                       (685U)
#define CSLR_GICSS0_SPI_RTI1_INTR_OVERFLOW_1                                                       (686U)
#define CSLR_GICSS0_SPI_WKUP_GPIO0_GPIO_0                                                          (736U)
#define CSLR_GICSS0_SPI_WKUP_GPIO0_GPIO_1                                                          (737U)
#define CSLR_GICSS0_SPI_WKUP_GPIO0_GPIO_2                                                          (738U)
#define CSLR_GICSS0_SPI_WKUP_GPIO0_GPIO_3                                                          (739U)
#define CSLR_GICSS0_SPI_WKUP_GPIO0_GPIO_4                                                          (740U)
#define CSLR_GICSS0_SPI_WKUP_GPIO0_GPIO_5                                                          (741U)
#define CSLR_GICSS0_SPI_WKUP_GPIO0_GPIO_6                                                          (742U)

#ifdef __cplusplus
}
#endif
#endif /* CSLR_GICSS0_INTERRUPT_MAP_H_ */
