/*
 *  Copyright (C) 2021-2024 Texas Instruments Incorporated
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#include <kernel/dpl/DebugP.h>
#include <kernel/dpl/SemaphoreP.h>
#include <kernel/dpl/AddrTranslateP.h>
#include <kernel/dpl/HwiP.h>
#include <drivers/epwm.h>
#include <drivers/eqep.h>
#include "ti_drivers_config.h"
#include "ti_drivers_open_close.h"
#include "ti_board_open_close.h"


/*
 * This example uses the EQEP module to measure frequency of a signal
 * generated by ePWM module
 *
 * In this example EQEP2 is used to measure frequency
 *
 * This example also showcases how to configure and use the EQEP module.
 */

/* Output channel - A or B */
#define APP_EPWM_OUTPUT_CH              (EPWM_OUTPUT_CH_A)
/* Duty Cycle of PWM output signal in % - give value from 0 to 100 */
#define APP_EPWM_DUTY_CYCLE             (50U)
/* Frequency of PWM output signal in Hz - 10 KHz is selected */
#define APP_EPWM_OUTPUT_FREQ            (1U * 10000U)
/* APP run time in seconds */
#define APP_EPWM_RUN_TIME               (10U)

/* TB frequency in Hz - so that /4 divider is used */
#define APP_EPWM_TB_FREQ                (CONFIG_EPWM0_FCLK / 4U)
/*
 *  PRD value - this determines the period
 *  PRD = (TBCLK/PWM FREQ) / 2
 *  /2 is added becasue up&down counter is selected. So period is 2 times
 */
#define APP_EPWM_PRD_VAL                ((APP_EPWM_TB_FREQ / APP_EPWM_OUTPUT_FREQ) / 2U)
/*
 *  COMPA value - this determines the duty cycle
 *  COMPA = (PRD - ((dutycycle * PRD) / 100)
 */
#define APP_EPWM_COMPA_VAL              (APP_EPWM_PRD_VAL - ((APP_EPWM_DUTY_CYCLE * \
                                            APP_EPWM_PRD_VAL) / 100U))


#define EQEP_UNIT_TIMEOUT_FREQ          (1000)

/* Defines used by example */
/* Sysclk frequency */
#define DEVICE_SYSCLK_FREQ              (500000000U)
/* Base/max frequency is 10 kHz */
#define BASE_FREQ                       (10000U)
/*      t2 - t1 = 8(SYSCLKFREQ / 128) / (10kHz * 2)
                = (SYSCLKFREQ / 128) / (2 * 10kHz / 8)
                = maximum (t2 - t1) = freqScalerPR
*/
#define FREQ_SCALER_PR  (((DEVICE_SYSCLK_FREQ / 128) * 8) / (2 * BASE_FREQ))
/*      10kHz = (x2 - x1) / (2 / 1000Hz)
        max (x2 - x1) = 20 counts = freqScalerFR
*/
#define FREQ_SCALER_FR  ((BASE_FREQ * 2) / EQEP_UNIT_TIMEOUT_FREQ)
/* Global variables and objects */
uint32_t gEpwmBaseAddr;
uint32_t gEqepBaseAddr;
static HwiP_Object gEpwmHwiObject;
static SemaphoreP_Object gEpwmSyncSemObject;
typedef struct
{
    uint32_t freqScalerPR;  /* Parameter: Scaler converting 1/N cycles to a */
                            /* GLOBAL_Q freq (Q0) - independently with global Q */
    uint32_t freqScalerFR;  /* Parameter: Scaler converting 1/N cycles to a */
                            /* GLOBAL_Q freq (Q0) - independently with global Q */
    uint32_t baseFreq;      /* Parameter: Maximum freq */

    Float32 freqPR;         /* Output: Freq in per-unit using capture unit */
    int32_t freqHzPR;       /* Output: Freq in Hz, measured using Capture unit */
    uint32_t oldPos;

    Float32 freqFR;         /* Output: Freq in per-unit using position counter */
    int32_t freqHzFR;       /* Output: Freq in Hz, measured using Capture unit */
} FreqCal_Object;
typedef FreqCal_Object *FreqCal_Handle;
FreqCal_Object freq =
{
    FREQ_SCALER_PR,  /* freqScalerPR */
    FREQ_SCALER_FR,  /* freqScalerFR */
    BASE_FREQ,       /* baseFreq */
    0, 0, 0, 0, 0    /* Initialize outputs to zero */
};
uint32_t count = 0;  /* counter to check measurement gets saturated */
uint32_t pass=0, fail =0; /* Pass or fail indicator */

/* Function prototypes */
static void App_epwmIntrISR(void *handle);
static void FreqCal_calculate(FreqCal_Handle, uint32_t*);
static void App_eqepInitFrequencyCalculation(void);
static void App_epwmConfig(uint32_t epwmBaseAddr, uint32_t epwmCh, uint32_t epwmFuncClk);

void eqep_frequency_measurement_main(void *args)
{
    int32_t status;
    uint32_t numIsrCnt = (APP_EPWM_RUN_TIME * APP_EPWM_OUTPUT_FREQ);
    HwiP_Params hwiPrms;

    DebugP_log("EQEP Frequency Measurement Test Started ...\r\n");
	DebugP_log("Please ensure EPWM to EQEP loopback is connected...\r\n");
	DebugP_log("Please wait %d seconds ...\r\n", APP_EPWM_RUN_TIME);

    gEpwmBaseAddr = (uint32_t)AddrTranslateP_getLocalAddr(CONFIG_EPWM0_BASE_ADDR);
    gEqepBaseAddr = (uint32_t)AddrTranslateP_getLocalAddr(CONFIG_EQEP0_BASE_ADDR);

    status = SemaphoreP_constructCounting(&gEpwmSyncSemObject, 0, numIsrCnt);
    DebugP_assert(SystemP_SUCCESS == status);

    /* Register & enable interrupt */
    HwiP_Params_init(&hwiPrms);
    /* Integrate with Syscfg */
    hwiPrms.intNum      = CONFIG_EPWM0_INTR;
    hwiPrms.eventId     = CONFIG_EPWM0_EVENT_ID;
    hwiPrms.callback    = &App_epwmIntrISR;
    /* Integrate with Syscfg */
    hwiPrms.isPulse     = CONFIG_EPWM0_INTR_IS_PULSE;
    status              = HwiP_construct(&gEpwmHwiObject, &hwiPrms);
    DebugP_assert(status == SystemP_SUCCESS);

    /* Configure PWM */
    App_epwmConfig(gEpwmBaseAddr, APP_EPWM_OUTPUT_CH, CONFIG_EPWM0_FCLK);
    /* Configure    EQEP */
    App_eqepInitFrequencyCalculation();

    while(numIsrCnt > 0)
    {
        SemaphoreP_pend(&gEpwmSyncSemObject, SystemP_WAIT_FOREVER);
        numIsrCnt--;
    }

    EPWM_etIntrDisable(gEpwmBaseAddr);
    EPWM_etIntrClear(gEpwmBaseAddr);     /* Clear any pending interrupts if any */
    HwiP_destruct(&gEpwmHwiObject);
    SemaphoreP_destruct(&gEpwmSyncSemObject);
    DebugP_log("Expected frequency = %d Hz, Measured frequency = %d Hz \r\n", APP_EPWM_OUTPUT_FREQ, freq.freqHzFR);
    if (pass)
    {
        DebugP_log("EQEP Frequency Measurement Test Passed!!\r\n");
        DebugP_log("All tests have passed!!\r\n");
    }
    else
    {
        DebugP_log("EQEP Frequency Measurement Test Failed!!\r\n");
    }

}

static void App_epwmIntrISR(void *handle)
{
    volatile bool status;

    /* Checks for events and calculates frequency. */
    FreqCal_calculate(&freq, &count);

    /* Comparing the eQEP measured frequency with the ePWM frequency */
    /* After count becomes 3 , eQEP measurement gets saturated and */
    /* classifying pass = 1 if measured frequency is 50 more or */
    /* less than input */
    if (count >= 3)
    {
         if (((freq.freqHzFR - (int32_t)APP_EPWM_OUTPUT_FREQ) < 50) && ((freq.freqHzFR - (int32_t)APP_EPWM_OUTPUT_FREQ) > -50))
        {
            pass = 1; fail = 0;
        }
        else
        {
            fail = 1; pass = 0;
        }
    }

    status = EPWM_etIntrStatus(gEpwmBaseAddr);
    if(status & EPWM_ETFLG_INT_MASK)
    {
        SemaphoreP_post(&gEpwmSyncSemObject);
        EPWM_etIntrClear(gEpwmBaseAddr);
    }

    return;
}

static void FreqCal_calculate(FreqCal_Object *p, uint32_t *c)
{

    uint32_t temp;
    Float32 newPosCnt, oldPosCnt;

    /* Frequency calculation using eQEP position counter */
    if((EQEP_getInterruptStatus(gEqepBaseAddr) & EQEP_INT_UNIT_TIME_OUT) != 0)
    {
        /* Incrementing the count value */
        (*c)++;
        /* Get latched POSCNT value */
        newPosCnt = EQEP_getPositionLatch(gEqepBaseAddr);
        if(newPosCnt > 0.0f)
        {
            oldPosCnt = p->oldPos;
            if(newPosCnt > oldPosCnt)
            {
                /* x2 - x1 in v = (x2 - x1) / T equation */
                temp = newPosCnt - oldPosCnt;
            }
            else
            {
                temp = ((float)0xFFFFFFFF - oldPosCnt) + newPosCnt;
            }

            /* p->freqFR = (x2 - x1) / (T * 10kHz) */
            p->freqFR = ((Float32)temp / (Float32)p->freqScalerFR);
            temp=p->freqFR;

            /* Is freq greater than max freq (10kHz for this example)? */
            if(temp >= 1)
            {
                p->freqFR = 1;
            }
            else
            {
                p->freqFR = temp;
            }

            /* Q0 = Q0 * GLOBAL_Q */
            /* p->freqHzFR = (p->freqFR) * 10kHz = (x2 - x1) / T */
            p->freqHzFR = (p->baseFreq * p->freqFR);

            /* Update old position counter value and clear unit time out flag */
            p->oldPos = newPosCnt;
            EQEP_clearInterruptStatus(gEqepBaseAddr, EQEP_INT_UNIT_TIME_OUT);
        }
    }
    /* Frequency calculation using eQEP capture counter */
    if((EQEP_getStatus(gEqepBaseAddr) & EQEP_STS_UNIT_POS_EVNT) != 0)
    {
        /* No capture overflow */
        if((EQEP_getStatus(gEqepBaseAddr) & EQEP_STS_CAP_OVRFLW_ERROR) == 0)
        {
            temp = (uint32_t)EQEP_getCapturePeriodLatch(gEqepBaseAddr);
        }
        else
        {
            /* Capture overflow, saturate the result */
            temp = 0xFFFF;
        }

        /* p->freqPR = X / [(t2 - t1) * 10kHz] */
        p->freqPR = ((Float32)p->freqScalerPR /  (Float32)temp);
        temp = p->freqPR;

        if(temp > 1)
        {
            p->freqPR = 1;
        }
        else
        {
            p->freqPR = temp;
        }

        /* Q0 = Q0 * GLOBAL_Q */
        /* p->freqHzPR = (p->freqPR) * 10kHz = X / (t2 - t1) */
        p->freqHzPR = (p->baseFreq * p->freqPR);

        /* Clear unit position event flag and overflow error flag */
        EQEP_clearStatus(gEqepBaseAddr, (EQEP_STS_UNIT_POS_EVNT |
                                      EQEP_STS_CAP_OVRFLW_ERROR));
    }
}
static void App_epwmConfig(uint32_t epwmBaseAddr,
                           uint32_t epwmCh,
                           uint32_t epwmFuncClk)
{
    EPWM_AqActionCfg  aqConfig;

    /* Configure Time base submodule */
    EPWM_tbTimebaseClkCfg(epwmBaseAddr, APP_EPWM_TB_FREQ, epwmFuncClk);
    EPWM_tbPwmFreqCfg(epwmBaseAddr, APP_EPWM_TB_FREQ, APP_EPWM_OUTPUT_FREQ,
        EPWM_TB_COUNTER_DIR_UP_DOWN,
            EPWM_SHADOW_REG_CTRL_ENABLE);
    EPWM_tbSyncDisable(epwmBaseAddr);
    EPWM_tbSetSyncOutMode(epwmBaseAddr, EPWM_TB_SYNC_OUT_EVT_SYNCIN);
    EPWM_tbSetEmulationMode(epwmBaseAddr, EPWM_TB_EMU_MODE_FREE_RUN);

    /* Configure counter compare submodule */
    EPWM_counterComparatorCfg(epwmBaseAddr, EPWM_CC_CMP_A,
        APP_EPWM_COMPA_VAL, EPWM_SHADOW_REG_CTRL_ENABLE,
            EPWM_CC_CMP_LOAD_MODE_CNT_EQ_ZERO, TRUE);
    EPWM_counterComparatorCfg(epwmBaseAddr, EPWM_CC_CMP_B,
        APP_EPWM_COMPA_VAL, EPWM_SHADOW_REG_CTRL_ENABLE,
            EPWM_CC_CMP_LOAD_MODE_CNT_EQ_ZERO, TRUE);

    /* Configure Action Qualifier Submodule */
    aqConfig.zeroAction = EPWM_AQ_ACTION_DONOTHING;
    aqConfig.prdAction = EPWM_AQ_ACTION_DONOTHING;
    aqConfig.cmpAUpAction = EPWM_AQ_ACTION_HIGH;
    aqConfig.cmpADownAction = EPWM_AQ_ACTION_LOW;
    aqConfig.cmpBUpAction = EPWM_AQ_ACTION_HIGH;
    aqConfig.cmpBDownAction = EPWM_AQ_ACTION_LOW;
    EPWM_aqActionOnOutputCfg(epwmBaseAddr, epwmCh, &aqConfig);

    /* Configure Dead Band Submodule */
    EPWM_deadbandBypass(epwmBaseAddr);

    /* Configure Chopper Submodule */
    EPWM_chopperEnable(epwmBaseAddr, FALSE);

    /* Configure trip zone Submodule */
    EPWM_tzTripEventDisable(epwmBaseAddr, EPWM_TZ_EVENT_ONE_SHOT, 0U);
    EPWM_tzTripEventDisable(epwmBaseAddr, EPWM_TZ_EVENT_CYCLE_BY_CYCLE, 0U);

    /* Configure event trigger Submodule */
    EPWM_etIntrCfg(epwmBaseAddr, EPWM_ET_INTR_EVT_CNT_EQ_ZRO,
        EPWM_ET_INTR_PERIOD_FIRST_EVT);
    EPWM_etIntrEnable(epwmBaseAddr);
}
static void App_eqepInitFrequencyCalculation(void)
{
    EQEP_setInitialPosition(gEqepBaseAddr, 0U);
    EQEP_setPosition(gEqepBaseAddr, 0U);

    /* Configure the decoder for up-count mode, counting both rising and
       falling edges (that is, 2x resolution) */
    EQEP_setDecoderConfig(gEqepBaseAddr, (EQEP_CONFIG_2X_RESOLUTION |
                                          EQEP_CONFIG_UP_COUNT |
                                          EQEP_CONFIG_NO_SWAP));
    EQEP_setEmulationMode(gEqepBaseAddr, EQEP_EMULATIONMODE_RUNFREE);

    /* Configure the position counter to reset on an unit timeout event */
    EQEP_setPositionCounterConfig(gEqepBaseAddr,
                                  EQEP_POSITION_RESET_UNIT_TIME_OUT,
                                  CSL_EQEP_QPOSCNT_QPOSCNT_MAX);

    /* Enable the unit timer, setting the frequency to EQEP_UNIT_TIMEOUT_FREQ */
    EQEP_enableUnitTimer(gEqepBaseAddr, (CONFIG_EQEP0_FCLK/EQEP_UNIT_TIMEOUT_FREQ));

    /* Configure the position counter to be latched on a unit time out */
    EQEP_setLatchMode(gEqepBaseAddr, EQEP_LATCH_UNIT_TIME_OUT);

    /* Enable the EQEP module */
    EQEP_enableModule(gEqepBaseAddr);

    /* Configure and enable the edge-capture unit. The capture clock divider is
       SYSCLKOUT/128. The unit-position event divider is QCLK/8. */
    EQEP_setCaptureConfig(gEqepBaseAddr, EQEP_CAPTURE_CLK_DIV_128,
                          EQEP_UNIT_POS_EVNT_DIV_8);
    EQEP_enableCapture(gEqepBaseAddr);

}


