/* parasoft-begin-suppress MISRA2012-RULE-1_1_a_c99-2 "C99 - limits" parasoft-begin-suppress MISRA2012-RULE-1_1_a_c90-2 "C90 - limits" */
/* parasoft-begin-suppress item MISRA2012-DIR-4_8 "Consider hiding implementation of structure, DRV-3667" */

/**********************************************************************
 * Copyright (C) 2012-2026 Cadence Design Systems, Inc.
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 * notice, this list of conditions and the following disclaimer in the
 * documentation and/or other materials provided with the distribution.
 * 3. Neither the name of the copyright holder nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT
 *
 **********************************************************************/

#ifndef REG_DSITX_REGS_H_
#define REG_DSITX_REGS_H_

#include <drivers/dss/v1/hw_include/common/cps_drv.h>

#include "dsitx_regs_macros.h"

typedef struct __attribute__((packed, aligned(4))) DSITX_Regs_s {
    volatile uint32_t ip_conf;
    volatile uint32_t mctl_main_data_ctl;
    volatile uint32_t mctl_main_phy_ctl;
    volatile uint32_t mctl_main_en;
    volatile uint32_t mctl_dphy_cfg0;
    volatile uint32_t mctl_dphy_timeout1;
    volatile uint32_t mctl_dphy_timeout2;
    volatile uint32_t mctl_ulpout_time;
    volatile uint32_t mctl_3dvideo_ctl;
    volatile uint32_t mctl_main_sts;
    volatile uint32_t mctl_dphy_err;
    volatile uint32_t mctl_lane_sts;
    volatile uint32_t dsc_mode_ctl;
    volatile uint32_t dsc_cmd_send;
    volatile uint32_t dsc_pps_wrdat;
    volatile uint32_t dsc_mode_sts;
    volatile uint32_t mctl_dphy_skewcal_timeout;
    volatile char pad__0[0x2CU];
    volatile uint32_t cmd_mode_ctl;
    volatile uint32_t cmd_mode_ctl2;
    volatile uint32_t cmd_mode_sts;
    volatile char pad__1[0x4U];
    volatile uint32_t direct_cmd_send;
    volatile uint32_t direct_cmd_main_settings;
    volatile uint32_t direct_cmd_sts;
    volatile uint32_t direct_cmd_rd_init;
    volatile uint32_t direct_cmd_wrdat;
    volatile uint32_t direct_cmd_fifo_rst;
    volatile char pad__2[0x8U];
    volatile uint32_t direct_cmd_rddat;
    volatile uint32_t direct_cmd_rd_property;
    volatile uint32_t direct_cmd_rd_sts;
    volatile char pad__3[0x4U];
    volatile uint32_t vid_main_ctl;
    volatile uint32_t vid_vsize1;
    volatile uint32_t vid_vsize2;
    volatile char pad__4[0x4U];
    volatile uint32_t vid_hsize1;
    volatile uint32_t vid_hsize2;
    volatile char pad__5[0x4U];
    volatile uint32_t vid_blksize1;
    volatile uint32_t vid_blksize2;
    volatile char pad__6[0x4U];
    volatile uint32_t vid_pck_time;
    volatile uint32_t vid_dphy_time;
    volatile uint32_t vid_err_color1;
    volatile uint32_t vid_err_color2;
    volatile uint32_t vid_vpos;
    volatile uint32_t vid_hpos;
    volatile uint32_t vid_mode_sts;
    volatile uint32_t vid_vca_setting1;
    volatile uint32_t vid_vca_setting2;
    volatile uint32_t tvg_ctl;
    volatile uint32_t tvg_img_size;
    volatile uint32_t tvg_color1;
    volatile uint32_t tvg_color1_bis;
    volatile uint32_t tvg_color2;
    volatile uint32_t tvg_color2_bis;
    volatile uint32_t tvg_sts;
    volatile char pad__7[0x18U];
    volatile uint32_t mctl_main_sts_ctl;
    volatile uint32_t cmd_mode_sts_ctl;
    volatile uint32_t direct_cmd_sts_ctl;
    volatile uint32_t direct_cmd_rd_sts_ctl;
    volatile uint32_t vid_mode_sts_ctl;
    volatile uint32_t tvg_sts_ctl;
    volatile uint32_t mctl_dphy_err_ctl1;
    volatile uint32_t mctl_dphy_err_ctl2;
    volatile uint32_t mctl_main_sts_clr;
    volatile uint32_t cmd_mode_sts_clr;
    volatile uint32_t direct_cmd_sts_clr;
    volatile uint32_t direct_cmd_rd_sts_clr;
    volatile uint32_t vid_mode_sts_clr;
    volatile uint32_t tg_sts_clr;
    volatile uint32_t mctl_dphy_err_clr;
    volatile char pad__8[0x4U];
    volatile uint32_t mctl_main_sts_flag;
    volatile uint32_t cmd_mode_sts_flag;
    volatile uint32_t direct_cmd_sts_flag;
    volatile uint32_t direct_cmd_rd_sts_flag;
    volatile uint32_t vid_mode_sts_flag;
    volatile uint32_t tg_sts_flag;
    volatile uint32_t mctl_dphy_err_flag;
    volatile char pad__9[0x14U];
    volatile uint32_t dpi_irq_en;
    volatile uint32_t dpi_irq_clr;
    volatile uint32_t dpi_irq_sts;
    volatile uint32_t dpi_cfg;
    volatile char pad__10[0x40U];
    volatile uint32_t test_generic;
    volatile char pad__11[0x8U];
    volatile uint32_t id_reg;
    volatile uint32_t asf_int_status;
    volatile uint32_t asf_int_raw_status;
    volatile uint32_t asf_int_mask;
    volatile uint32_t asf_int_test;
    volatile uint32_t asf_fatal_nonfatal_select;
    volatile char pad__12[0xCU];
    volatile uint32_t asf_sram_corr_fault_status;
    volatile uint32_t asf_sram_uncorr_fault_status;
    volatile uint32_t asf_sram_fault_stats;
    volatile char pad__13[0x4U];
    volatile uint32_t asf_trans_to_ctrl;
    volatile uint32_t asf_trans_to_fault_mask;
    volatile uint32_t asf_trans_to_fault_status;
    volatile char pad__14[0x4U];
    volatile uint32_t asf_protocol_fault_mask;
    volatile uint32_t asf_protocol_fault_status;
} DSITX_Regs;

#endif /* REG_DSITX_REGS_H_ */

/* parasoft-end-suppress MISRA2012-RULE-1_1_a_c99-2 "C99 - limits" */
/* parasoft-end-suppress MISRA2012-RULE-1_1_a_c90-2 "C90 - limits" */
/* parasoft-end-suppress MISRA2012-DIR-4_8 "Consider hiding implementation of structure, DRV-3667" */

