/*
 *  Copyright (C) 2021 Texas Instruments Incorporated
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef TEST_ADC_TEST_CASES_H_
#define TEST_ADC_TEST_CASES_H_

/* ========================================================================== */
/*                             Include Files                                  */
/* ========================================================================== */

#include "test_adc.h"
#include "ti_drivers_config.h"

/* ========================================================================== */
/*                           Macros & Typedefs                                */
/* ========================================================================== */

/* SOC-specific ADC base address selection */
#if defined(SOC_AM275X) || defined(SOC_AM62LX)
#define ADC_TEST_BASE_ADDR  CONFIG_ADC0_BASE_ADDR
#else
#error "Unsupported SOC for ADC test"
#endif

#define ADC_NUM_TESTCASES (sizeof(gADCTestcaseParams) / sizeof(test_adc_testcaseParams_t))

/* ========================================================================== */
/*                            Global Variables                                */
/* ========================================================================== */

/** \brief Defines the various ADC test cases. */
test_adc_testcaseParams_t gADCTestcaseParams[] =
{
    {
        .testcaseId         = 6697U,
        .testCaseName       = "ADC Polling mode with FIFO 0",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_SINGLE_SHOT,
            .intrEnable = (ADC_INTR_SRC_END_OF_SEQUENCE | ADC_INTR_SRC_FIFO0_OVERRUN |
                           ADC_INTR_SRC_FIFO0_UNDERFLOW),
            .numSteps = 16,
            .numIterations = 1,
            {
                {ADC_STEP_1, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_2, ADC_CHANNEL_2, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_3, ADC_CHANNEL_3, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_4, ADC_CHANNEL_4, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_5, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_6, ADC_CHANNEL_2, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_7, ADC_CHANNEL_3, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_8, ADC_CHANNEL_4, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_9, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_10, ADC_CHANNEL_2, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_11, ADC_CHANNEL_3, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_12, ADC_CHANNEL_4, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_13, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_14, ADC_CHANNEL_2, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_15, ADC_CHANNEL_3, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_16, ADC_CHANNEL_4, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
            },
            .testMode = ADC_TEST_MODE_POLLING,
            .fifoEnable = TRUE,
            .fifoNum = ADC_FIFO_NUM_0,
            .fifoThreshold = 32,
            .highRange = 0x3FFU,
            .lowRange = 0U,
            .stepIdTagEnable = TRUE,
            .errOffset = 100U,
        },
    },
    {
        .testcaseId         = 6698U,
        .testCaseName       = "ADC Polling mode with FIFO 1",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_SINGLE_SHOT,
            .intrEnable = (ADC_INTR_SRC_END_OF_SEQUENCE | ADC_INTR_SRC_FIFO1_OVERRUN |
                           ADC_INTR_SRC_FIFO1_UNDERFLOW),
            .numSteps = 16,
            .numIterations = 1,
            {
                {ADC_STEP_1, ADC_CHANNEL_1, ADC_FIFO_NUM_1, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_2, ADC_CHANNEL_2, ADC_FIFO_NUM_1, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_3, ADC_CHANNEL_3, ADC_FIFO_NUM_1, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_4, ADC_CHANNEL_4, ADC_FIFO_NUM_1, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_5, ADC_CHANNEL_1, ADC_FIFO_NUM_1, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_6, ADC_CHANNEL_2, ADC_FIFO_NUM_1, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_7, ADC_CHANNEL_3, ADC_FIFO_NUM_1, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_8, ADC_CHANNEL_4, ADC_FIFO_NUM_1, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_9, ADC_CHANNEL_1, ADC_FIFO_NUM_1, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_10, ADC_CHANNEL_2, ADC_FIFO_NUM_1, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_11, ADC_CHANNEL_3, ADC_FIFO_NUM_1, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_12, ADC_CHANNEL_4, ADC_FIFO_NUM_1, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_13, ADC_CHANNEL_1, ADC_FIFO_NUM_1, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_14, ADC_CHANNEL_2, ADC_FIFO_NUM_1, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_15, ADC_CHANNEL_3, ADC_FIFO_NUM_1, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_16, ADC_CHANNEL_4, ADC_FIFO_NUM_1, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
            },
            .testMode = ADC_TEST_MODE_POLLING,
            .fifoEnable = TRUE,
            .fifoNum = ADC_FIFO_NUM_1,
            .fifoThreshold = 32,
            .highRange = 0x3FFU,
            .lowRange = 0U,
            .stepIdTagEnable = TRUE,
            .errOffset = 100U,
        },
    },
    {
        .testcaseId         = 6699U,
        .testCaseName       = "ADC ISR mode with FIFO 0",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_SINGLE_SHOT,
            .intrEnable = (ADC_INTR_SRC_END_OF_SEQUENCE | ADC_INTR_SRC_FIFO0_OVERRUN |
                           ADC_INTR_SRC_FIFO0_UNDERFLOW),
            .numSteps = 16,
            .numIterations = 1,
            {
                {ADC_STEP_1, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_2, ADC_CHANNEL_2, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_3, ADC_CHANNEL_3, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_4, ADC_CHANNEL_4, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_5, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_6, ADC_CHANNEL_2, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_7, ADC_CHANNEL_3, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_8, ADC_CHANNEL_4, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_9, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_10, ADC_CHANNEL_2, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_11, ADC_CHANNEL_3, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_12, ADC_CHANNEL_4, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_13, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_14, ADC_CHANNEL_2, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_15, ADC_CHANNEL_3, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_16, ADC_CHANNEL_4, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
            },
            .testMode = ADC_TEST_MODE_CPU,
            .fifoEnable = TRUE,
            .fifoNum = ADC_FIFO_NUM_0,
            .fifoThreshold = 32,
            .highRange = 0x3FFU,
            .lowRange = 0U,
            .stepIdTagEnable = TRUE,
            .errOffset = 100U,
        },
    },
    {
        .testcaseId         = 6700U,
        .testCaseName       = "ADC ISR mode with FIFO 1",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_SINGLE_SHOT,
            .intrEnable = (ADC_INTR_SRC_END_OF_SEQUENCE | ADC_INTR_SRC_FIFO1_OVERRUN |
                           ADC_INTR_SRC_FIFO1_UNDERFLOW),
            .numSteps = 16,
            .numIterations = 1,
            {
                {ADC_STEP_1, ADC_CHANNEL_1, ADC_FIFO_NUM_1, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_2, ADC_CHANNEL_2, ADC_FIFO_NUM_1, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_3, ADC_CHANNEL_3, ADC_FIFO_NUM_1, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_4, ADC_CHANNEL_4, ADC_FIFO_NUM_1, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_5, ADC_CHANNEL_1, ADC_FIFO_NUM_1, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_6, ADC_CHANNEL_2, ADC_FIFO_NUM_1, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_7, ADC_CHANNEL_3, ADC_FIFO_NUM_1, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_8, ADC_CHANNEL_4, ADC_FIFO_NUM_1, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_9, ADC_CHANNEL_1, ADC_FIFO_NUM_1, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_10, ADC_CHANNEL_2, ADC_FIFO_NUM_1, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_11, ADC_CHANNEL_3, ADC_FIFO_NUM_1, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_12, ADC_CHANNEL_4, ADC_FIFO_NUM_1, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_13, ADC_CHANNEL_1, ADC_FIFO_NUM_1, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_14, ADC_CHANNEL_2, ADC_FIFO_NUM_1, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_15, ADC_CHANNEL_3, ADC_FIFO_NUM_1, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_16, ADC_CHANNEL_4, ADC_FIFO_NUM_1, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
            },
            .testMode = ADC_TEST_MODE_CPU,
            .fifoEnable = TRUE,
            .fifoNum = ADC_FIFO_NUM_1,
            .fifoThreshold = 32,
            .highRange = 0x3FFU,
            .lowRange = 0U,
            .stepIdTagEnable = TRUE,
            .errOffset = 100U,
        },
    },
    {
        .testcaseId         = 6701U,
        .testCaseName       = "ADC samples averaging",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_SINGLE_SHOT,
            .intrEnable = (ADC_INTR_SRC_END_OF_SEQUENCE | ADC_INTR_SRC_FIFO0_OVERRUN |
                           ADC_INTR_SRC_FIFO0_UNDERFLOW),
            .numSteps = 5,
            .numIterations = 1,
            {
                {ADC_STEP_1, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_2, ADC_CHANNEL_2, ADC_FIFO_NUM_0, ADC_AVERAGING_8_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_3, ADC_CHANNEL_3, ADC_FIFO_NUM_0, ADC_AVERAGING_4_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_4, ADC_CHANNEL_4, ADC_FIFO_NUM_0, ADC_AVERAGING_2_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_5, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_NONE,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
            },
            .testMode = ADC_TEST_MODE_CPU,
            .fifoEnable = TRUE,
            .fifoNum = ADC_FIFO_NUM_0,
            .fifoThreshold = 10,
            .highRange = 0x3FFU,
            .lowRange = 0U,
            .stepIdTagEnable = TRUE,
            .errOffset = 100U,
        },
    },
    {
        .testcaseId         = 6702U,
        .testCaseName       = "ADC open and sample delay combinations",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_SINGLE_SHOT,
            .intrEnable = (ADC_INTR_SRC_END_OF_SEQUENCE | ADC_INTR_SRC_FIFO1_OVERRUN |
                           ADC_INTR_SRC_FIFO1_UNDERFLOW),
            .numSteps = 4,
            .numIterations = 1,
            {
                {ADC_STEP_1, ADC_CHANNEL_1, ADC_FIFO_NUM_1, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_2, ADC_CHANNEL_2, ADC_FIFO_NUM_1, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_3, ADC_CHANNEL_3, ADC_FIFO_NUM_1, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, 1},
                {ADC_STEP_4, ADC_CHANNEL_4, ADC_FIFO_NUM_1, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0, 1},
            },
            .testMode = ADC_TEST_MODE_CPU,
            .fifoEnable = TRUE,
            .fifoNum = ADC_FIFO_NUM_1,
            .fifoThreshold = 8,
            .highRange = 0x3FFU,
            .lowRange = 0U,
            .stepIdTagEnable = TRUE,
            .errOffset = 100U,
        },
    },
    {
        .testcaseId         = 6703U,
        .testCaseName       = "ADC singleshot Mode",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_SINGLE_SHOT,
            .intrEnable = (ADC_INTR_SRC_END_OF_SEQUENCE | ADC_INTR_SRC_FIFO0_OVERRUN |
                           ADC_INTR_SRC_FIFO0_UNDERFLOW),
            .numSteps = 16,
            .numIterations = 1,
            {
                {ADC_STEP_1, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_2, ADC_CHANNEL_2, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_3, ADC_CHANNEL_3, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_4, ADC_CHANNEL_4, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_5, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_6, ADC_CHANNEL_2, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_7, ADC_CHANNEL_3, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_8, ADC_CHANNEL_4, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_9, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_10, ADC_CHANNEL_2, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_11, ADC_CHANNEL_3, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_12, ADC_CHANNEL_4, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_13, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_14, ADC_CHANNEL_2, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_15, ADC_CHANNEL_3, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_16, ADC_CHANNEL_4, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
            },
            .testMode = ADC_TEST_MODE_CPU,
            .fifoEnable = TRUE,
            .fifoNum = ADC_FIFO_NUM_0,
            .fifoThreshold = 32,
            .highRange = 0x3FFU,
            .lowRange = 0U,
            .stepIdTagEnable = TRUE,
            .errOffset = 100U,
        },
    },
    {
        .testcaseId         = 6704U,
        .testCaseName       = "ADC Continuous mode",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_CONTINUOUS,
            .intrEnable = (ADC_INTR_SRC_END_OF_SEQUENCE),
            .numSteps = 2,
            .numIterations = 10,
            {
                {ADC_STEP_1, ADC_CHANNEL_1, ADC_FIFO_NUM_1, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_CONTINUOUS, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_2, ADC_CHANNEL_2, ADC_FIFO_NUM_1, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_CONTINUOUS, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
            },
            .testMode = ADC_TEST_MODE_CPU,
            .fifoEnable = TRUE,
            .fifoNum = ADC_FIFO_NUM_1,
            .fifoThreshold = 40,
            .highRange = 0x3FFU,
            .lowRange = 0U,
            .stepIdTagEnable = TRUE,
            .errOffset = 100U,
        },
    },
    {
        .testcaseId         = 6705U,
        .testCaseName       = "ADC Min Max Range",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_SINGLE_SHOT,
            .intrEnable = (ADC_INTR_SRC_END_OF_SEQUENCE | ADC_INTR_SRC_FIFO1_OVERRUN |
                           ADC_INTR_SRC_FIFO1_UNDERFLOW | ADC_INTR_SRC_OUT_OF_RANGE),
            .numSteps = 16,
            .numIterations = 1,
            {
                {ADC_STEP_1, ADC_CHANNEL_1, ADC_FIFO_NUM_1, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 1U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_2, ADC_CHANNEL_2, ADC_FIFO_NUM_1, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 1U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_3, ADC_CHANNEL_3, ADC_FIFO_NUM_1, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 1U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_4, ADC_CHANNEL_4, ADC_FIFO_NUM_1, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 1U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_5, ADC_CHANNEL_1, ADC_FIFO_NUM_1, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 1U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_6, ADC_CHANNEL_2, ADC_FIFO_NUM_1, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 1U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_7, ADC_CHANNEL_3, ADC_FIFO_NUM_1, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 1U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_8, ADC_CHANNEL_4, ADC_FIFO_NUM_1, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 1U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_9, ADC_CHANNEL_1, ADC_FIFO_NUM_1, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 1U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_10, ADC_CHANNEL_2, ADC_FIFO_NUM_1, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 1U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_11, ADC_CHANNEL_3, ADC_FIFO_NUM_1, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 1U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_12, ADC_CHANNEL_4, ADC_FIFO_NUM_1, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 1U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_13, ADC_CHANNEL_1, ADC_FIFO_NUM_1, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 1U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_14, ADC_CHANNEL_2, ADC_FIFO_NUM_1, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 1U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_15, ADC_CHANNEL_3, ADC_FIFO_NUM_1, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 1U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
                {ADC_STEP_16, ADC_CHANNEL_4, ADC_FIFO_NUM_1, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 1U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
            },
            .testMode = ADC_TEST_MODE_CPU,
            .fifoEnable = TRUE,
            .fifoNum = ADC_FIFO_NUM_1,
            .fifoThreshold = 32,
            .highRange = 0x3FFU,
            .lowRange = 0U,
            .stepIdTagEnable = TRUE,
            .errOffset = 100U,
        },
    },
#ifdef SOC_AM275X
    /* Power/Init/Clock Test Cases */
    {
        .testcaseId         = 10573U,
        .testCaseName       = "ADC Power Up/Down halt and resume",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_SINGLE_SHOT,
            .intrEnable = 0U,
            .numSteps = 1,
            .numIterations = 1,
            {
                {ADC_STEP_1, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
            },
            .testMode = ADC_TEST_MODE_API,
            .fifoEnable = TRUE,
            .fifoNum = ADC_FIFO_NUM_0,
            .fifoThreshold = 10,
            .highRange = 0x3FFU,
            .lowRange = 0U,
            .stepIdTagEnable = FALSE,
            .errOffset = 0U,
        },
    },
    {
        .testcaseId         = 10574U,
        .testCaseName       = "ADC isPoweredUp readback after power up",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_SINGLE_SHOT,
            .intrEnable = 0U,
            .numSteps = 0,
            .numIterations = 1,
            {
            },
            .testMode = ADC_TEST_MODE_API,
            .fifoEnable = FALSE,
            .fifoNum = ADC_FIFO_NUM_0,
            .fifoThreshold = 10,
            .highRange = 0x3FFU,
            .lowRange = 0U,
            .stepIdTagEnable = FALSE,
            .errOffset = 0U,
        },
    },
    {
        .testcaseId         = 10575U,
        .testCaseName       = "ADC isPoweredUp readback after power down",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_SINGLE_SHOT,
            .intrEnable = 0U,
            .numSteps = 0,
            .numIterations = 1,
            {
            },
            .testMode = ADC_TEST_MODE_API,
            .fifoEnable = FALSE,
            .fifoNum = ADC_FIFO_NUM_0,
            .fifoThreshold = 10,
            .highRange = 0x3FFU,
            .lowRange = 0U,
            .stepIdTagEnable = FALSE,
            .errOffset = 0U,
        },
    },
    {
        .testcaseId         = 10576U,
        .testCaseName       = "ADC setClkDivider no-op invariance",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_SINGLE_SHOT,
            .intrEnable = 0U,
            .numSteps = 1,
            .numIterations = 1,
            {
                {ADC_STEP_1, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
            },
            .testMode = ADC_TEST_MODE_API,
            .fifoEnable = TRUE,
            .fifoNum = ADC_FIFO_NUM_0,
            .fifoThreshold = 10,
            .highRange = 0x3FFU,
            .lowRange = 0U,
            .stepIdTagEnable = FALSE,
            .errOffset = 0U,
        },
    },
    {
        .testcaseId         = 10577U,
        .testCaseName       = "ADC init calibration-only path",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_SINGLE_SHOT,
            .intrEnable = 0U,
            .numSteps = 0,
            .numIterations = 1,
            {
            },
            .testMode = ADC_TEST_MODE_API,
            .fifoEnable = FALSE,
            .fifoNum = ADC_FIFO_NUM_0,
            .fifoThreshold = 10,
            .highRange = 0x3FFU,
            .lowRange = 0U,
            .stepIdTagEnable = FALSE,
            .errOffset = 0U,
        },
    },
    {
        .testcaseId         = 10578U,
        .testCaseName       = "ADC init errCorrection/errOffset no-effect",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_SINGLE_SHOT,
            .intrEnable = 0U,
            .numSteps = 0,
            .numIterations = 1,
            {
            },
            .testMode = ADC_TEST_MODE_API,
            .fifoEnable = FALSE,
            .fifoNum = ADC_FIFO_NUM_0,
            .fifoThreshold = 10,
            .highRange = 0x3FFU,
            .lowRange = 0U,
            .stepIdTagEnable = FALSE,
            .errOffset = 0U,
        },
    },
    {
        .testcaseId         = 10581U,
        .testCaseName       = "ADC setIdleMode idle mode functional",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_SINGLE_SHOT,
            .intrEnable = 0U,
            .numSteps = 1,
            .numIterations = 1,
            {
                {ADC_STEP_1, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_NONE,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0U, 0U},
            },
            .testMode = ADC_TEST_MODE_API,
            .fifoEnable = FALSE,
            .fifoNum = ADC_FIFO_NUM_0,
            .fifoThreshold = 1,
            .highRange = 0U,
            .lowRange = 0U,
            .stepIdTagEnable = FALSE,
            .errOffset = 0U,
        },
    },
    /* Step Setup/Control Test Cases */
    {
        .testcaseId         = 10732U,
        .testCaseName       = "ADC setStepParams valid program and field checks",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_SINGLE_SHOT,
            .intrEnable = 0U,
            .numSteps = 4,
            .numIterations = 1,
            {
                {ADC_STEP_1, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x100U, 0x50U},
                {ADC_STEP_2, ADC_CHANNEL_2, ADC_FIFO_NUM_1, ADC_AVERAGING_8_SAMPLES,
                ADC_OPERATION_MODE_CONTINUOUS, 1U, 0x200U, 0xAAU},
                {ADC_STEP_3, ADC_CHANNEL_3, ADC_FIFO_NUM_0, ADC_AVERAGING_4_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
                {ADC_STEP_4, ADC_CHANNEL_4, ADC_FIFO_NUM_1, ADC_AVERAGING_NONE,
                ADC_OPERATION_MODE_CONTINUOUS, 1U, ADC_OPENDELAY_MAX, ADC_SAMPLEDELAY_MAX},
            },
            .testMode = ADC_TEST_MODE_API,
            .fifoEnable = TRUE,
            .fifoNum = ADC_FIFO_NUM_0,
            .fifoThreshold = 10,
            .highRange = 0x3FFU,
            .lowRange = 0U,
            .stepIdTagEnable = FALSE,
            .errOffset = 0U,
        },
    },
    {
        .testcaseId         = 10733U,
        .testCaseName       = "ADC setStepParams safe reconfiguration",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_SINGLE_SHOT,
            .intrEnable = 0U,
            .numSteps = 1,
            .numIterations = 1,
            {
                {ADC_STEP_1, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
            },
            .testMode = ADC_TEST_MODE_API,
            .fifoEnable = TRUE,
            .fifoNum = ADC_FIFO_NUM_0,
            .fifoThreshold = 10,
            .highRange = 0x3FFU,
            .lowRange = 0U,
            .stepIdTagEnable = FALSE,
            .errOffset = 0U,
        },
    },
    {
        .testcaseId         = 10734U,
        .testCaseName       = "ADC setStepParams invalid openDelay",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_SINGLE_SHOT,
            .intrEnable = 0U,
            .numSteps = 0,
            .numIterations = 1,
            {
            },
            .testMode = ADC_TEST_MODE_API,
            .fifoEnable = FALSE,
            .fifoNum = ADC_FIFO_NUM_0,
            .fifoThreshold = 10,
            .highRange = 0x3FFU,
            .lowRange = 0U,
            .stepIdTagEnable = FALSE,
            .errOffset = 0U,
        },
    },
    {
        .testcaseId         = 10735U,
        .testCaseName       = "ADC setStepParams invalid sampleDelay",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_SINGLE_SHOT,
            .intrEnable = 0U,
            .numSteps = 0,
            .numIterations = 1,
            {
            },
            .testMode = ADC_TEST_MODE_API,
            .fifoEnable = FALSE,
            .fifoNum = ADC_FIFO_NUM_0,
            .fifoThreshold = 10,
            .highRange = 0x3FFU,
            .lowRange = 0U,
            .stepIdTagEnable = FALSE,
            .errOffset = 0U,
        },
    },
    {
        .testcaseId         = 10736U,
        .testCaseName       = "ADC stepEnable single step",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_SINGLE_SHOT,
            .intrEnable = 0U,
            .numSteps = 1,
            .numIterations = 1,
            {
                {ADC_STEP_1, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
            },
            .testMode = ADC_TEST_MODE_API,
            .fifoEnable = TRUE,
            .fifoNum = ADC_FIFO_NUM_0,
            .fifoThreshold = 10,
            .highRange = 0x3FFU,
            .lowRange = 0U,
            .stepIdTagEnable = FALSE,
            .errOffset = 0U,
        },
    },
    {
        .testcaseId         = 10737U,
        .testCaseName       = "ADC stepEnable multiple steps",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_SINGLE_SHOT,
            .intrEnable = 0U,
            .numSteps = 4,
            .numIterations = 1,
            {
                {ADC_STEP_1, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
                {ADC_STEP_5, ADC_CHANNEL_2, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
                {ADC_STEP_10, ADC_CHANNEL_3, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
                {ADC_STEP_16, ADC_CHANNEL_4, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
            },
            .testMode = ADC_TEST_MODE_API,
            .fifoEnable = TRUE,
            .fifoNum = ADC_FIFO_NUM_0,
            .fifoThreshold = 10,
            .highRange = 0x3FFU,
            .lowRange = 0U,
            .stepIdTagEnable = FALSE,
            .errOffset = 0U,
        },
    },
    {
        .testcaseId         = 10738U,
        .testCaseName       = "ADC stepEnable boundary bit position",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_SINGLE_SHOT,
            .intrEnable = 0U,
            .numSteps = 2,
            .numIterations = 1,
            {
                {ADC_STEP_1, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
                {ADC_STEP_16, ADC_CHANNEL_4, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
            },
            .testMode = ADC_TEST_MODE_API,
            .fifoEnable = TRUE,
            .fifoNum = ADC_FIFO_NUM_0,
            .fifoThreshold = 10,
            .highRange = 0x3FFU,
            .lowRange = 0U,
            .stepIdTagEnable = FALSE,
            .errOffset = 0U,
        },
    },
    {
        .testcaseId         = 10739U,
        .testCaseName       = "ADC clearAllSteps",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_SINGLE_SHOT,
            .intrEnable = 0U,
            .numSteps = 4,
            .numIterations = 1,
            {
                {ADC_STEP_1, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
                {ADC_STEP_5, ADC_CHANNEL_2, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
                {ADC_STEP_10, ADC_CHANNEL_3, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
                {ADC_STEP_16, ADC_CHANNEL_4, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
            },
            .testMode = ADC_TEST_MODE_API,
            .fifoEnable = TRUE,
            .fifoNum = ADC_FIFO_NUM_0,
            .fifoThreshold = 10,
            .highRange = 0x3FFU,
            .lowRange = 0U,
            .stepIdTagEnable = FALSE,
            .errOffset = 0U,
        },
    },
    {
        .testcaseId         = 10740U,
        .testCaseName       = "ADC start EN=0 with steps enabled",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_SINGLE_SHOT,
            .intrEnable = 0U,
            .numSteps = 1,
            .numIterations = 1,
            {
                {ADC_STEP_1, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
            },
            .testMode = ADC_TEST_MODE_API,
            .fifoEnable = TRUE,
            .fifoNum = ADC_FIFO_NUM_0,
            .fifoThreshold = 10,
            .highRange = 0x3FFU,
            .lowRange = 0U,
            .stepIdTagEnable = FALSE,
            .errOffset = 0U,
        },
    },
    {
        .testcaseId         = 10741U,
        .testCaseName       = "ADC start EN=1 with no steps enabled",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_SINGLE_SHOT,
            .intrEnable = 0U,
            .numSteps = 1,
            .numIterations = 1,
            {
                {ADC_STEP_1, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
            },
            .testMode = ADC_TEST_MODE_API,
            .fifoEnable = TRUE,
            .fifoNum = ADC_FIFO_NUM_0,
            .fifoThreshold = 10,
            .highRange = 0x3FFU,
            .lowRange = 0U,
            .stepIdTagEnable = FALSE,
            .errOffset = 0U,
        },
    },
    {
        .testcaseId         = 10742U,
        .testCaseName       = "ADC start EN=1 with steps enabled",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_SINGLE_SHOT,
            .intrEnable = 0U,
            .numSteps = 1,
            .numIterations = 1,
            {
                {ADC_STEP_1, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
            },
            .testMode = ADC_TEST_MODE_API,
            .fifoEnable = TRUE,
            .fifoNum = ADC_FIFO_NUM_0,
            .fifoThreshold = 10,
            .highRange = 0x3FFU,
            .lowRange = 0U,
            .stepIdTagEnable = FALSE,
            .errOffset = 0U,
        },
    },
    {
        .testcaseId         = 10743U,
        .testCaseName       = "ADC stepIdTagEnable on data format",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_SINGLE_SHOT,
            .intrEnable = 0U,
            .numSteps = 4,
            .numIterations = 1,
            {
                {ADC_STEP_1, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
                {ADC_STEP_5, ADC_CHANNEL_2, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
                {ADC_STEP_10, ADC_CHANNEL_3, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
                {ADC_STEP_16, ADC_CHANNEL_4, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
            },
            .testMode = ADC_TEST_MODE_API,
            .fifoEnable = TRUE,
            .fifoNum = ADC_FIFO_NUM_0,
            .fifoThreshold = 10,
            .highRange = 0x3FFU,
            .lowRange = 0U,
            .stepIdTagEnable = TRUE,
            .errOffset = 0U,
        },
    },
    {
        .testcaseId         = 10744U,
        .testCaseName       = "ADC stepIdTagEnable off data format",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_SINGLE_SHOT,
            .intrEnable = 0U,
            .numSteps = 4,
            .numIterations = 1,
            {
                {ADC_STEP_1, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
                {ADC_STEP_5, ADC_CHANNEL_2, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
                {ADC_STEP_10, ADC_CHANNEL_3, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
                {ADC_STEP_16, ADC_CHANNEL_4, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
            },
            .testMode = ADC_TEST_MODE_API,
            .fifoEnable = TRUE,
            .fifoNum = ADC_FIFO_NUM_0,
            .fifoThreshold = 10,
            .highRange = 0x3FFU,
            .lowRange = 0U,
            .stepIdTagEnable = FALSE,
            .errOffset = 0U,
        },
    },
    {
        .testcaseId         = 10788U,
        .testCaseName       = "ADC change step params while active",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_CONTINUOUS,
            .intrEnable = 0U,
            .numSteps = 1,
            .numIterations = 1,
            {
                {ADC_STEP_1, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_NONE,
                ADC_OPERATION_MODE_CONTINUOUS, 0x100U, 0x10U, 0U},
            },
            .testMode = ADC_TEST_MODE_API,
            .fifoEnable = TRUE,
            .fifoNum = ADC_FIFO_NUM_0,
            .fifoThreshold = 5,
            .highRange = 0U,
            .lowRange = 0U,
            .stepIdTagEnable = TRUE,
            .errOffset = 0U,
        },
    },
    /* FIFO/DMA Test Cases */
    {
        .testcaseId         = 10745U,
        .testCaseName       = "ADC getFIFOData tag on alignment",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_SINGLE_SHOT,
            .intrEnable = 0U,
            .numSteps = 4,
            .numIterations = 1,
            {
                {ADC_STEP_1, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
                {ADC_STEP_2, ADC_CHANNEL_2, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
                {ADC_STEP_3, ADC_CHANNEL_3, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
                {ADC_STEP_4, ADC_CHANNEL_4, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
            },
            .testMode = ADC_TEST_MODE_API,
            .fifoEnable = TRUE,
            .fifoNum = ADC_FIFO_NUM_0,
            .fifoThreshold = 10,
            .highRange = 0x3FFU,
            .lowRange = 0U,
            .stepIdTagEnable = TRUE,
            .errOffset = 0U,
        },
    },
    {
        .testcaseId         = 10746U,
        .testCaseName       = "ADC getFIFOData tag off alignment",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_SINGLE_SHOT,
            .intrEnable = 0U,
            .numSteps = 4,
            .numIterations = 1,
            {
                {ADC_STEP_1, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
                {ADC_STEP_2, ADC_CHANNEL_2, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
                {ADC_STEP_3, ADC_CHANNEL_3, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
                {ADC_STEP_4, ADC_CHANNEL_4, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
            },
            .testMode = ADC_TEST_MODE_API,
            .fifoEnable = TRUE,
            .fifoNum = ADC_FIFO_NUM_0,
            .fifoThreshold = 10,
            .highRange = 0x3FFU,
            .lowRange = 0U,
            .stepIdTagEnable = FALSE,
            .errOffset = 0U,
        },
    },
    {
        .testcaseId         = 10747U,
        .testCaseName       = "ADC getFIFOWordCount fill behavior",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_SINGLE_SHOT,
            .intrEnable = 0U,
            .numSteps = 16,
            .numIterations = 1,
            {
                {ADC_STEP_1, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
                {ADC_STEP_2, ADC_CHANNEL_2, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
                {ADC_STEP_3, ADC_CHANNEL_3, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
                {ADC_STEP_4, ADC_CHANNEL_4, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
                {ADC_STEP_5, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
                {ADC_STEP_6, ADC_CHANNEL_2, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
                {ADC_STEP_7, ADC_CHANNEL_3, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
                {ADC_STEP_8, ADC_CHANNEL_4, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
                {ADC_STEP_9, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
                {ADC_STEP_10, ADC_CHANNEL_2, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
                {ADC_STEP_11, ADC_CHANNEL_3, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
                {ADC_STEP_12, ADC_CHANNEL_4, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
                {ADC_STEP_13, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
                {ADC_STEP_14, ADC_CHANNEL_2, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
                {ADC_STEP_15, ADC_CHANNEL_3, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
                {ADC_STEP_16, ADC_CHANNEL_4, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
            },
            .testMode = ADC_TEST_MODE_API,
            .fifoEnable = TRUE,
            .fifoNum = ADC_FIFO_NUM_0,
            .fifoThreshold = 10,
            .highRange = 0x3FFU,
            .lowRange = 0U,
            .stepIdTagEnable = FALSE,
            .errOffset = 0U,
        },
    },
    {
        .testcaseId         = 10748U,
        .testCaseName       = "ADC getFIFOWordCount consume behavior",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_SINGLE_SHOT,
            .intrEnable = 0U,
            .numSteps = 8,
            .numIterations = 1,
            {
                {ADC_STEP_1, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
                {ADC_STEP_2, ADC_CHANNEL_2, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
                {ADC_STEP_3, ADC_CHANNEL_3, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
                {ADC_STEP_4, ADC_CHANNEL_4, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
                {ADC_STEP_5, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
                {ADC_STEP_6, ADC_CHANNEL_2, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
                {ADC_STEP_7, ADC_CHANNEL_3, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
                {ADC_STEP_8, ADC_CHANNEL_4, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
            },
            .testMode = ADC_TEST_MODE_API,
            .fifoEnable = TRUE,
            .fifoNum = ADC_FIFO_NUM_0,
            .fifoThreshold = 10,
            .highRange = 0x3FFU,
            .lowRange = 0U,
            .stepIdTagEnable = FALSE,
            .errOffset = 0U,
        },
    },
    {
        .testcaseId         = 10749U,
        .testCaseName       = "ADC CPU threshold min valid",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_SINGLE_SHOT,
            .intrEnable = 0U,
            .numSteps = 1,
            .numIterations = 1,
            {
                {ADC_STEP_1, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
            },
            .testMode = ADC_TEST_MODE_API,
            .fifoEnable = TRUE,
            .fifoNum = ADC_FIFO_NUM_0,
            .fifoThreshold = 1,
            .highRange = 0x3FFU,
            .lowRange = 0U,
            .stepIdTagEnable = FALSE,
            .errOffset = 0U,
        },
    },
    {
        .testcaseId         = 10750U,
        .testCaseName       = "ADC CPU threshold max valid",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_SINGLE_SHOT,
            .intrEnable = 0U,
            .numSteps = 1,
            .numIterations = 1,
            {
                {ADC_STEP_1, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
            },
            .testMode = ADC_TEST_MODE_API,
            .fifoEnable = TRUE,
            .fifoNum = ADC_FIFO_NUM_0,
            .fifoThreshold = 64,
            .highRange = 0x3FFU,
            .lowRange = 0U,
            .stepIdTagEnable = FALSE,
            .errOffset = 0U,
        },
    },
    {
        .testcaseId         = 10751U,
        .testCaseName       = "ADC CPU threshold below min",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_SINGLE_SHOT,
            .intrEnable = 0U,
            .numSteps = 1,
            .numIterations = 1,
            {
                {ADC_STEP_1, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
            },
            .testMode = ADC_TEST_MODE_API,
            .fifoEnable = TRUE,
            .fifoNum = ADC_FIFO_NUM_0,
            .fifoThreshold = 0,
            .highRange = 0x3FFU,
            .lowRange = 0U,
            .stepIdTagEnable = FALSE,
            .errOffset = 0U,
        },
    },
    {
        .testcaseId         = 10752U,
        .testCaseName       = "ADC CPU threshold above max",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_SINGLE_SHOT,
            .intrEnable = 0U,
            .numSteps = 1,
            .numIterations = 1,
            {
                {ADC_STEP_1, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
            },
            .testMode = ADC_TEST_MODE_API,
            .fifoEnable = TRUE,
            .fifoNum = ADC_FIFO_NUM_0,
            .fifoThreshold = 65,
            .highRange = 0x3FFU,
            .lowRange = 0U,
            .stepIdTagEnable = FALSE,
            .errOffset = 0U,
        },
    },
    {
        .testcaseId         = 10753U,
        .testCaseName       = "ADC DMA threshold min valid",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_SINGLE_SHOT,
            .intrEnable = 0U,
            .numSteps = 1,
            .numIterations = 1,
            {
                {ADC_STEP_1, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
            },
            .testMode = ADC_TEST_MODE_API,
            .fifoEnable = TRUE,
            .fifoNum = ADC_FIFO_NUM_0,
            .fifoThreshold = 1,
            .highRange = 0x3FFU,
            .lowRange = 0U,
            .stepIdTagEnable = FALSE,
            .errOffset = 0U,
        },
    },
    {
        .testcaseId         = 10754U,
        .testCaseName       = "ADC DMA threshold max valid",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_SINGLE_SHOT,
            .intrEnable = 0U,
            .numSteps = 1,
            .numIterations = 1,
            {
                {ADC_STEP_1, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
            },
            .testMode = ADC_TEST_MODE_API,
            .fifoEnable = TRUE,
            .fifoNum = ADC_FIFO_NUM_0,
            .fifoThreshold = 64,
            .highRange = 0x3FFU,
            .lowRange = 0U,
            .stepIdTagEnable = FALSE,
            .errOffset = 0U,
        },
    },
    {
        .testcaseId         = 10755U,
        .testCaseName       = "ADC DMA threshold below min",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_SINGLE_SHOT,
            .intrEnable = 0U,
            .numSteps = 1,
            .numIterations = 1,
            {
                {ADC_STEP_1, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
            },
            .testMode = ADC_TEST_MODE_API,
            .fifoEnable = TRUE,
            .fifoNum = ADC_FIFO_NUM_0,
            .fifoThreshold = 0,
            .highRange = 0x3FFU,
            .lowRange = 0U,
            .stepIdTagEnable = FALSE,
            .errOffset = 0U,
        },
    },
    {
        .testcaseId         = 10756U,
        .testCaseName       = "ADC DMA threshold above max",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_SINGLE_SHOT,
            .intrEnable = 0U,
            .numSteps = 1,
            .numIterations = 1,
            {
                {ADC_STEP_1, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
            },
            .testMode = ADC_TEST_MODE_API,
            .fifoEnable = TRUE,
            .fifoNum = ADC_FIFO_NUM_0,
            .fifoThreshold = 65,
            .highRange = 0x3FFU,
            .lowRange = 0U,
            .stepIdTagEnable = FALSE,
            .errOffset = 0U,
        },
    },
    {
        .testcaseId         = 10757U,
        .testCaseName       = "ADC DMA access enable FIFO0",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_SINGLE_SHOT,
            .intrEnable = 0U,
            .numSteps = 1,
            .numIterations = 1,
            {
                {ADC_STEP_1, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
            },
            .testMode = ADC_TEST_MODE_API,
            .fifoEnable = TRUE,
            .fifoNum = ADC_FIFO_NUM_0,
            .fifoThreshold = 10,
            .highRange = 0x3FFU,
            .lowRange = 0U,
            .stepIdTagEnable = FALSE,
            .errOffset = 0U,
        },
    },
    {
        .testcaseId         = 10758U,
        .testCaseName       = "ADC DMA access disable FIFO0",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_SINGLE_SHOT,
            .intrEnable = 0U,
            .numSteps = 1,
            .numIterations = 1,
            {
                {ADC_STEP_1, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
            },
            .testMode = ADC_TEST_MODE_API,
            .fifoEnable = TRUE,
            .fifoNum = ADC_FIFO_NUM_0,
            .fifoThreshold = 10,
            .highRange = 0x3FFU,
            .lowRange = 0U,
            .stepIdTagEnable = FALSE,
            .errOffset = 0U,
        },
    },
    {
        .testcaseId         = 10759U,
        .testCaseName       = "ADC DMA access enable FIFO1",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_SINGLE_SHOT,
            .intrEnable = 0U,
            .numSteps = 1,
            .numIterations = 1,
            {
                {ADC_STEP_1, ADC_CHANNEL_1, ADC_FIFO_NUM_1, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
            },
            .testMode = ADC_TEST_MODE_API,
            .fifoEnable = TRUE,
            .fifoNum = ADC_FIFO_NUM_1,
            .fifoThreshold = 10,
            .highRange = 0x3FFU,
            .lowRange = 0U,
            .stepIdTagEnable = FALSE,
            .errOffset = 0U,
        },
    },
    {
        .testcaseId         = 10760U,
        .testCaseName       = "ADC DMA access disable FIFO1",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_SINGLE_SHOT,
            .intrEnable = 0U,
            .numSteps = 1,
            .numIterations = 1,
            {
                {ADC_STEP_1, ADC_CHANNEL_1, ADC_FIFO_NUM_1, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
            },
            .testMode = ADC_TEST_MODE_API,
            .fifoEnable = TRUE,
            .fifoNum = ADC_FIFO_NUM_1,
            .fifoThreshold = 10,
            .highRange = 0x3FFU,
            .lowRange = 0U,
            .stepIdTagEnable = FALSE,
            .errOffset = 0U,
        },
    },
    {
        .testcaseId         = 10790U,
        .testCaseName       = "ADC change threshold while active",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_CONTINUOUS,
            .intrEnable = 0U,
            .numSteps = 1,
            .numIterations = 1,
            {
                {ADC_STEP_1, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_NONE,
                ADC_OPERATION_MODE_CONTINUOUS, 0x100U, 0x10U, 0U},
            },
            .testMode = ADC_TEST_MODE_API,
            .fifoEnable = TRUE,
            .fifoNum = ADC_FIFO_NUM_0,
            .fifoThreshold = 5,
            .highRange = 0U,
            .lowRange = 0U,
            .stepIdTagEnable = FALSE,
            .errOffset = 0U,
        },
    },
    {
        .testcaseId         = 10791U,
        .testCaseName       = "ADC CPU poll overflow",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_CONTINUOUS,
            .intrEnable = 0U,
            .numSteps = 1,
            .numIterations = 1,
            {
                {ADC_STEP_1, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_NONE,
                ADC_OPERATION_MODE_CONTINUOUS, 0x10U, 0x01U, 0U},
            },
            .testMode = ADC_TEST_MODE_API,
            .fifoEnable = TRUE,
            .fifoNum = ADC_FIFO_NUM_0,
            .fifoThreshold = 64,
            .highRange = 0U,
            .lowRange = 0U,
            .stepIdTagEnable = FALSE,
            .errOffset = 0U,
        },
    },
    {
        .testcaseId         = 10792U,
        .testCaseName       = "ADC CPU poll underflow",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_SINGLE_SHOT,
            .intrEnable = 0U,
            .numSteps = 1,
            .numIterations = 1,
            {
                {ADC_STEP_1, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_NONE,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0x100U, 0x10U, 0U},
            },
            .testMode = ADC_TEST_MODE_API,
            .fifoEnable = TRUE,
            .fifoNum = ADC_FIFO_NUM_0,
            .fifoThreshold = 1,
            .highRange = 0U,
            .lowRange = 0U,
            .stepIdTagEnable = FALSE,
            .errOffset = 0U,
        },
    },
    {
        .testcaseId         = 10793U,
        .testCaseName       = "ADC DMA overflow",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_CONTINUOUS,
            .intrEnable = 0U,
            .numSteps = 1,
            .numIterations = 1,
            {
                {ADC_STEP_1, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_NONE,
                ADC_OPERATION_MODE_CONTINUOUS, 0x10U, 0x01U, 0U},
            },
            .testMode = ADC_TEST_MODE_API,
            .fifoEnable = TRUE,
            .fifoNum = ADC_FIFO_NUM_0,
            .fifoThreshold = 4,
            .highRange = 0U,
            .lowRange = 0U,
            .stepIdTagEnable = FALSE,
            .errOffset = 0U,
        },
    },
    {
        .testcaseId         = 10794U,
        .testCaseName       = "ADC DMA underflow",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_SINGLE_SHOT,
            .intrEnable = 0U,
            .numSteps = 1,
            .numIterations = 1,
            {
                {ADC_STEP_1, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_NONE,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0x100U, 0x10U, 0U},
            },
            .testMode = ADC_TEST_MODE_API,
            .fifoEnable = TRUE,
            .fifoNum = ADC_FIFO_NUM_0,
            .fifoThreshold = 1,
            .highRange = 0U,
            .lowRange = 0U,
            .stepIdTagEnable = FALSE,
            .errOffset = 0U,
        },
    },
    {
        .testcaseId         = 10761U,
        .testCaseName       = "ADC get CPU FIFO threshold levels",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_SINGLE_SHOT,
            .intrEnable = 0U,
            .numSteps = 1,
            .numIterations = 1,
            {
                {ADC_STEP_1, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_NONE,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0x100U, 0x10U, 0U},
            },
            .testMode = ADC_TEST_MODE_API,
            .fifoEnable = TRUE,
            .fifoNum = ADC_FIFO_NUM_0,
            .fifoThreshold = 10,
            .highRange = 0U,
            .lowRange = 0U,
            .stepIdTagEnable = FALSE,
            .errOffset = 0U,
        },
    },
    {
        .testcaseId         = 10762U,
        .testCaseName       = "ADC get DMA FIFO threshold levels",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_SINGLE_SHOT,
            .intrEnable = 0U,
            .numSteps = 1,
            .numIterations = 1,
            {
                {ADC_STEP_1, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_NONE,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0x100U, 0x10U, 0U},
            },
            .testMode = ADC_TEST_MODE_API,
            .fifoEnable = TRUE,
            .fifoNum = ADC_FIFO_NUM_0,
            .fifoThreshold = 15,
            .highRange = 0U,
            .lowRange = 0U,
            .stepIdTagEnable = FALSE,
            .errOffset = 0U,
        },
    },
    {
        .testcaseId         = 10763U,
        .testCaseName       = "ADC DMA line config FIFO0",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_SINGLE_SHOT,
            .intrEnable = 0U,
            .numSteps = 8,
            .numIterations = 1,
            {
                {ADC_STEP_1, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_NONE,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0U, 0U},
            },
            .testMode = ADC_TEST_MODE_API,
            .fifoEnable = TRUE,
            .fifoNum = ADC_FIFO_NUM_0,
            .fifoThreshold = 4,
            .highRange = 0U,
            .lowRange = 0U,
            .stepIdTagEnable = FALSE,
            .errOffset = 0U,
        },
    },
    {
        .testcaseId         = 10764U,
        .testCaseName       = "ADC DMA line config FIFO1",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_SINGLE_SHOT,
            .intrEnable = 0U,
            .numSteps = 8,
            .numIterations = 1,
            {
                {ADC_STEP_1, ADC_CHANNEL_1, ADC_FIFO_NUM_1, ADC_AVERAGING_NONE,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0U, 0U},
            },
            .testMode = ADC_TEST_MODE_API,
            .fifoEnable = TRUE,
            .fifoNum = ADC_FIFO_NUM_1,
            .fifoThreshold = 4,
            .highRange = 0U,
            .lowRange = 0U,
            .stepIdTagEnable = FALSE,
            .errOffset = 0U,
        },
    },
    {
        .testcaseId         = 10765U,
        .testCaseName       = "ADC FIFO data read sequential",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_SINGLE_SHOT,
            .intrEnable = 0U,
            .numSteps = 4,
            .numIterations = 1,
            {
                {ADC_STEP_1, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_NONE,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0U, 0U},
            },
            .testMode = ADC_TEST_MODE_API,
            .fifoEnable = TRUE,
            .fifoNum = ADC_FIFO_NUM_0,
            .fifoThreshold = 4,
            .highRange = 0U,
            .lowRange = 0U,
            .stepIdTagEnable = TRUE,
            .errOffset = 0U,
        },
    },
    {
        .testcaseId         = 10766U,
        .testCaseName       = "ADC DMA transfer completion",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_SINGLE_SHOT,
            .intrEnable = 0U,
            .numSteps = 8,
            .numIterations = 1,
            {
                {ADC_STEP_1, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_NONE,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0U, 0U},
            },
            .testMode = ADC_TEST_MODE_API,
            .fifoEnable = TRUE,
            .fifoNum = ADC_FIFO_NUM_0,
            .fifoThreshold = 4,
            .highRange = 0U,
            .lowRange = 0U,
            .stepIdTagEnable = FALSE,
            .errOffset = 0U,
        },
    },
    /* Interrupt/EOI Test Cases */
    {
        .testcaseId         = 10767U,
        .testCaseName       = "ADC enableIntr mask all sources",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_SINGLE_SHOT,
            .intrEnable = ADC_INTR_SRC_END_OF_SEQUENCE | ADC_INTR_SRC_FIFO0_THRESHOLD |
                          ADC_INTR_SRC_FIFO0_OVERRUN | ADC_INTR_SRC_FIFO0_UNDERFLOW |
                          ADC_INTR_SRC_FIFO1_THRESHOLD | ADC_INTR_SRC_FIFO1_OVERRUN |
                          ADC_INTR_SRC_FIFO1_UNDERFLOW | ADC_INTR_SRC_OUT_OF_RANGE,
            .numSteps = 1,
            .numIterations = 1,
            {
                {ADC_STEP_1, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
            },
            .testMode = ADC_TEST_MODE_API,
            .fifoEnable = TRUE,
            .fifoNum = ADC_FIFO_NUM_0,
            .fifoThreshold = 10,
            .highRange = 0x3FFU,
            .lowRange = 0U,
            .stepIdTagEnable = FALSE,
            .errOffset = 0U,
        },
    },
    {
        .testcaseId         = 10769U,
        .testCaseName       = "ADC disableIntr unmask all sources",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_SINGLE_SHOT,
            .intrEnable = 0U,
            .numSteps = 1,
            .numIterations = 1,
            {
                {ADC_STEP_1, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
            },
            .testMode = ADC_TEST_MODE_API,
            .fifoEnable = TRUE,
            .fifoNum = ADC_FIFO_NUM_0,
            .fifoThreshold = 10,
            .highRange = 0x3FFU,
            .lowRange = 0U,
            .stepIdTagEnable = FALSE,
            .errOffset = 0U,
        },
    },
    {
        .testcaseId         = 10771U,
        .testCaseName       = "ADC getIntrStatus masked",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_SINGLE_SHOT,
            .intrEnable = ADC_INTR_SRC_END_OF_SEQUENCE | ADC_INTR_SRC_FIFO0_THRESHOLD,
            .numSteps = 1,
            .numIterations = 1,
            {
                {ADC_STEP_1, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
            },
            .testMode = ADC_TEST_MODE_API,
            .fifoEnable = TRUE,
            .fifoNum = ADC_FIFO_NUM_0,
            .fifoThreshold = 10,
            .highRange = 0x3FFU,
            .lowRange = 0U,
            .stepIdTagEnable = FALSE,
            .errOffset = 0U,
        },
    },
    {
        .testcaseId         = 10772U,
        .testCaseName       = "ADC getIntrStatus raw unmasked",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_SINGLE_SHOT,
            .intrEnable = 0U,
            .numSteps = 1,
            .numIterations = 1,
            {
                {ADC_STEP_1, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
            },
            .testMode = ADC_TEST_MODE_API,
            .fifoEnable = TRUE,
            .fifoNum = ADC_FIFO_NUM_0,
            .fifoThreshold = 10,
            .highRange = 0x3FFU,
            .lowRange = 0U,
            .stepIdTagEnable = FALSE,
            .errOffset = 0U,
        },
    },
    {
        .testcaseId         = 10773U,
        .testCaseName       = "ADC clearIntrStatus W1C",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_SINGLE_SHOT,
            .intrEnable = ADC_INTR_SRC_END_OF_SEQUENCE | ADC_INTR_SRC_FIFO0_THRESHOLD |
                          ADC_INTR_SRC_FIFO0_OVERRUN,
            .numSteps = 1,
            .numIterations = 1,
            {
                {ADC_STEP_1, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
            },
            .testMode = ADC_TEST_MODE_API,
            .fifoEnable = TRUE,
            .fifoNum = ADC_FIFO_NUM_0,
            .fifoThreshold = 10,
            .highRange = 0x3FFU,
            .lowRange = 0U,
            .stepIdTagEnable = FALSE,
            .errOffset = 0U,
        },
    },
    {
        .testcaseId         = 10774U,
        .testCaseName       = "ADC writeEOI clear then EOI",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_SINGLE_SHOT,
            .intrEnable = ADC_INTR_SRC_END_OF_SEQUENCE,
            .numSteps = 1,
            .numIterations = 1,
            {
                {ADC_STEP_1, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
            },
            .testMode = ADC_TEST_MODE_API,
            .fifoEnable = TRUE,
            .fifoNum = ADC_FIFO_NUM_0,
            .fifoThreshold = 10,
            .highRange = 0x3FFU,
            .lowRange = 0U,
            .stepIdTagEnable = FALSE,
            .errOffset = 0U,
        },
    },
    /* Range/Status Test Cases */
    {
        .testcaseId         = 10775U,
        .testCaseName       = "ADC setGetRange valid",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_SINGLE_SHOT,
            .intrEnable = 0U,
            .numSteps = 1,
            .numIterations = 1,
            {
                {ADC_STEP_1, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
            },
            .testMode = ADC_TEST_MODE_API,
            .fifoEnable = TRUE,
            .fifoNum = ADC_FIFO_NUM_0,
            .fifoThreshold = 10,
            .highRange = 0x300U,
            .lowRange = 0x100U,
            .stepIdTagEnable = FALSE,
            .errOffset = 0U,
        },
    },
    {
        .testcaseId         = 10776U,
        .testCaseName       = "ADC setRange low greater than high",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_SINGLE_SHOT,
            .intrEnable = 0U,
            .numSteps = 1,
            .numIterations = 1,
            {
                {ADC_STEP_1, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
            },
            .testMode = ADC_TEST_MODE_API,
            .fifoEnable = TRUE,
            .fifoNum = ADC_FIFO_NUM_0,
            .fifoThreshold = 10,
            .highRange = 0x200U,
            .lowRange = 0x500U,
            .stepIdTagEnable = FALSE,
            .errOffset = 0U,
        },
    },
    {
        .testcaseId         = 10777U,
        .testCaseName       = "ADC setRange high above max",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_SINGLE_SHOT,
            .intrEnable = 0U,
            .numSteps = 1,
            .numIterations = 1,
            {
                {ADC_STEP_1, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
            },
            .testMode = ADC_TEST_MODE_API,
            .fifoEnable = TRUE,
            .fifoNum = ADC_FIFO_NUM_0,
            .fifoThreshold = 10,
            .highRange = 0x1500U,
            .lowRange = 0x100U,
            .stepIdTagEnable = FALSE,
            .errOffset = 0U,
        },
    },
    {
        .testcaseId         = 10778U,
        .testCaseName       = "ADC range violation interrupt",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_SINGLE_SHOT,
            .intrEnable = ADC_INTR_SRC_OUT_OF_RANGE,
            .numSteps = 1,
            .numIterations = 1,
            {
                {ADC_STEP_1, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_NONE,
                ADC_OPERATION_MODE_SINGLE_SHOT, 1U, 0x1U, 0U},
            },
            .testMode = ADC_TEST_MODE_API,
            .fifoEnable = TRUE,
            .fifoNum = ADC_FIFO_NUM_0,
            .fifoThreshold = 10,
            .highRange = 0x300U,
            .lowRange = 0x200U,
            .stepIdTagEnable = FALSE,
            .errOffset = 0U,
        },
    },
    {
        .testcaseId         = 10779U,
        .testCaseName       = "ADC getSequencerStatus busy",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_SINGLE_SHOT,
            .intrEnable = 0U,
            .numSteps = 4,
            .numIterations = 1,
            {
                {ADC_STEP_1, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x100U, 0xFFU}, /* sampleDelay: 0x100U->0xFFU (ADC_SAMPLEDELAY_MAX) */
                {ADC_STEP_2, ADC_CHANNEL_2, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x100U, 0xFFU}, /* sampleDelay: 0x100U->0xFFU */
                {ADC_STEP_3, ADC_CHANNEL_3, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x100U, 0xFFU}, /* sampleDelay: 0x100U->0xFFU */
                {ADC_STEP_4, ADC_CHANNEL_4, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x100U, 0xFFU}, /* sampleDelay: 0x100U->0xFFU */
            },
            .testMode = ADC_TEST_MODE_API,
            .fifoEnable = TRUE,
            .fifoNum = ADC_FIFO_NUM_0,
            .fifoThreshold = 10,
            .highRange = 0x3FFU,
            .lowRange = 0U,
            .stepIdTagEnable = FALSE,
            .errOffset = 0U,
        },
    },
    {
        .testcaseId         = 10780U,
        .testCaseName       = "ADC getSequencerStatus idle",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_SINGLE_SHOT,
            .intrEnable = 0U,
            .numSteps = 1,
            .numIterations = 1,
            {
                {ADC_STEP_1, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_16_SAMPLES,
                ADC_OPERATION_MODE_SINGLE_SHOT, 0U, 0x1U, 0U},
            },
            .testMode = ADC_TEST_MODE_API,
            .fifoEnable = TRUE,
            .fifoNum = ADC_FIFO_NUM_0,
            .fifoThreshold = 10,
            .highRange = 0x3FFU,
            .lowRange = 0U,
            .stepIdTagEnable = FALSE,
            .errOffset = 0U,
        },
    },
    {
        .testcaseId         = 10789U,
        .testCaseName       = "ADC change range while active",
        .adcConfigParams    =
        {
            .adcModule = ADC_TEST_BASE_ADDR,
            .adcMode = ADC_OPERATION_MODE_CONTINUOUS,
            .intrEnable = 0U,
            .numSteps = 1,
            .numIterations = 1,
            {
                {ADC_STEP_1, ADC_CHANNEL_1, ADC_FIFO_NUM_0, ADC_AVERAGING_NONE,
                ADC_OPERATION_MODE_CONTINUOUS, 0x100U, 0x10U, 1U},
            },
            .testMode = ADC_TEST_MODE_API,
            .fifoEnable = TRUE,
            .fifoNum = ADC_FIFO_NUM_0,
            .fifoThreshold = 5,
            .highRange = 0x300U,
            .lowRange = 0x100U,
            .stepIdTagEnable = FALSE,
            .errOffset = 0U,
        },
    },
#endif /* #ifdef SOC_AM275X */
};

#endif /* #ifndef ST_UART_TEST_CASES_H_ */
