MODULE_NAME = rm_pm_hal_src

SRCDIR = src/rm_pm_hal_src
INCDIR = src/rm_pm_hal_src src/
# Can be removed
PDK_CFLAGS =  -DBUILD_MCU1_0 -DBUILD_MCU

CFLAGS_LOCAL_COMMON = $(PDK_CFLAGS)

# RM & PM HAL Configuration
CONFIG_ADDR_REMAP_OFFSET=0x00000000
CONFIG_DM_BUILD=y
CONFIG_PM=y
CONFIG_PSC=y
CONFIG_CLOCK=y
CONFIG_CLK_ADPLLM=y
CONFIG_CLK_PLL_16FFT=y
CONFIG_CLK_PLL_DESKEW=y
CONFIG_TRACE=y
CONFIG_TRACE_BUFFER=y
CONFIG_TRACE_UART=y
CONFIG_SOC_FOLDER_STRING=am62x
CONFIG_CLK_PLL_16FFT_FRACF_CALIBRATION=y
CONFIG_SEC_PROXY_DRIVER=y
CONFIG_GET_FW_CAPS=y
SCICLIENT_SOCVER = V5

RM_PM_HAL_BUILD_PATH=../rm_pm_hal_src
