/*
 * Copyright (c) 2025, Texas Instruments Incorporated
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * *  Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 * *  Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * *  Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
 * OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */

/**
 *
 * \file  hyperRam.h
 *
 * \brief This file contains structure, typedefs, functions and
 *        prototypes used for Hyperram.
 *
 *****************************************************************************/
 #ifndef hyperRam_H_
 #define hyperRam_H_
 

/* ========================================================================== */
/*                             Include Files                                  */
/* ========================================================================== */

#include <stdint.h>
#include <kernel/dpl/SystemP.h>
#include <drivers/hw_include/soc_config.h>
#include <drivers/hyperbus.h>
#include <kernel/dpl/SemaphoreP.h>

 #ifdef __cplusplus
 extern "C"
 {
 #endif
 
/* ========================================================================== */
/*                           Macros & Typedefs                                */
/* ========================================================================== */

 /**
  *  \defgroup BOARD_HYPERRAM_MODULE APIs for HYPERRAM
  *  \ingroup BOARD_MODULE
  *
  *  This module contains APIs to program and use the HyperRAM module on the board .
  *  See \ref BOARD_HYPERRAM_PAGE for more details.
  *
  *  @{
  */
 
 /**
  * \brief Handle to the HYPERRAM driver returned by HyperRam_open()
  */
 typedef void  *HYPERRAM_Handle;

 /**
  * \brief Forward declaration of \ref HyperRam_Config_s
  */
 typedef struct HyperRam_Config_s HyperRam_Config;
 
/* ========================================================================== */
/*                         Structure Declarations                             */
/* ========================================================================== */

 /**
  * \brief HyperRam device attributes, these are filled by SysCfg based on the HyperRam device that is selected.
  */
 typedef struct HyperRam_Attrs_s {
    char *HyperRamName;
    /**< HyperRam name. Taken from Sysconfig */
    uint32_t driverInstance;
    /**< Underlying HYPERBUS peripheral driver instance that is used by the HYPERRAM driver, e.g HYPERBUS driver */
    uint16_t CR0;
    /**< HyperRam device register CR0 */
    uint16_t CR1;
    /**< HyperRam device register CR1 */
    uint16_t ID0;
    /**< HyperRam device register ID0 */
    uint16_t ID1;
    /**< HyperRam device register ID1 */

 } HyperRam_Attrs;
 
 /**
  * \brief HyperRam driver configuration, these are filled by SysCfg based on the HyperRam device that is selected.
  */
 struct HyperRam_Config_s
 {
    HyperRam_Attrs *attrs;
    /**< HyperRam device attributes */
    void *object;
    /**< HyperRam driver object, used to maintain driver implementation state */
 
 };
 
/* ========================================================================== */
/*                          Function Declarations                             */
/* ========================================================================== */

/**
 *  \brief  This function initializes the HYPERBUS module
 */
void HyperRam_init(void);

/**
 *  \brief  This function de-initializes the HYPERBUS module
 */
void HyperRam_deinit(void);

/**
 * \brief Open HyperRam driver
 *
 * Make sure the SOC peripheral driver is opened before calling this API.
 * Drivers_open function generated by SysCfg opens the underlying SOC peripheral driver, e.g HYPERBUS.
 *
 * Internally this API also reads the device and manufacture ID and checks if it matches the
 * expected value for the HYPERRAM device, if there is mismatch then `NULL` is returned.
 *
 * Global variables `HYPERRAM_Config gHyperRamConfig[]` and `uint32_t gHyperRamConfigNum` is instantiated by SysCfg
 * to describe the HYPERRAM configuration based on user selection in SysCfg.
 *
 * \param instanceId [in] Index within `HyperRam_Config gHyperRamConfig[]` denoting the HyperRam driver to open
 *
 * \return Handle to HyperRam driver which should be used in subsequent API call
 * \return NULL in case of failure
 */
HYPERRAM_Handle HyperRam_open(uint32_t instanceId);

/**
 * \brief Close HyperRam driver
 *
 * \param handle    [in] HyperRam driver handle from \ref HyperRam_open
 */
 void HyperRam_close(HYPERRAM_Handle handle);

/** @} */

/* ========================================================================== */
/*                       Static Function Definitions                          */
/* ========================================================================== */

/* None */

/* ========================================================================== */
/*                  Internal/Private Structure Declarations                   */
/* ========================================================================== */

typedef struct {
   HYPERRAM_Handle handle;
   /**< Instance handle */
   HYPERBUS_Handle hyperbusHandle;
   /**< Handle of the underlying HyperBus instance */
   uint32_t isOpen;
   /**< Flag to indicate if the instance is already open */
   SemaphoreP_Object       lockObj;
   /**< Transfer Sync Semaphore object */
 
 } HyperRam_Object;

 #ifdef __cplusplus
 }
 #endif
 
 #endif /* hyperRam_H_ */
