/******************************************************************************
 * Copyright (C) 2012-2026 Cadence Design Systems, Inc.
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 
 * 1. Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 * notice, this list of conditions and the following disclaimer in the
 * documentation and/or other materials provided with the distribution.
 * 3. Neither the name of the copyright holder nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT
 *
 *****************************************************************************/

// parasoft-begin-suppress MISRA2012-RULE-1_1_b_c90-2 "C90 - limits"
// parasoft-begin-suppress MISRA2012-RULE-1_1_b_c99-2 "C99 - limits"

// parasoft-begin-suppress MISRA2012-RULE-5_4_b_c90-2 "C90 - similar names"
// parasoft-begin-suppress MISRA2012-RULE-5_4_b_c99-2 "C99 - similar names"

#ifndef REG_DPHY_REGS_MACROS_H_
#define REG_DPHY_REGS_MACROS_H_

#define DPHY__CMN0_CMN_DIG_TBIT13_READ_MASK                           0xFFFFFFFFU
#define DPHY__CMN0_CMN_DIG_TBIT13_WRITE_MASK                          0xFFFFFFFFU
#define DPHY__CMN0_CMN_DIG_TBIT13__UNUSED_MASK                        0x000003FFU
#define DPHY__CMN0_CMN_DIG_TBIT13__UNUSED_SHIFT                                0U
#define DPHY__CMN0_CMN_DIG_TBIT13__UNUSED_WIDTH                               10U
#define DPHY__CMN0_CMN_DIG_TBIT13__O_ANA_PLL_FB_DIV_HIGH_TM_SEL_MASK  0x00000400U
#define DPHY__CMN0_CMN_DIG_TBIT13__O_ANA_PLL_FB_DIV_HIGH_TM_SEL_SHIFT         10U
#define DPHY__CMN0_CMN_DIG_TBIT13__O_ANA_PLL_FB_DIV_HIGH_TM_SEL_WIDTH          1U
#define DPHY__CMN0_CMN_DIG_TBIT13__O_ANA_PLL_FB_DIV_HIGH_TM_SEL_WOCLR          0U
#define DPHY__CMN0_CMN_DIG_TBIT13__O_ANA_PLL_FB_DIV_HIGH_TM_SEL_WOSET          0U
#define DPHY__CMN0_CMN_DIG_TBIT13__O_ANA_PLL_FB_DIV_HIGH_TM_MASK      0x001FF800U
#define DPHY__CMN0_CMN_DIG_TBIT13__O_ANA_PLL_FB_DIV_HIGH_TM_SHIFT             11U
#define DPHY__CMN0_CMN_DIG_TBIT13__O_ANA_PLL_FB_DIV_HIGH_TM_WIDTH             10U
#define DPHY__CMN0_CMN_DIG_TBIT13__O_ANA_PLL_FB_DIV_LOW_TM_SEL_MASK   0x00200000U
#define DPHY__CMN0_CMN_DIG_TBIT13__O_ANA_PLL_FB_DIV_LOW_TM_SEL_SHIFT          21U
#define DPHY__CMN0_CMN_DIG_TBIT13__O_ANA_PLL_FB_DIV_LOW_TM_SEL_WIDTH           1U
#define DPHY__CMN0_CMN_DIG_TBIT13__O_ANA_PLL_FB_DIV_LOW_TM_SEL_WOCLR           0U
#define DPHY__CMN0_CMN_DIG_TBIT13__O_ANA_PLL_FB_DIV_LOW_TM_SEL_WOSET           0U
#define DPHY__CMN0_CMN_DIG_TBIT13__O_ANA_PLL_FB_DIV_LOW_TM_MASK       0xFFC00000U
#define DPHY__CMN0_CMN_DIG_TBIT13__O_ANA_PLL_FB_DIV_LOW_TM_SHIFT              22U
#define DPHY__CMN0_CMN_DIG_TBIT13__O_ANA_PLL_FB_DIV_LOW_TM_WIDTH              10U

#define DPHY__CMN0_CMN_DIG_TBIT14_READ_MASK                           0xFFFFFFFFU
#define DPHY__CMN0_CMN_DIG_TBIT14_WRITE_MASK                          0xFFFFFFFFU
#define DPHY__CMN0_CMN_DIG_TBIT14__O_ANA_PLL_IP_DIV_TM_SEL_MASK       0x00000001U
#define DPHY__CMN0_CMN_DIG_TBIT14__O_ANA_PLL_IP_DIV_TM_SEL_SHIFT               0U
#define DPHY__CMN0_CMN_DIG_TBIT14__O_ANA_PLL_IP_DIV_TM_SEL_WIDTH               1U
#define DPHY__CMN0_CMN_DIG_TBIT14__O_ANA_PLL_IP_DIV_TM_SEL_WOCLR               0U
#define DPHY__CMN0_CMN_DIG_TBIT14__O_ANA_PLL_IP_DIV_TM_SEL_WOSET               0U
#define DPHY__CMN0_CMN_DIG_TBIT14__O_ANA_PLL_IP_DIV_TM_MASK           0x0000003EU
#define DPHY__CMN0_CMN_DIG_TBIT14__O_ANA_PLL_IP_DIV_TM_SHIFT                   1U
#define DPHY__CMN0_CMN_DIG_TBIT14__O_ANA_PLL_IP_DIV_TM_WIDTH                   5U
#define DPHY__CMN0_CMN_DIG_TBIT14__O_ANA_PLL_OP_DIV_TM_SEL_MASK       0x00000040U
#define DPHY__CMN0_CMN_DIG_TBIT14__O_ANA_PLL_OP_DIV_TM_SEL_SHIFT               6U
#define DPHY__CMN0_CMN_DIG_TBIT14__O_ANA_PLL_OP_DIV_TM_SEL_WIDTH               1U
#define DPHY__CMN0_CMN_DIG_TBIT14__O_ANA_PLL_OP_DIV_TM_SEL_WOCLR               0U
#define DPHY__CMN0_CMN_DIG_TBIT14__O_ANA_PLL_OP_DIV_TM_SEL_WOSET               0U
#define DPHY__CMN0_CMN_DIG_TBIT14__O_ANA_PLL_OP_DIV_TM_MASK           0x00001F80U
#define DPHY__CMN0_CMN_DIG_TBIT14__O_ANA_PLL_OP_DIV_TM_SHIFT                   7U
#define DPHY__CMN0_CMN_DIG_TBIT14__O_ANA_PLL_OP_DIV_TM_WIDTH                   6U
#define DPHY__CMN0_CMN_DIG_TBIT14__UNUSED_MASK                        0xFFFFE000U
#define DPHY__CMN0_CMN_DIG_TBIT14__UNUSED_SHIFT                               13U
#define DPHY__CMN0_CMN_DIG_TBIT14__UNUSED_WIDTH                               19U

#endif /* REG_DPHY_REGS_MACROS_H_ */

// parasoft-end-suppress MISRA2012-RULE-5_4_b_c99-2 "C99 - similar names"
// parasoft-end-suppress MISRA2012-RULE-5_4_b_c90-2 "C90 - similar names"

// parasoft-end-suppress MISRA2012-RULE-1_1_b_c99-2 "C99 - limits"
// parasoft-end-suppress MISRA2012-RULE-1_1_b_c90-2 "C90 - limits"

